"""
Skill Editor Agent Schemas

Pydantic schemas for structured agent responses, inspired by BubbleLab's approach.
These schemas ensure type-safe communication between agents and the frontend.
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from dataclasses import dataclass, field, asdict
from pydantic import BaseModel, Field


# ============================================================
# Enums
# ============================================================

class IntentType(str, Enum):
    """Types of user intents the agent can recognize"""
    CREATE_FLOWGRAM = "create_flowgram"
    ADD_NODE = "add_node"
    REMOVE_NODE = "remove_node"
    CONNECT_NODES = "connect_nodes"
    MODIFY_NODE = "modify_node"
    RUN_FLOWGRAM = "run_flowgram"
    DEBUG_FLOWGRAM = "debug_flowgram"
    EXPLAIN = "explain"
    GENERAL_CHAT = "general_chat"
    UNKNOWN = "unknown"


class PlannerAction(str, Enum):
    """Actions the planner agent can take"""
    ASK_CLARIFICATION = "ask_clarification"
    GATHER_CONTEXT = "gather_context"
    GENERATE_PLAN = "generate_plan"
    PROCEED_TO_CODE = "proceed_to_code"


class CodeAgentAction(str, Enum):
    """Actions the code agent can take"""
    GENERATE_FLOWGRAM = "generate_flowgram"
    EDIT_FLOWGRAM = "edit_flowgram"
    VALIDATE = "validate"
    ANSWER = "answer"
    REJECT = "reject"


# ============================================================
# Clarification Schemas
# ============================================================

class ClarificationChoice(BaseModel):
    """A choice option for a clarification question"""
    id: str = Field(..., description="Unique identifier for this choice")
    label: str = Field(..., description="Display label for the choice")
    description: Optional[str] = Field(None, description="Additional description")


class ClarificationQuestion(BaseModel):
    """A clarification question to ask the user"""
    id: str = Field(..., description="Unique identifier for this question")
    question: str = Field(..., description="The question text")
    choices: List[ClarificationChoice] = Field(..., description="Available choices")
    context: Optional[str] = Field(None, description="Why this question is important")
    allow_multiple: bool = Field(False, description="Whether multiple choices can be selected")


class ClarificationResponse(BaseModel):
    """User's response to clarification questions"""
    answers: Dict[str, List[str]] = Field(..., description="Map of question_id to selected choice_ids")


# ============================================================
# Plan Schemas
# ============================================================

class PlanStep(BaseModel):
    """A step in the implementation plan"""
    title: str = Field(..., description="Step title")
    description: str = Field(..., description="Detailed description of what this step does")
    node_types: List[str] = Field(default_factory=list, description="Node types used in this step")


class ImplementationPlan(BaseModel):
    """Implementation plan generated by the planner"""
    summary: str = Field(..., description="Brief overview of what the workflow will accomplish")
    steps: List[PlanStep] = Field(..., description="Step-by-step breakdown")
    estimated_nodes: List[str] = Field(default_factory=list, description="Estimated node types needed")
    complexity: str = Field("medium", description="Estimated complexity: simple, medium, complex")


# ============================================================
# Planner Agent Output
# ============================================================

class PlannerOutput(BaseModel):
    """Structured output from the planner agent"""
    action: PlannerAction = Field(..., description="The action to take")
    questions: Optional[List[ClarificationQuestion]] = Field(
        None, description="Clarification questions (when action is ask_clarification)"
    )
    plan: Optional[ImplementationPlan] = Field(
        None, description="Implementation plan (when action is generate_plan)"
    )
    context_request: Optional[Dict[str, Any]] = Field(
        None, description="Context request info (when action is gather_context)"
    )
    message: Optional[str] = Field(
        None, description="Optional message to display to user"
    )


# ============================================================
# Flowgram Schemas
# ============================================================

class NodePosition(BaseModel):
    """Position of a node on the canvas"""
    x: float = Field(..., description="X coordinate")
    y: float = Field(..., description="Y coordinate")


class FlowgramNode(BaseModel):
    """A node in the flowgram"""
    id: str = Field(..., description="Unique node identifier")
    type: str = Field(..., description="Node type (e.g., 'llm', 'mcp_tool', 'condition')")
    label: str = Field(..., description="Display label")
    position: NodePosition = Field(..., description="Canvas position")
    config: Dict[str, Any] = Field(default_factory=dict, description="Node configuration")


class FlowgramEdge(BaseModel):
    """An edge connecting two nodes"""
    source: str = Field(..., description="Source node ID")
    target: str = Field(..., description="Target node ID")
    source_handle: Optional[str] = Field(None, description="Source handle ID")
    target_handle: Optional[str] = Field(None, description="Target handle ID")
    label: Optional[str] = Field(None, description="Edge label")


class Flowgram(BaseModel):
    """Complete flowgram structure"""
    nodes: List[FlowgramNode] = Field(default_factory=list, description="List of nodes")
    edges: List[FlowgramEdge] = Field(default_factory=list, description="List of edges")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


# ============================================================
# Code Agent Output
# ============================================================

class ValidationError(BaseModel):
    """A validation error in the flowgram"""
    node_id: Optional[str] = Field(None, description="Node ID with the error")
    field: Optional[str] = Field(None, description="Field with the error")
    message: str = Field(..., description="Error message")
    severity: str = Field("error", description="Severity: error, warning, info")


class ValidationResult(BaseModel):
    """Result of flowgram validation"""
    valid: bool = Field(..., description="Whether the flowgram is valid")
    errors: List[ValidationError] = Field(default_factory=list, description="Validation errors")
    warnings: List[ValidationError] = Field(default_factory=list, description="Validation warnings")


class CodeAgentOutput(BaseModel):
    """Structured output from the code agent"""
    action: CodeAgentAction = Field(..., description="The action taken")
    message: str = Field(..., description="Message to display to user")
    flowgram: Optional[Flowgram] = Field(
        None, description="Generated or edited flowgram"
    )
    validation: Optional[ValidationResult] = Field(
        None, description="Validation result"
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


# ============================================================
# Canvas Commands
# ============================================================

class CanvasCommand(BaseModel):
    """A command to be sent to the frontend canvas"""
    type: str = Field(..., description="Command type (e.g., 'canvas.add_node')")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Command payload")
    
    def to_dict(self) -> Dict[str, Any]:
        return {"type": self.type, "payload": self.payload}


# ============================================================
# Agent Response
# ============================================================

class AgentResponse(BaseModel):
    """Unified response from the skill editor agent"""
    message: str = Field(..., description="Response message to display")
    commands: List[CanvasCommand] = Field(default_factory=list, description="Canvas commands")
    intent: IntentType = Field(IntentType.GENERAL_CHAT, description="Classified intent")
    
    # Planning phase data
    clarification: Optional[List[ClarificationQuestion]] = Field(
        None, description="Clarification questions if needed"
    )
    plan: Optional[ImplementationPlan] = Field(
        None, description="Implementation plan if generated"
    )
    
    # Code generation data
    flowgram: Optional[Flowgram] = Field(
        None, description="Generated flowgram"
    )
    validation: Optional[ValidationResult] = Field(
        None, description="Validation result"
    )
    
    # Metadata
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    
    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(exclude_none=True)


# ============================================================
# Streaming Events
# ============================================================

class StreamEventType(str, Enum):
    """Types of streaming events"""
    CHUNK = "chunk"
    CLARIFICATION = "clarification"
    PLAN = "plan"
    PROGRESS = "progress"
    FLOWGRAM = "flowgram"
    VALIDATION = "validation"
    CANVAS_COMMAND = "canvas_command"
    COMPLETE = "complete"
    ERROR = "error"


class StreamEvent(BaseModel):
    """A streaming event sent to the frontend"""
    type: StreamEventType = Field(..., description="Event type")
    data: Dict[str, Any] = Field(default_factory=dict, description="Event data")
    
    def to_dict(self) -> Dict[str, Any]:
        return {"type": self.type.value, "data": self.data}


# ============================================================
# Node Type Definitions
# ============================================================

NODE_TYPES = {
    "start": {
        "description": "Entry point of the workflow",
        "has_inputs": False,
        "has_outputs": True,
    },
    "end": {
        "description": "Exit point of the workflow",
        "has_inputs": True,
        "has_outputs": False,
    },
    "llm": {
        "description": "LLM node for AI processing with prompts",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "model": "string",
            "system_prompt": "string",
            "user_prompt": "string",
            "temperature": "number",
        }
    },
    "mcp_tool": {
        "description": "MCP tool node for external tool calls",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "tool_name": "string",
            "tool_input": "object",
        }
    },
    "condition": {
        "description": "Conditional branching node",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "condition": "string",
            "true_branch": "string",
            "false_branch": "string",
        }
    },
    "loop": {
        "description": "Loop node for iterative processing",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "max_iterations": "number",
            "condition": "string",
        }
    },
    "code": {
        "description": "Custom code execution node",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "language": "string",
            "code": "string",
        }
    },
    "http": {
        "description": "HTTP request node for API calls",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "url": "string",
            "method": "string",
            "headers": "object",
            "body": "object",
        }
    },
    "browser_automation": {
        "description": "Browser automation node using browser-use agent for web interactions, this sub-agent can run {max_steps} steps to read anyu url page, understand it and then interact with it, including clicking, typing, scrolling, etc. The input will a text prompt describing what to do with with the browser.",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "provider": "string",  # 'browser-use' | 'browsebase' | 'crawl4ai'
            "task": "string",  # High-level instruction text for the agent
            "browser": "string",  # Browser type (e.g., 'new chromium')
            "browserDriver": "string",  # Driver type ('native', 'selenium', etc.)
            "cdpPort": "string",  # CDP port for browser connection
            "modelProvider": "string",  # LLM provider for browser-use agent
            "modelName": "string",  # LLM model name
            "useThinking": "boolean",  # Enable thinking mode for browser-use
            "profile": "string",  # Browser profile name
            "promptSelection": "string",  # 'inline' or 'saved'
            "systemPrompt": "string",  # System prompt for the agent
            "prompt": "string",  # User prompt/task instruction
            "timeout_seconds": "number",  # Max time for browser automation
            "enable_guardrail_timer": "boolean",  # Enable timeout tracking
            "wait_for_done": "boolean",  # Whether to interrupt when external completion is needed
        }
    },
    "pend_event": {
        "description": "Interrupt node that pauses workflow and waits for external event or human input",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "prompt": "string",  # Message to present to human/agent
            "tag": "string",  # Business tag for the interrupt (defaults to node_name)
            "eventType": "string",  # Main event type to wait for
            "pendingSources": "array",  # Additional event sources to listen for
        }
    },
    "chat_node": {
        "description": "Chat node that sends messages to the user via TaskRunner GUI",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "role": "string",  # Message role ('assistant', 'user', 'system')
            "message": "string",  # Message template to send
            "wait_for_reply": "boolean",  # Whether to wait for user reply
        }
    },
    "rag": {
        "description": "RAG (Retrieval Augmented Generation) node for knowledge retrieval",
        "has_inputs": True,
        "has_outputs": True,
        "config_schema": {
            "query_path": "string",  # Dotted path to extract query from state
        }
    },
}


def get_node_types_description() -> str:
    """Format node types for prompts"""
    lines = []
    for name, info in NODE_TYPES.items():
        lines.append(f"- **{name}**: {info['description']}")
    return "\n".join(lines)
