"""
Validator Agent

Specialized agent for validating and fixing JSON/flowgram output from CodeAgent.
When CodeAgent produces malformed JSON or invalid flowgram structure, this agent
uses an LLM to understand the error and fix it.

This follows the same pattern as PlannerAgent and CodeAgent in the multi-agent architecture.
"""

import json
import re
from typing import Any, Dict, List, Optional, Callable
from enum import Enum

from utils.logger_helper import logger_helper as logger


class ValidatorAction(str, Enum):
    """Actions the validator agent can take"""
    FIXED = "fixed"  # Successfully fixed the JSON/flowgram
    UNFIXABLE = "unfixable"  # Cannot fix - need to regenerate
    VALID = "valid"  # Input was already valid
    TRUNCATED = "truncated"  # Output was truncated, need continuation


class ValidatorOutput:
    """Output from the validator agent"""
    def __init__(
        self,
        action: ValidatorAction,
        message: str,
        fixed_json: Optional[Dict[str, Any]] = None,
        original_error: Optional[str] = None,
        truncated_content: Optional[str] = None,  # Partial content if truncated
    ):
        self.action = action
        self.message = message
        self.fixed_json = fixed_json
        self.original_error = original_error
        self.truncated_content = truncated_content


VALIDATOR_SYSTEM_PROMPT = """You are a JSON Validator and Repair Agent.

Your job is to fix malformed JSON that was generated by another AI agent.

MULTI-SHEET SYNC (CRITICAL):
- Every skill has two files: `<name>_skill.json` (current sheet) AND `<name>_skill_bundle.json` (all sheets).
- After fixing, ensure the `workFlow` for the current sheet can be mirrored into the bundle’s main sheet (`mainSheetId`/`activeSheetId` = "main") so nodes/edges stay identical.
- Assume the caller will persist BOTH files; never leave the bundle out of sync with the sheet file.

## COMMON JSON ERRORS TO FIX:
1. **Trailing commas**: Remove commas before ] or }
2. **Missing commas**: Add commas between array elements or object properties
3. **Unclosed brackets**: Close any unclosed { } [ ]
4. **Truncated content**: If JSON is cut off, complete the structure logically
5. **Invalid escape sequences**: Fix backslash issues in strings
6. **Unquoted keys**: Add quotes around object keys
7. **Single quotes**: Replace single quotes with double quotes

## OUTPUT FORMAT:
You MUST respond with ONLY valid JSON. No explanations, no markdown, just the fixed JSON.

If the JSON is completely unrecoverable (e.g., mostly garbage), respond with:
{"error": "unfixable", "reason": "brief explanation"}

## IMPORTANT:
- Preserve ALL data from the original JSON
- Only fix syntax errors, don't change the content/meaning
- The JSON should contain a "flowgram" object with "nodes" and "edges" arrays
- Each node needs: id, type, label, position, config
- Each edge needs: source, target (and optionally source_handle, target_handle)
"""


class ValidatorAgent:
    """
    Agent for validating and fixing JSON/flowgram output.
    
    Responsibilities:
    - Detect JSON syntax errors
    - Use LLM to fix malformed JSON
    - Validate flowgram structure
    - Report unfixable errors
    """
    
    MAX_FIX_ATTEMPTS = 2
    
    def __init__(self, llm=None):
        """
        Initialize the ValidatorAgent.
        
        Args:
            llm: LangChain LLM instance for JSON repair
        """
        self.llm = llm
        logger.info("[ValidatorAgent] Initialized")
    
    def set_llm(self, llm):
        """Set the LLM instance"""
        self.llm = llm
        logger.debug("[ValidatorAgent] LLM instance set")
    
    def _get_llm(self):
        """Get or create LLM instance"""
        if self.llm:
            return self.llm
        
        try:
            import importlib
            settings_mod = importlib.import_module("config.llm_settings")
            LLMSettings = getattr(settings_mod, "LLMSettings", None)
            if not LLMSettings:
                raise ImportError("config.llm_settings.LLMSettings not found")
            settings = LLMSettings()
            self.llm = settings.get_chat_model()
            logger.info("[ValidatorAgent] Loaded LLM from settings")
            return self.llm
        except Exception as e:
            logger.error(f"[ValidatorAgent] Failed to load LLM: {e}")
            try:
                from langchain_openai import ChatOpenAI
                import os
                api_key = os.environ.get("OPENAI_API_KEY")
                if api_key:
                    self.llm = ChatOpenAI(model="gpt-4o", api_key=api_key, max_tokens=4096)
                    logger.info("[ValidatorAgent] Using fallback OpenAI LLM")
                    return self.llm
            except Exception:
                pass
            return None
    
    def try_parse_json(self, json_str: str) -> tuple[Optional[Dict], Optional[str]]:
        """
        Try to parse JSON string, return (parsed_dict, error_message).
        If successful, error_message is None.
        """
        try:
            return json.loads(json_str), None
        except json.JSONDecodeError as e:
            return None, str(e)
    
    def quick_fix_json(self, json_str: str) -> Optional[Dict]:
        """
        Apply quick programmatic fixes for common JSON errors.
        Returns parsed dict if successful, None otherwise.
        """
        # Fix 1: Remove trailing commas before ] or }
        fixed = re.sub(r',(\s*[}\]])', r'\1', json_str)
        result, _ = self.try_parse_json(fixed)
        if result:
            return result
        
        # Fix 2: Try to close unclosed brackets
        open_braces = fixed.count('{') - fixed.count('}')
        open_brackets = fixed.count('[') - fixed.count(']')
        
        if open_braces > 0 or open_brackets > 0:
            closing = ']' * open_brackets + '}' * open_braces
            result, _ = self.try_parse_json(fixed + closing)
            if result:
                return result
        
        # Fix 3: Replace single quotes with double quotes (risky but sometimes works)
        # Only do this if there are no double quotes in the string
        if '"' not in json_str and "'" in json_str:
            single_to_double = json_str.replace("'", '"')
            result, _ = self.try_parse_json(single_to_double)
            if result:
                return result
        
        return None
    
    async def validate_and_fix(
        self,
        raw_response: str,
        on_event: Optional[Callable] = None
    ) -> ValidatorOutput:
        """
        Validate and fix JSON from CodeAgent response.
        
        Args:
            raw_response: Raw string response from CodeAgent (may contain markdown, etc.)
            on_event: Optional callback for streaming events
            
        Returns:
            ValidatorOutput with fixed JSON or error
        """
        logger.info(f"[ValidatorAgent] Validating response (length: {len(raw_response)})")
        
        # Step 0: Check for truncation indicators
        is_truncated = self._detect_truncation(raw_response)
        if is_truncated:
            logger.warning("[ValidatorAgent] Detected truncated output - JSON was cut off mid-generation")
        
        # Step 1: Extract JSON from response (may be in markdown code block)
        json_str = self._extract_json_string(raw_response)
        if not json_str:
            logger.warning("[ValidatorAgent] No JSON-like content found in response")
            return ValidatorOutput(
                action=ValidatorAction.UNFIXABLE,
                message="No JSON content found in the response",
                original_error="No JSON-like structure detected"
            )
        
        # Step 2: Try direct parse
        result, error = self.try_parse_json(json_str)
        if result:
            logger.info("[ValidatorAgent] JSON is already valid")
            # Step 2.5: Fix disconnected nodes if this is a flowgram
            result = self.fix_disconnected_nodes(result)
            return ValidatorOutput(
                action=ValidatorAction.VALID,
                message="JSON is valid",
                fixed_json=result
            )
        
        logger.info(f"[ValidatorAgent] JSON parse error: {error}")
        
        # If truncated and can't parse, return TRUNCATED action for continuation
        if is_truncated:
            logger.info("[ValidatorAgent] Returning TRUNCATED for continuation request")
            return ValidatorOutput(
                action=ValidatorAction.TRUNCATED,
                message="JSON output was truncated mid-generation. Need to continue generation.",
                original_error=error,
                truncated_content=json_str
            )
        
        # Step 3: Try quick programmatic fixes
        quick_fixed = self.quick_fix_json(json_str)
        if quick_fixed:
            logger.info("[ValidatorAgent] Fixed JSON with quick fixes")
            # Fix disconnected nodes if this is a flowgram
            quick_fixed = self.fix_disconnected_nodes(quick_fixed)
            return ValidatorOutput(
                action=ValidatorAction.FIXED,
                message="Fixed JSON syntax errors (trailing commas, unclosed brackets)",
                fixed_json=quick_fixed,
                original_error=error
            )
        
        # Step 4: Use LLM to fix the JSON
        llm = self._get_llm()
        if not llm:
            logger.warning("[ValidatorAgent] No LLM available for repair")
            return ValidatorOutput(
                action=ValidatorAction.UNFIXABLE,
                message="JSON is malformed and no LLM available for repair",
                original_error=error
            )
        
        # Try LLM repair
        for attempt in range(self.MAX_FIX_ATTEMPTS):
            logger.info(f"[ValidatorAgent] LLM repair attempt {attempt + 1}/{self.MAX_FIX_ATTEMPTS}")
            
            repair_prompt = f"""Fix this malformed JSON. The error was: {error}

MALFORMED JSON:
```
{json_str[:8000]}  
```
{"... (truncated)" if len(json_str) > 8000 else ""}

Return ONLY the fixed JSON, no explanations."""
            
            try:
                from langchain_core.messages import SystemMessage, HumanMessage
                
                messages = [
                    SystemMessage(content=VALIDATOR_SYSTEM_PROMPT),
                    HumanMessage(content=repair_prompt)
                ]
                
                response = await llm.ainvoke(messages)
                response_text = response.content if hasattr(response, 'content') else str(response)
                
                # Extract JSON from LLM response
                fixed_json_str = self._extract_json_string(response_text)
                if fixed_json_str:
                    result, new_error = self.try_parse_json(fixed_json_str)
                    if result:
                        # Check if LLM returned an error response
                        if result.get("error") == "unfixable":
                            logger.warning(f"[ValidatorAgent] LLM says unfixable: {result.get('reason')}")
                            return ValidatorOutput(
                                action=ValidatorAction.UNFIXABLE,
                                message=f"JSON cannot be repaired: {result.get('reason', 'unknown')}",
                                original_error=error
                            )
                        
                        logger.info("[ValidatorAgent] LLM successfully fixed JSON")
                        # Fix disconnected nodes if this is a flowgram
                        result = self.fix_disconnected_nodes(result)
                        return ValidatorOutput(
                            action=ValidatorAction.FIXED,
                            message=f"Fixed JSON using LLM (attempt {attempt + 1})",
                            fixed_json=result,
                            original_error=error
                        )
                    else:
                        error = new_error  # Update error for next attempt
                        
            except Exception as e:
                logger.warning(f"[ValidatorAgent] LLM repair failed: {e}")
        
        # All attempts failed
        logger.error("[ValidatorAgent] All repair attempts failed")
        return ValidatorOutput(
            action=ValidatorAction.UNFIXABLE,
            message="Failed to repair JSON after multiple attempts",
            original_error=error
        )
    
    def _detect_truncation(self, text: str) -> bool:
        """
        Detect if the LLM output was truncated mid-generation.
        
        Signs of truncation:
        1. JSON ends mid-string (unclosed quote)
        2. JSON ends mid-object (unclosed braces)
        3. Response ends with incomplete JSON structure
        4. Response ends abruptly without proper closing
        """
        if not text:
            return False
        
        # Check if text ends abruptly (common truncation patterns)
        text_stripped = text.rstrip()
        
        # Pattern 1: Ends mid-string (inside quotes)
        if text_stripped.endswith('"') or text_stripped.endswith("'"):
            # Check if this is an unclosed string
            quote_count = text_stripped.count('"')
            if quote_count % 2 != 0:
                return True
        
        # Pattern 2: Ends with incomplete JSON structure indicators
        truncation_endings = [
            '{{',  # Template variable start
            '":', # Key without value
            '": ', # Key with space but no value
            '",', # Might be mid-array
            '[', # Unclosed array
            '{', # Unclosed object
            '\\', # Escape character
        ]
        for ending in truncation_endings:
            if text_stripped.endswith(ending):
                return True
        
        # Pattern 3: Count brackets - significant imbalance suggests truncation
        open_braces = text.count('{')
        close_braces = text.count('}')
        open_brackets = text.count('[')
        close_brackets = text.count(']')
        
        # If many more opens than closes, likely truncated
        brace_diff = open_braces - close_braces
        bracket_diff = open_brackets - close_brackets
        
        if brace_diff > 3 or bracket_diff > 3:
            return True
        
        # Pattern 4: Check if response ends mid-word or mid-key
        # Look for incomplete key-value patterns
        if re.search(r'"[a-zA-Z_][a-zA-Z0-9_]*$', text_stripped):
            return True  # Ends with incomplete key
        
        return False
    
    def _extract_json_string(self, text: str) -> Optional[str]:
        """Extract JSON string from text that may contain markdown or other content"""
        # Try markdown code block first
        json_match = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', text)
        if json_match:
            return json_match.group(1).strip()
        
        # Find first { and try to extract JSON object
        first_brace = text.find('{')
        if first_brace >= 0:
            # Find the matching closing brace by counting
            depth = 0
            in_string = False
            escape_next = False
            
            for i, char in enumerate(text[first_brace:], start=first_brace):
                if escape_next:
                    escape_next = False
                    continue
                if char == '\\':
                    escape_next = True
                    continue
                if char == '"' and not escape_next:
                    in_string = not in_string
                    continue
                if in_string:
                    continue
                if char == '{':
                    depth += 1
                elif char == '}':
                    depth -= 1
                    if depth == 0:
                        return text[first_brace:i+1]
            
            # If we didn't find matching brace, return everything from first brace
            return text[first_brace:]
        
        return None
    
    def validate_flowgram_structure(self, data: Dict) -> tuple[bool, List[str]]:
        """
        Validate that the parsed JSON has valid flowgram structure.
        Returns (is_valid, list_of_errors).
        """
        errors = []
        
        # Check for flowgram wrapper or direct nodes/edges (handle flowgram, workFlow, or direct)
        flowgram = data.get("flowgram") or data.get("workFlow") or data
        
        # Check nodes
        nodes = flowgram.get("nodes", [])
        if not nodes:
            errors.append("No nodes found in flowgram")
        else:
            for i, node in enumerate(nodes):
                if not node.get("id"):
                    errors.append(f"Node {i} missing 'id'")
                if not node.get("type"):
                    errors.append(f"Node {i} missing 'type'")
        
        # Check edges
        edges = flowgram.get("edges", [])
        node_ids = {n.get("id") for n in nodes if n.get("id")}
        
                # Check edges reference valid nodes and handles
        for i, edge in enumerate(edges):
            source = edge.get("source") or edge.get("sourceNodeID")
            target = edge.get("target") or edge.get("targetNodeID")
            if not source:
                errors.append(f"Edge {i} missing 'source'")
            elif source not in node_ids:
                errors.append(f"Edge {i} source '{source}' not found in nodes")
            if not target:
                errors.append(f"Edge {i} missing 'target'")
            elif target not in node_ids:
                errors.append(f"Edge {i} target '{target}' not found in nodes")
            if source and source.startswith("condition"):
                handle = edge.get("sourcePortID") or edge.get("source_handle") or edge.get("sourceHandle")
                if handle is None:
                    errors.append(f"Edge {i} from condition '{source}' missing source handle (branch key)")        # Required configs per node type (UI shape: data.inputsValues/script)

        for node in nodes:
            ntype = node.get("type") or ""
            data = node.get("data") or {}
            inputs_values = data.get("inputsValues") or {}
            if ntype == "llm":
                prompt_sel = (inputs_values.get("promptSelection") or {}).get("content")
                sys_p = (inputs_values.get("systemPrompt") or {}).get("content")
                usr_p = (inputs_values.get("prompt") or {}).get("content")
                model_name = (inputs_values.get("modelName") or {}).get("content")
                model_provider = (inputs_values.get("modelProvider") or {}).get("content")
                api_host = (inputs_values.get("apiHost") or {}).get("content")
                temperature = (inputs_values.get("temperature") or {}).get("content")
                if not prompt_sel:
                    errors.append(f"LLM node '{node.get('id')}' missing promptSelection (prompt pool ID or inline)")
                if (prompt_sel in [None, "", "inline"]) and not sys_p and not usr_p:
                    errors.append(f"LLM node '{node.get('id')}' has inline promptSelection but empty prompts")
                if not model_name:
                    errors.append(f"LLM node '{node.get('id')}' missing modelName")
                if not model_provider:
                    errors.append(f"LLM node '{node.get('id')}' missing modelProvider")
                if api_host in [None, ""]:
                    errors.append(f"LLM node '{node.get('id')}' missing apiHost")
                if temperature is None:
                    errors.append(f"LLM node '{node.get('id')}' missing temperature")
            if ntype in ["browser-automation", "browser_automation"]:
                prompt_sel = (inputs_values.get("promptSelection") or {}).get("content")
                sys_p = (inputs_values.get("systemPrompt") or {}).get("content")
                usr_p = (inputs_values.get("prompt") or {}).get("content")
                model_name = (inputs_values.get("modelName") or {}).get("content")
                model_provider = (inputs_values.get("modelProvider") or {}).get("content")
                browser = (inputs_values.get("browser") or {}).get("content")
                browser_driver = (inputs_values.get("browserDriver") or {}).get("content")
                temperature = (inputs_values.get("temperature") or {}).get("content")
                if not prompt_sel:
                    errors.append(f"browser_automation node '{node.get('id')}' missing promptSelection (prompt pool ID or inline)")
                if (prompt_sel in [None, "", "inline"]) and not sys_p and not usr_p:
                    errors.append(f"browser_automation node '{node.get('id')}' has inline promptSelection but empty prompts")
                if not model_name:
                    errors.append(f"browser_automation node '{node.get('id')}' missing modelName")
                if not model_provider:
                    errors.append(f"browser_automation node '{node.get('id')}' missing modelProvider")
                if browser in [None, ""]:
                    errors.append(f"browser_automation node '{node.get('id')}' missing browser")
                if browser_driver in [None, ""]:
                    errors.append(f"browser_automation node '{node.get('id')}' missing browserDriver")
                if temperature is None:
                    errors.append(f"browser_automation node '{node.get('id')}' missing temperature")
            if ntype == "code":
                script = data.get("script") or {}
                code_content = script.get("content")
                if not code_content:
                    errors.append(f"Code node '{node.get('id')}' missing code/script content")

        # Check for disconnected nodes (except start/end)
        disconnected = self._find_disconnected_nodes(nodes, edges)
        for node_id in disconnected:
            errors.append(f"Node '{node_id}' is disconnected (no incoming or outgoing edges)")
        
        return len(errors) == 0, errors
    
    def _find_disconnected_nodes(self, nodes: List[Dict], edges: List[Dict], start_type: str = "start", end_type: str = "end") -> List[str]:
        """Find nodes that are missing incoming or outgoing edges (partially or fully disconnected)"""
        disconnected = []
        
        # Build sets of nodes with edges and count outgoing edges per node
        nodes_with_incoming = set()
        outgoing_count = {}  # node_id -> count of outgoing edges
        outgoing_handles = {}  # node_id -> set of source handles used
        
        for edge in edges:
            source = edge.get("source") or edge.get("sourceNodeID")
            target = edge.get("target") or edge.get("targetNodeID")
            source_handle = edge.get("sourcePortID") or edge.get("source_handle") or edge.get("sourceHandle")
            if source:
                outgoing_count[source] = outgoing_count.get(source, 0) + 1
                if source not in outgoing_handles:
                    outgoing_handles[source] = set()
                if source_handle:
                    outgoing_handles[source].add(source_handle)
            if target:
                nodes_with_incoming.add(target)
        
        for node in nodes:
            node_id = node.get("id")
            node_type = node.get("type", "")
            
            # Skip start/end nodes (or block-start/block-end for loops)
            if node_type in (start_type, end_type):
                continue
            
            has_incoming = node_id in nodes_with_incoming
            has_outgoing = outgoing_count.get(node_id, 0) > 0
            
            # For condition nodes, check if ALL branches have outgoing edges
            if node_type == "condition":
                conditions = node.get("data", {}).get("conditions", [])
                if conditions:
                    required_handles = {c.get("key") for c in conditions if c.get("key")}
                    used_handles = outgoing_handles.get(node_id, set())
                    missing_handles = required_handles - used_handles
                    # Condition is disconnected if missing incoming OR missing any branch edges
                    if not has_incoming or missing_handles:
                        disconnected.append(node_id)
                        if missing_handles:
                            logger.debug(f"[ValidatorAgent] Condition node '{node_id}' missing edges for branches: {missing_handles}")
                        if not has_incoming:
                            logger.debug(f"[ValidatorAgent] Condition node '{node_id}' missing incoming edge")
                        continue
            
            # A node is disconnected if it's missing EITHER incoming OR outgoing edges
            if not has_incoming or not has_outgoing:
                disconnected.append(node_id)
        
        return disconnected
    
    def _normalize_condition_keys(self, cond_node: Dict) -> List[Dict]:
        """
        Normalize condition keys to stable if/elseif/else naming so branch handles stay consistent.
        - First branch -> if_branch
        - Middle branches -> elseif_<index>
        - Last branch -> else_branch
        """
        data = cond_node.get("data", {}) or {}
        conditions = data.get("conditions") or []
        if not conditions:
            conditions = [{"key": "if_branch", "value": {}}, {"key": "else_branch", "value": {}}]
        else:
            n = len(conditions)
            for idx, c in enumerate(conditions):
                if idx == 0:
                    c["key"] = "if_branch"
                elif idx == n - 1:
                    c["key"] = "else_branch"
                else:
                    c["key"] = f"elseif_{idx}"
        # Persist normalized keys into both data and config for consistency
        data["conditions"] = conditions
        cond_node["data"] = data
        cond_node.setdefault("config", {})["conditions"] = conditions
        return conditions
    
    def fix_disconnected_nodes(self, data: Dict, task_context: Optional[str] = None) -> Dict:
        """
        Attempt to fix disconnected nodes by adding edges based on logical task sequence.
        This is a best-effort fix for common LLM mistakes.
        Also processes internal blocks/edges of loop nodes.
        
        Args:
            data: The flowgram data to fix
            task_context: The original user request/task description for logical sequencing
        """
        # Store task context for use in _fix_disconnected_in_scope
        self._task_context = task_context
        if task_context:
            logger.info(f"[ValidatorAgent] Fixing disconnected nodes with task context: {task_context[:100]}...")
        # Handle different flowgram structures: flowgram, workFlow, or direct nodes
        flowgram = data.get("flowgram") or data.get("workFlow") or data
        nodes = flowgram.get("nodes", [])
        edges = flowgram.get("edges")
        if edges is None:
            edges = []
            flowgram["edges"] = edges
        # Normalize edge dicts (drop null-valued fields)
        self._normalize_edges(edges)
        
        if not nodes:
            return data
        
        # Fix top-level disconnected nodes
        # Always run, even if edges is empty (will create needed edges)
        self._fix_disconnected_in_scope(nodes, edges)
        # Ensure mutated edges are persisted on the flowgram object
        flowgram["edges"] = edges
        
        # Fix disconnected nodes inside loop nodes
        for node in nodes:
            if node.get("type") == "loop":
                # Loop nodes can have blocks and edges at top level or in data
                blocks = node.get("blocks", []) or node.get("data", {}).get("blocks", [])
                internal_edges = (
                    node.get("edges", [])
                    or node.get("internal_edges", [])
                    or node.get("data", {}).get("edges", [])
                    or node.get("data", {}).get("internal_edges", [])
                )
                # Normalize loop edge dicts
                self._normalize_edges(internal_edges)
                
                # If loop has blocks but NO edges, we need to create edges from scratch
                if blocks and not internal_edges:
                    loop_id = node.get("id", "loop")
                    logger.info(f"[ValidatorAgent] Loop node '{loop_id}' has {len(blocks)} blocks but NO edges - creating edges")
                    internal_edges = []
                    # Store the new edges list in the node
                    node["edges"] = internal_edges
                
                if blocks:
                    loop_id = node.get("id", "loop")
                    logger.info(f"[ValidatorAgent] Checking loop node '{loop_id}' with {len(blocks)} blocks and {len(internal_edges)} edges")
                    new_edges = self._fix_disconnected_in_scope(blocks, internal_edges, is_loop=True, task_context=task_context)
                    
                    # Update the edges in the loop node
                    if node.get("edges") is not None:
                        node["edges"] = internal_edges
                    elif node.get("internal_edges") is not None:
                        node["internal_edges"] = internal_edges
                    elif node.get("data", {}).get("edges") is not None:
                        node["data"]["edges"] = internal_edges
                    elif node.get("data", {}).get("internal_edges") is not None:
                        node["data"]["internal_edges"] = internal_edges
                    else:
                        # Store in the most common location
                        node["internal_edges"] = internal_edges
        
        return data

    def _normalize_edges(self, edges: List[Dict]) -> None:
        """Remove null-valued fields from edges to avoid frontend mis-rendering."""
        for e in edges:
            to_delete = [k for k, v in e.items() if v is None]
            for k in to_delete:
                del e[k]

    def _normalize_condition_handles(
        self,
        cond_id: str,
        conditions: List[Dict],
        edges: List[Dict],
    ) -> None:
        """
        Ensure outgoing edges from a condition node use handles that match the condition keys.
        If an edge uses a non-existent handle, remap it to an available condition key
        (first available, then fallback to the first key).
        """
        if not conditions:
            return
        required_handles = [c.get("key") for c in conditions if c.get("key")]
        if not required_handles:
            return

        # Track which handles are already correctly used
        used = set()
        needing_remap = []
        for e in edges:
            source = e.get("sourceNodeID") or e.get("source")
            if source != cond_id:
                continue
            handle = e.get("sourcePortID") or e.get("source_handle") or e.get("sourceHandle")
            if handle in required_handles and handle not in used:
                used.add(handle)
            else:
                needing_remap.append(e)

        available = [h for h in required_handles if h not in used]
        for e in needing_remap:
            new_handle = None
            if available:
                new_handle = available.pop(0)
                used.add(new_handle)
            elif required_handles:
                new_handle = required_handles[0]
            if new_handle:
                e["sourcePortID"] = new_handle
            else:
                # No handle available; leave edge as-is but ensure no nulls
                if "sourcePortID" in e and e["sourcePortID"] is None:
                    del e["sourcePortID"]
    
    def _fix_disconnected_in_scope(self, nodes: List[Dict], edges: List[Dict], is_loop: bool = False, task_context: Optional[str] = None) -> List[Dict]:
        """
        Fix disconnected nodes within a scope (top-level or inside a loop).
        Uses sequential connection based on node order in the array.
        Handles condition nodes specially - connects ALL branches.
        Returns list of new edges added.
        """
        if not nodes:
            return []
        
        start_type = "block-start" if is_loop else "start"
        end_type = "block-end" if is_loop else "end"
        scope_name = "loop" if is_loop else "flowgram"
        
        # Build node lookup and index mapping
        node_by_id = {n.get("id"): n for n in nodes}
        node_index = {n.get("id"): i for i, n in enumerate(nodes)}
        
        # Build edge sets for quick lookup
        nodes_with_outgoing = set()
        nodes_with_incoming = set()
        # Track edge uniqueness by (source, target, handle) so condition branches to same target are allowed
        edge_pairs = set()
        outgoing_handles = {}  # node_id -> set of source handles used
        
        for edge in edges:
            source = edge.get("source") or edge.get("sourceNodeID")
            target = edge.get("target") or edge.get("targetNodeID")
            source_handle = edge.get("sourcePortID") or edge.get("source_handle") or edge.get("sourceHandle")
            if source:
                nodes_with_outgoing.add(source)
                if source not in outgoing_handles:
                    outgoing_handles[source] = set()
                if source_handle:
                    outgoing_handles[source].add(source_handle)
            if target:
                nodes_with_incoming.add(target)
            if source and target:
                edge_pairs.add((source, target, source_handle or ""))
        
        # Find start, end, and content nodes
        start_node = None
        end_node = None
        content_nodes = []
        condition_nodes = []
        
        for node in nodes:
            node_type = node.get("type", "")
            if node_type == start_type:
                start_node = node
            elif node_type == end_type:
                end_node = node
            elif node_type == "condition":
                content_nodes.append(node)
                condition_nodes.append(node)
            else:
                content_nodes.append(node)
        
        new_edges = []
        
        # Build the expected chain: start -> content_nodes[0] -> ... -> end
        chain = []
        if start_node:
            chain.append(start_node)
        chain.extend(content_nodes)
        if end_node:
            chain.append(end_node)
        
        # Helper to add an edge
        def add_edge(source_id: str, target_id: str, source_handle: Optional[str] = None):
            key = (source_id, target_id, source_handle or "")
            if key in edge_pairs:
                return False
            edge = {"sourceNodeID": source_id, "targetNodeID": target_id}
            if source_handle:
                edge["sourcePortID"] = source_handle
                logger.info(f"[ValidatorAgent] Added condition edge: {source_id} ({source_handle}) -> {target_id}")
            else:
                logger.info(f"[ValidatorAgent] Added edge: {source_id} -> {target_id}")
            # Persist the edge into the working list so it is saved back to the flowgram
            edges.append(edge)
            new_edges.append(edge)
            edge_pairs.add(key)
            nodes_with_outgoing.add(source_id)
            nodes_with_incoming.add(target_id)
            if source_id not in outgoing_handles:
                outgoing_handles[source_id] = set()
            if source_handle:
                outgoing_handles[source_id].add(source_handle)
            return True

        def _dedupe_condition_outgoing_edges(cond_id: str) -> None:
            def edge_source(e: Dict) -> Optional[str]:
                return e.get("sourceNodeID") or e.get("source")

            def edge_target(e: Dict) -> Optional[str]:
                return e.get("targetNodeID") or e.get("target")

            def edge_handle(e: Dict) -> Optional[str]:
                return e.get("sourcePortID") or e.get("source_handle") or e.get("sourceHandle")

            outgoing = []
            for e in edges:
                if edge_source(e) == cond_id:
                    h = edge_handle(e)
                    if h:
                        outgoing.append(e)

            by_handle: Dict[str, List[Dict]] = {}
            for e in outgoing:
                by_handle.setdefault(edge_handle(e) or "", []).append(e)

            to_remove_ids = set()

            def target_score(tgt_id: Optional[str]) -> int:
                if not tgt_id:
                    return -1
                tgt_node = node_by_id.get(tgt_id)
                tgt_type = (tgt_node or {}).get("type", "")
                return 0 if tgt_type == end_type else 1

            for handle, items in by_handle.items():
                if not handle or len(items) <= 1:
                    continue

                # Pick the best edge to keep
                best = None
                best_score = -1
                for e in items:
                    sc = target_score(edge_target(e))
                    if sc > best_score:
                        best = e
                        best_score = sc

                for e in items:
                    if e is not best:
                        to_remove_ids.add(id(e))

            if to_remove_ids:
                edges[:] = [e for e in edges if id(e) not in to_remove_ids]
                edge_pairs.clear()
                nodes_with_outgoing.clear()
                nodes_with_incoming.clear()
                outgoing_handles.clear()
                for edge in edges:
                    source = edge.get("source") or edge.get("sourceNodeID")
                    target = edge.get("target") or edge.get("targetNodeID")
                    source_handle = edge.get("sourcePortID") or edge.get("source_handle") or edge.get("sourceHandle")
                    if source:
                        nodes_with_outgoing.add(source)
                        if source not in outgoing_handles:
                            outgoing_handles[source] = set()
                        if source_handle:
                            outgoing_handles[source].add(source_handle)
                    if target:
                        nodes_with_incoming.add(target)
                    if source and target:
                        edge_pairs.add((source, target, source_handle or ""))

        def _fix_collapsed_loop_condition_branches(cond_id: str) -> None:
            if not is_loop:
                return
            if not start_node or not end_node:
                return

            start_id = start_node.get("id")
            end_id = end_node.get("id")
            if not start_id or not end_id:
                return

            by_handle: Dict[str, Dict] = {}
            for e in edges:
                if (e.get("sourceNodeID") or e.get("source")) != cond_id:
                    continue
                h = e.get("sourcePortID") or e.get("source_handle") or e.get("sourceHandle")
                if not h:
                    continue
                if h not in by_handle:
                    by_handle[h] = e

            if_edge = by_handle.get("if_branch")
            else_edge = by_handle.get("else_branch")
            if not if_edge or not else_edge:
                return

            if_tgt = if_edge.get("targetNodeID") or if_edge.get("target")
            else_tgt = else_edge.get("targetNodeID") or else_edge.get("target")

            if if_tgt == else_tgt == end_id:
                if_edge["targetNodeID"] = start_id
                if "target" in if_edge:
                    del if_edge["target"]
                edge_pairs.clear()
                nodes_with_outgoing.clear()
                nodes_with_incoming.clear()
                outgoing_handles.clear()
                for edge in edges:
                    source = edge.get("source") or edge.get("sourceNodeID")
                    target = edge.get("target") or edge.get("targetNodeID")
                    source_handle = edge.get("sourcePortID") or edge.get("source_handle") or edge.get("sourceHandle")
                    if source:
                        nodes_with_outgoing.add(source)
                        if source not in outgoing_handles:
                            outgoing_handles[source] = set()
                        if source_handle:
                            outgoing_handles[source].add(source_handle)
                    if target:
                        nodes_with_incoming.add(target)
                    if source and target:
                        edge_pairs.add((source, target, source_handle or ""))
        
        # STEP 1: Connect sequential chain (non-condition logic)
        for i in range(len(chain) - 1):
            source_node = chain[i]
            target_node = chain[i + 1]
            source_id = source_node.get("id")
            target_id = target_node.get("id")
            source_type = source_node.get("type", "")
            
            # Skip condition nodes - handle them separately
            if source_type == "condition":
                continue
            
            # Skip if edge already exists
            if (source_id, target_id, "") in edge_pairs:
                continue
            
            # Skip if source already has outgoing
            if source_id in nodes_with_outgoing:
                continue
            
            # Skip if target already has incoming
            if target_id in nodes_with_incoming:
                continue
            
            add_edge(source_id, target_id)
        
        # STEP 2: Handle condition nodes - connect ALL branches
        for cond_node in condition_nodes:
            cond_id = cond_node.get("id")
            cond_idx = node_index.get(cond_id, -1)
            # Normalize condition keys to if/elseif/else pattern to keep handles stable
            conditions = self._normalize_condition_keys(cond_node)

            has_incoming = cond_id in nodes_with_incoming

            # Normalize existing condition handles to match declared condition keys
            self._normalize_condition_handles(cond_id, conditions, edges)

            _dedupe_condition_outgoing_edges(cond_id)

            _fix_collapsed_loop_condition_branches(cond_id)

            # Refresh used handles after normalization
            used_handles = set()
            for e in edges:
                if (e.get("sourceNodeID") or e.get("source")) == cond_id:
                    handle = e.get("sourcePortID") or e.get("source_handle") or e.get("sourceHandle")
                    if handle:
                        used_handles.add(handle)
            outgoing_handles[cond_id] = used_handles

            # Ensure condition has an incoming edge from the previous node in chain
            if not has_incoming:
                chain_idx = next((i for i, n in enumerate(chain) if n.get("id") == cond_id), -1)
                if chain_idx > 0:
                    prev_id = chain[chain_idx - 1].get("id")
                    if prev_id:
                        add_edge(prev_id, cond_id)
            
            if not conditions:
                # No conditions defined, treat as regular node
                if cond_id not in nodes_with_outgoing:
                    # Find next node in chain
                    chain_idx = next((i for i, n in enumerate(chain) if n.get("id") == cond_id), -1)
                    if chain_idx >= 0 and chain_idx < len(chain) - 1:
                        next_id = chain[chain_idx + 1].get("id")
                        add_edge(cond_id, next_id)
                continue
            
            # Get required branch handles
            required_handles = [c.get("key") for c in conditions if c.get("key")]
            used_handles = outgoing_handles.get(cond_id, set())
            
            # Find nodes that come after this condition in the array
            # These are potential targets for the condition branches
            chain_idx = next((i for i, n in enumerate(chain) if n.get("id") == cond_id), -1)
            if chain_idx < 0:
                continue
            
            # Get potential targets (nodes after condition in chain)
            potential_targets = []
            for j in range(chain_idx + 1, len(chain)):
                potential_targets.append(chain[j])
            
            # Connect missing branches
            for i, handle in enumerate(required_handles):
                if handle in used_handles:
                    continue  # Already connected
                
                # Find a target for this branch
                # Strategy: Use nodes in order - first branch gets first available, etc.
                target_node = None
                
                # For the first missing branch, try to find a node that needs incoming
                for pt in potential_targets:
                    pt_id = pt.get("id")
                    pt_type = pt.get("type", "")
                    if pt_type == end_type:
                        # End node is always a valid fallback target
                        if target_node is None:
                            target_node = pt
                        continue
                    if pt_id not in nodes_with_incoming:
                        target_node = pt
                        break
                
                # If no unconnected node found, use end node or next in chain
                if target_node is None and potential_targets:
                    target_node = potential_targets[0]
                
                if target_node:
                    target_id = target_node.get("id")
                    add_edge(cond_id, target_id, handle)
                    used_handles.add(handle)
        
        # STEP 3: Ensure all nodes have incoming edges
        for i, node in enumerate(chain):
            node_id = node.get("id")
            node_type = node.get("type", "")
            
            if node_type == start_type:
                continue
            
            if node_id not in nodes_with_incoming and i > 0:
                # Find previous non-condition node, or use condition's first branch
                prev_node = chain[i - 1]
                prev_id = prev_node.get("id")
                prev_type = prev_node.get("type", "")
                
                if prev_type == "condition":
                    conditions = prev_node.get("data", {}).get("conditions", [])
                    if conditions:
                        # Use first available branch
                        used = outgoing_handles.get(prev_id, set())
                        for c in conditions:
                            handle = c.get("key")
                            if handle and handle not in used:
                                add_edge(prev_id, node_id, handle)
                                break
                        else:
                            # All branches used, use first one anyway
                            handle = conditions[0].get("key", "if_branch")
                            add_edge(prev_id, node_id, handle)
                    else:
                        add_edge(prev_id, node_id)
                else:
                    add_edge(prev_id, node_id)
        
        # STEP 4: Ensure all non-end nodes have outgoing edges
        for i, node in enumerate(chain):
            node_id = node.get("id")
            node_type = node.get("type", "")
            
            if node_type == end_type:
                continue
            
            # For condition nodes, check if ALL branches are connected
            if node_type == "condition":
                conditions = node.get("data", {}).get("conditions", [])
                if conditions:
                    required = {c.get("key") for c in conditions if c.get("key")}
                    used = outgoing_handles.get(node_id, set())
                    missing = required - used
                    if missing and i < len(chain) - 1:
                        # Connect missing branches to end or next node
                        target = end_node if end_node else chain[i + 1]
                        target_id = target.get("id")
                        for handle in missing:
                            add_edge(node_id, target_id, handle)
                continue
            
            # Regular nodes
            if node_id not in nodes_with_outgoing and i < len(chain) - 1:
                next_id = chain[i + 1].get("id")
                add_edge(node_id, next_id)
        
        if new_edges:
            edges.extend(new_edges)
            logger.info(f"[ValidatorAgent] Added {len(new_edges)} edges to fix disconnected nodes in {scope_name}")
        
        return new_edges


# Singleton instance
_validator_agent: Optional[ValidatorAgent] = None


def get_validator_agent() -> ValidatorAgent:
    """Get or create the ValidatorAgent singleton"""
    global _validator_agent
    if _validator_agent is None:
        _validator_agent = ValidatorAgent()
    return _validator_agent


