@echo off
REM ============================================================
REM eCan OTA Inno Setup Launcher
REM ============================================================
REM This script is generated by Python ota/core/installer.py
REM on each OTA upgrade. It waits for the host application to
REM exit completely before launching the Inno Setup installer,
REM avoiding file-lock conflicts and process-group races that
REM previously caused Inno Setup to wedge at "Created temporary
REM directory".
REM
REM Flow:
REM   1. Python writes a copy of this template to %TEMP% with
REM      ``WAIT_MODE`` (one of ``pid`` / ``name``),
REM      ``WAIT_TARGET`` (the PID or IMAGENAME to wait on),
REM      ``EXTRA_WAIT_SECONDS``, and ``INNO_CMD`` substituted in.
REM   2. Python launches this BAT via ``cmd /c <bat>`` with
REM      DETACHED_PROCESS so it survives the parent's exit.
REM   3. Python immediately calls ``sys.exit(0)``.
REM   4. This BAT polls ``tasklist`` until the host process is
REM      gone (handles crash, normal exit, AND the ~5s window
REM      Windows takes to release file handles after process
REM      termination).
REM   5. After an extra safety wait, it launches Inno Setup
REM      directly via ``start "" /B``. Because the BAT and Inno
REM      Setup are launched this way, the MSVCRT-quoting issue
REM      that broke the previous BAT implementation is avoided
REM      (the BAT substitutes ``INNO_CMD`` as a single string
REM      and ``start`` parses it with cmd.exe rules, NOT MSVCRT).
REM   6. Self-delete at the end.
REM
REM WAIT_MODE rationale:
REM   * ``pid`` is preferred (more precise). The launcher polls
REM     ``tasklist /FI "PID eq <n>"`` and exits as soon as THAT
REM     specific PID is gone. No risk of accidentally waiting
REM     on a sibling Python process, IDE process, etc.
REM   * ``name`` is the fallback for callers that don't know
REM     the PID. Less precise: if any process named ``python.exe``
REM     is alive, the BAT waits. Safe for the typical
REM     ``eCan.cn.exe`` / ``eCan.exe`` case where the IMAGENAME
REM     uniquely identifies the host app on a normal user box.
REM ============================================================

setlocal EnableExtensions EnableDelayedExpansion

set "WAIT_MODE={WAIT_MODE}"
set "WAIT_TARGET={WAIT_TARGET}"
set "EXTRA_WAIT_SECONDS={EXTRA_WAIT_SECONDS}"

REM ping -n N waits ~N-1 seconds (ping -n 2 = ~1s). We use +1 offset
REM because Windows' `timeout` command exits immediately when stdin is
REM not a real console (cmd.exe launched via subprocess.Popen without
REM DETACHED_PROCESS inherits a pipe for stdin), whereas `ping` works
REM reliably in that mode. Also, `timeout` is fundamentally incompatible
REM with `DETACHED_PROCESS + tasklist | find` pipelines: with DETACHED,
REM the `find` part of the pipe hangs waiting on stdin that never closes,
REM which is the exact bug this BAT was supposed to fix.
set "POLL_COUNT=2"
set /a EXTRA_WAIT_PING_COUNT=EXTRA_WAIT_SECONDS+1

echo [OTA Launcher] Wait mode: %WAIT_MODE%
echo [OTA Launcher] Wait target: %WAIT_TARGET%
echo [OTA Launcher] Extra wait after exit: %EXTRA_WAIT_SECONDS% seconds
echo [OTA Launcher] Polling tasklist...

REM ----------------------------------------------------------
REM Phase 1: Wait for the host process to exit completely.
REM
REM We use ``tasklist /FI "..." /NH`` (no header) and pipe
REM through ``find`` because bare ``tasklist`` always emits a
REM header row that confuses ``find``. /NH suppresses that
REM header on Windows Vista+ -- without it, find matches the
REM header text and exits 0, which would skip the wait entirely.
REM
REM The loop has a hard ceiling of 120 iterations (120 seconds)
REM to avoid an infinite wait if something exotic is wrong.
REM Past 120 s the launcher gives up and lets Inno Setup try
REM anyway -- better a failed install than a wedged launcher.
REM ----------------------------------------------------------
set "WAIT_COUNT=0"

:WAIT_LOOP
if !WAIT_COUNT! GEQ 120 goto WAIT_DONE

REM Run tasklist. Two prior bugs combined to make this loop
REM a no-op in production:
REM   1. ``set "FILTER=/FI \"IMAGENAME eq %WAIT_TARGET%\""``
REM      inside the if/else block -- cmd.exe's ``set`` does NOT
REM      process ``\"`` as an escape, so FILTER ended up with
REM      literal backslashes (``/FI \"IMAGENAME eq ...\"``) and
REM      tasklist failed with ``Invalid parameter/option - 'eq'``.
REM   2. ``2^>nul`` -- the caret escapes the ``>``, so tasklist
REM      received the literal string ``2>nul`` as an argument
REM      instead of stderr redirection. Same ``Invalid parameter/
REM      option - '2>nul'`` failure mode.
REM The fix: build the filter inline (no intermediate FILTER
REM variable) and use bare ``2>nul`` (no caret) for stderr
REM redirection. The previous ``set "FILTER=..."`` construction
REM looked correct on paper but silently bypassed the host-process
REM wait in production, causing "Created temporary directory"
REM hangs when Inno Setup tried to overwrite locked files.
REM
REM ``/NH`` suppresses the header row that bare ``tasklist``
REM emits on Vista+ -- without it, ``find`` matches the header
REM text and exits 0, which would skip the wait entirely.
if /I "%WAIT_MODE%"=="pid" (
    tasklist /FI "PID eq %WAIT_TARGET%" /NH 2>nul | find /I "%WAIT_TARGET%" >nul 2>&1
) else (
    tasklist /FI "IMAGENAME eq %WAIT_TARGET%" /NH 2>nul | find /I "%WAIT_TARGET%" >nul 2>&1
)
if %ERRORLEVEL% EQU 0 (
    REM Target still running -- wait ~1 second and re-check.
    REM We use ``ping 127.0.0.1 -n 2`` instead of ``timeout /t 1``
    REM because:
    REM   * ``timeout`` requires a real console for stdin; when launched
    REM     without DETACHED_PROCESS, cmd.exe inherits Python's pipe
    REM     stdin and ``timeout`` returns immediately with "不支持键盘输入
    REM     系统请求" instead of waiting. This was the cause of OTA
    REM     installations "completing" instantly without ever launching
    REM     Inno Setup on dev machines.
    REM   * ``ping 127.0.0.1 -n 2`` reliably sleeps ~1 second regardless
    REM     of stdio configuration (no console needed, no interactive
    REM     input required). Verified on Windows 10/11 with all combos
    of subprocess.Popen creationflags.
    set /a WAIT_COUNT+=1
    ping 127.0.0.1 -n %POLL_COUNT% >nul 2>&1
    goto WAIT_LOOP
)

:WAIT_DONE
echo [OTA Launcher] Host process exited (waited !WAIT_COUNT! seconds).

REM ----------------------------------------------------------
REM Phase 2: Extra wait for Windows to release file handles.
REM
REM Even after ``tasklist`` confirms the process is gone,
REM Windows can take several seconds to release file handles
REM held by the terminated process. Without this wait Inno
REM Setup's file-replacement step hits "DeleteFile failed;
REM error code 5. 拒绝访问" on ``eCan.cn.exe`` / ``*.dll``.
REM
REM ``EXTRA_WAIT_SECONDS`` defaults to 5 -- enough for the
REM common case. The Python side passes a longer value (e.g.
REM 10 s on AV-heavy systems) when logs show persistent EBUSY.
REM ----------------------------------------------------------
echo [OTA Launcher] Sleeping %EXTRA_WAIT_SECONDS% seconds for file-handle release...
ping 127.0.0.1 -n %EXTRA_WAIT_PING_COUNT% >nul 2>&1

REM ----------------------------------------------------------
REM Phase 3: Launch Inno Setup.
REM
REM We use ``start "" /B <command>`` instead of calling the
REM installer directly so:
REM   * The BAT process does NOT block waiting for Inno Setup
REM     (important for the self-delete below).
REM   * Inno Setup's exit code isn't returned to the BAT, so
REM     a non-zero exit doesn't skip the self-delete.
REM
REM The empty-string title ``""`` is required by ``start``;
REM without it, ``start`` interprets the first quoted argument
REM as the window title and the actual command never runs.
REM
REM ``{INNO_CMD}`` is the FULL command line, already escaped
REM by Python before we wrote it here. ``start`` uses cmd.exe
REM parsing rules (NOT MSVCRT), so a value like
REM ``/DIR=C:\Users\foo`` passes through to Inno Setup
REM verbatim and Inno Setup's argv parser reads it as
REM ``/DIR=C:\Users\foo`` -- clean.
REM ----------------------------------------------------------
echo [OTA Launcher] Starting Inno Setup: {INNO_CMD}
start "" /B {INNO_CMD}

REM ----------------------------------------------------------
REM Phase 4: Self-delete.
REM
REM The trick: launch a SECOND background ``cmd`` that sleeps
REM 2 seconds (giving the parent BAT time to exit and release
REM the file handle), then deletes THIS BAT. This is the only
REM reliable way for a script to delete itself on Windows
REM without a 3rd-party tool -- direct ``del %~f0`` would fail
REM because the BAT is still mapped into the running process.
REM
REM ``/B`` keeps it background, ``>nul`` swallows output, and
REM the ``cmd /c`` wrapper is needed because ``del`` is a
REM builtin.
REM ----------------------------------------------------------
echo [OTA Launcher] Scheduling self-delete in 2 seconds...
start "" /B cmd /c "ping 127.0.0.1 -n 2 >nul & del /F /Q %~f0" >nul 2>&1

echo [OTA Launcher] Done -- Inno Setup is running independently.
endlocal
exit /b 0
