#!/usr/bin/env python3
"""
Inject build information into application

Injects environment, version and other information into the application at build time,
for runtime use (including OTA updates, banner display, etc.)

Usage:
    python3 build_system/scripts/inject_build_info.py \
        --version 1.0.0 \
        --environment production \
        --git-commit abc123
"""

import argparse
import json
from datetime import datetime
from pathlib import Path
import subprocess
import sys

# Project root directory
project_root = Path(__file__).parent.parent.parent


def get_git_info() -> dict:
    """Get Git information"""
    try:
        # Get commit hash
        commit = subprocess.check_output(
            ['git', 'rev-parse', '--short', 'HEAD'],
            cwd=project_root
        ).decode().strip()
        
        # Get branch
        branch = subprocess.check_output(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            cwd=project_root
        ).decode().strip()
        
        # Get commit time
        commit_time = subprocess.check_output(
            ['git', 'log', '-1', '--format=%ci'],
            cwd=project_root
        ).decode().strip()
        
        return {
            'commit': commit,
            'branch': branch,
            'commit_time': commit_time
        }
    except Exception as e:
        print(f"Warning: Could not get git info: {e}")
        return {
            'commit': 'unknown',
            'branch': 'unknown',
            'commit_time': 'unknown'
        }


def inject_python_config(version: str, environment: str, git_info: dict, build_time: str):
    """
    Inject Python build data file
    
    Generate config/build_data.py for runtime use
    Note: config/build_info.py contains the core logic and should not be modified
    """
    config_dir = project_root / 'config'
    config_dir.mkdir(exist_ok=True)
    
    config_file = config_dir / 'build_data.py'
    
    # Determine channel
    channel_map = {
        "development": "dev",
        "test": "beta",
        "staging": "stable",
        "production": "stable"
    }
    channel = channel_map.get(environment, "stable")
    
    # Generate build data content (pure data, no logic)
    content = f'''"""
Build Data
This file is automatically generated by build_system/scripts/inject_build_info.py
Do not modify manually

For usage, import from config.build_info instead:
    from config.build_info import VERSION, ENVIRONMENT, get_banner
"""

# Build data dictionary - imported by config/build_info.py
BUILD_DATA = {{
    "version": "{version}",
    "environment": "{environment}",
    "channel": "{channel}",
    "git_commit": "{git_info['commit']}",
    "git_branch": "{git_info['branch']}",
    "git_commit_time": "{git_info['commit_time']}",
    "build_time": "{build_time}",
    "build_timestamp": {datetime.now().timestamp()},
    "ota_enabled": True,
    "signature_required": {environment in ["staging", "production"]},
    "is_fallback": False
}}
'''
    
    # Write to file
    with open(config_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"[OK] Generated: {config_file}")
    return config_file



def inject_version_file(version: str):
    """
    Update VERSION file
    """
    version_file = project_root / 'VERSION'
    
    with open(version_file, 'w', encoding='utf-8') as f:
        f.write(version)
    
    print(f"[OK] Updated: {version_file}")
    return version_file


def get_version_from_file() -> str:
    """
    Read version number from VERSION file
    
    Returns:
        Version string, returns "0.0.0" if file does not exist
    """
    version_file = project_root / 'VERSION'
    if version_file.exists():
        version = version_file.read_text().strip()
        print(f"[INFO] Read version from VERSION file: {version}")
        return version
    else:
        print("[WARN] VERSION file not found, using default: 0.0.0")
        return "0.0.0"


def main():
    parser = argparse.ArgumentParser(
        description='Inject build information into application'
    )
    parser.add_argument(
        '--version',
        help='Version string (e.g., 1.0.0, 1.0.0-rc.1). If not provided, read from VERSION file'
    )
    parser.add_argument(
        '--environment',
        required=True,
        choices=['development', 'test', 'staging', 'production', 'simulation'],
        help='Target environment'
    )
    parser.add_argument(
        '--git-commit',
        help='Git commit hash (auto-detected if not provided)'
    )
    
    args = parser.parse_args()
    
    # Priority: command line argument > VERSION file > default value
    version = args.version or get_version_from_file()
    
    # Get Git information
    git_info = get_git_info()
    if args.git_commit:
        git_info['commit'] = args.git_commit
    
    # Build time
    build_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    print("=" * 60)
    print("Injecting Build Information")
    print("=" * 60)
    print(f"Version:     {version}")
    print(f"Environment: {args.environment}")
    print(f"Git Commit:  {git_info['commit']}")
    print(f"Git Branch:  {git_info['branch']}")
    print(f"Build Time:  {build_time}")
    print("=" * 60)
    print()
    
    # Inject configuration files
    inject_python_config(version, args.environment, git_info, build_time)
    inject_version_file(version)
    
    print()
    print("=" * 60)
    print("[OK] Build information injected successfully!")
    print("=" * 60)
    print()
    print("Usage in Python:")
    print("  from config.build_info import get_banner, BUILD_INFO")
    print("  print(get_banner())")
    print("=" * 60)


if __name__ == '__main__':
    main()
