CREATE TABLE `agent_task_rels` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `agent_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `task_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vehicle_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `priority` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `progress` double DEFAULT '0',
  `scheduled_start` datetime(6) DEFAULT NULL,
  `actual_start` datetime(6) DEFAULT NULL,
  `estimated_end` datetime(6) DEFAULT NULL,
  `actual_end` datetime(6) DEFAULT NULL,
  `result` json DEFAULT NULL,
  `error_message` text COLLATE utf8mb4_unicode_ci,
  `logs` text COLLATE utf8mb4_unicode_ci,
  `cpu_usage` double DEFAULT NULL,
  `memory_usage` double DEFAULT NULL,
  `execution_time` double DEFAULT NULL,
  `execution_context` json DEFAULT NULL,
  `retry_count` int DEFAULT '0',
  `max_retries` int DEFAULT '3',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `fk_atr_agent` (`agent_id`),
  KEY `fk_atr_task` (`task_id`),
  KEY `fk_atr_vehicle` (`vehicle_id`),
  CONSTRAINT `fk_atr_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_atr_task` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_atr_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `agent_vehicles` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
