CREATE TABLE `agent_task_skill_rels` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `task_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `skill_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'primary',
  `execution_order` int DEFAULT '0',
  `is_required` tinyint(1) DEFAULT '1',
  `skill_config` json DEFAULT NULL,
  `parameters` json DEFAULT NULL,
  `constraints_json` json DEFAULT NULL,
  `estimated_duration` double DEFAULT NULL,
  `estimated_cost` double DEFAULT NULL,
  `resource_requirements` json DEFAULT NULL,
  `success_criteria` json DEFAULT NULL,
  `quality_threshold` double DEFAULT '0.8',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `actual_duration` double DEFAULT NULL,
  `actual_cost` double DEFAULT NULL,
  `quality_score` double DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_task_skill` (`task_id`,`skill_id`),
  KEY `fk_ats_skill` (`skill_id`),
  CONSTRAINT `fk_ats_skill` FOREIGN KEY (`skill_id`) REFERENCES `agent_skills` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_ats_task` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
