from typing import TYPE_CHECKING, Any, Optional, Dict
import json
import socket
import requests
import traceback
from app_context import AppContext
if TYPE_CHECKING:
    from gui.MainGUI import MainWindow
from gui.ipc.handlers import validate_params, resolve_username
from gui.ipc.registry import IPCHandlerRegistry
from gui.ipc.types import IPCRequest, IPCResponse, create_error_response, create_success_response
from gui.ipc.context_bridge import get_handler_context
from agent.cloud_api.constants import Operation
from agent.ec_tasks.ser_consts import TASK_SERIALIZATION_EXCLUDE

from utils.logger_helper import logger_helper as logger

# ============================================================================
# Helper Functions for Agent Task Management
# ============================================================================

def _serialize_task_status(status) -> str:
    """Serialize TaskStatus object to a JSON-serializable string
    
    Args:
        status: TaskStatus object, string, or None
        
    Returns:
        str: Status string (e.g., 'pending', 'working', 'completed')
    """
    if status is None:
        return 'pending'
    
    # If it's already a string, return it
    if isinstance(status, str):
        return status
    
    # If it's a TaskStatus object (Pydantic model), extract the state
    if hasattr(status, 'state'):
        state = status.state
        # TaskState is an enum, get its value
        if hasattr(state, 'value'):
            return state.value
        return str(state)
    
    # Fallback: convert to string
    return str(status)


def _get_agent_task_service(request: Optional[Dict] = None, params: Optional[Dict] = None):
    """Get agent task service from context (uses correct user-specific database path)

    Args:
        request: IPC request (optional, for context)
        params: IPC params (optional, for context)

    Returns:
        task_service: Database agent task service instance, or None if not available
    """
    from gui.ipc.context_bridge import get_handler_context
    ctx = get_handler_context(request, params)
    if ctx:
        ec_db_mgr = ctx.get_ec_db_mgr()
        if ec_db_mgr:
            return ec_db_mgr.task_service
    logger.error("[task_handler] Database manager not available - cannot access database")
    return None


def _safe_parse_json(value: Any, default: Any = None):
    """Parse a value that may be a JSON string or already a dict/list."""
    if value is None:
        return default
    if isinstance(value, (dict, list)):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
            return parsed
        except (json.JSONDecodeError, ValueError):
            return default
    return default


def _clear_skill_runtime_markers(metadata: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(metadata, dict):
        return {}
    cleaned = dict(metadata)
    state = cleaned.get('state')
    if isinstance(state, dict):
        new_state = dict(state)
        attrs = new_state.get('attributes')
        if isinstance(attrs, dict):
            new_attrs = dict(attrs)
            new_attrs.pop('__this_node__', None)
            new_attrs.pop('__llm_timings__', None)
            new_attrs.pop('async_response', None)
            new_attrs.pop('run_id', None)
            new_state['attributes'] = new_attrs
        cleaned['state'] = new_state
    cleaned.pop('run_id', None)
    cleaned.pop('runID', None)
    return cleaned


def _prepare_agent_task_data(agent_task_info: Dict[str, Any], username: str, agent_task_id: Optional[str] = None) -> Dict[str, Any]:
    """Prepare agent task data for database storage

    Args:
        agent_task_info: Raw agent task information from frontend
        username: Owner username
        agent_task_id: Optional agent task ID (if None, will be generated by database)

    Returns:
        Dict containing prepared agent task data
    """
    # Get metadata from frontend (could be 'metadata' or 'settings' key)
    # Frontend may send JSON strings via toAwsJson — parse them back
    metadata = _safe_parse_json(agent_task_info.get('metadata', agent_task_info.get('settings')), {})
    if not isinstance(metadata, dict):
        metadata = {}
    
    # NOTE: skill is now managed through task-skill relationship table (DBAgentTaskSkillRel)
    # Don't store skill in metadata anymore
    
    agent_task_data = {
        'name': agent_task_info.get('name', 'Unnamed Agent Task'),
        'owner': username,
        'description': agent_task_info.get('description', ''),
        'source': agent_task_info.get('source', 'ui'),
        'priority': agent_task_info.get('priority', 'medium'),
        'status': agent_task_info.get('status', 'pending'),
        'task_type': agent_task_info.get('task_type', 'local'),
        'objectives': _safe_parse_json(agent_task_info.get('objectives'), []),
        'schedule': _safe_parse_json(agent_task_info.get('schedule'), {}),
        'trigger': agent_task_info.get('trigger') or agent_task_info.get('trigger_type') or 'manual',
        'progress': agent_task_info.get('progress', 0.0),
        'result': _safe_parse_json(agent_task_info.get('result'), {}),
        'error_message': agent_task_info.get('error_message', ''),
        'settings': metadata,
        'org_id': agent_task_info.get('org_id', None),
    }

    # Only add ID if provided (for updates)
    if agent_task_id:
        agent_task_data['id'] = agent_task_id

    return agent_task_data


def _skill_binding_changed(task_id: str, incoming_skill_ids: list, request=None, params=None) -> bool:
    try:
        task_service = _get_agent_task_service(request, params)
        if not task_service or not task_id:
            return False
        existing = task_service.get_task_skills(task_id, role='primary')
        existing_ids = []
        if existing.get('success') and existing.get('data'):
            existing_ids = sorted(
                str(rel.get('skill_id')).strip()
                for rel in existing.get('data', [])
                if rel.get('skill_id')
            )
        incoming_ids = sorted(str(skill_id).strip() for skill_id in (incoming_skill_ids or []) if skill_id)
        return existing_ids != incoming_ids
    except Exception as e:
        logger.warning(f"[task_handler] Failed to compare task skill bindings: {e}")
        return False


def _manage_task_skill_relationships(task_id: str, skill_ids: list, request=None, params=None) -> bool:
    """Create or update task-skill relationships using task service (supports multiple skills)
    
    Args:
        task_id: Task ID
        skill_ids: List of skill IDs (empty list to remove all relationships)
        request: IPC request (for context/db access)
        params: IPC params (for context/db access)
        
    Returns:
        bool: True if successful
    """
    try:
        logger.debug(f"[_manage_task_skill_relationships] START: task_id={task_id}, skill_ids={skill_ids}")
        task_service = _get_agent_task_service(request, params)
        if not task_service:
            logger.error(f"[_manage_task_skill_relationships] Task service not available")
            return False
        
        # Get existing skills for this task
        existing_skills = task_service.get_task_skills(task_id, role='primary')
        logger.debug(f"[_manage_task_skill_relationships] Existing skills query result: {existing_skills}")
        
        # Remove existing primary skill relationships
        if existing_skills.get('success') and existing_skills.get('data'):
            logger.debug(f"[_manage_task_skill_relationships] Removing {len(existing_skills['data'])} existing skill relationships")
            for skill_rel in existing_skills['data']:
                remove_result = task_service.remove_skill_from_task(task_id, skill_rel['skill_id'])
                logger.debug(f"[_manage_task_skill_relationships] Removed skill {skill_rel['skill_id']}: {remove_result}")
        
        # Add new relationships for all skill_ids
        logger.debug(f"[_manage_task_skill_relationships] Adding {len(skill_ids or [])} new skill relationships")
        for skill_id in (skill_ids or []):
            if skill_id:
                logger.debug(f"[_manage_task_skill_relationships] Adding skill {skill_id} to task {task_id}")
                result = task_service.add_skill_to_task(
                    task_id=task_id,
                    skill_id=skill_id,
                    role='primary',
                    is_required=True
                )
                logger.debug(f"[_manage_task_skill_relationships] Add skill result: {result}")
                if not result.get('success'):
                    logger.error(f"[_manage_task_skill_relationships] Failed to add skill {skill_id} to task: {result.get('error')}")
                    return False
        
        logger.debug(f"[_manage_task_skill_relationships] SUCCESS: All skills processed")
        return True
            
    except Exception as e:
        logger.error(f"[_manage_task_skill_relationships] EXCEPTION: {e}")
        import traceback
        logger.error(f"[_manage_task_skill_relationships] Traceback: {traceback.format_exc()}")
        return False


def _get_task_skill_info(task_id: str, request: Optional[Dict] = None, params: Optional[Dict] = None) -> Optional[Dict[str, Any]]:
    """Get skill information from task-skill relationship using task service
    
    Args:
        task_id: Task ID
        request: IPC request (optional, for context)
        params: IPC params (optional, for context)
        
    Returns:
        Dict with skill info (id, name) or None
    """
    try:
        task_service = _get_agent_task_service(request, params)
        if not task_service:
            logger.error(f"[task_handler] Task service not available")
            return None
        
        skills = task_service.get_task_skills(task_id, role='primary')
        
        if skills.get('success') and skills.get('data'):
            skill_rels = skills['data']
            if skill_rels and len(skill_rels) > 0:
                skill_rel = skill_rels[0]
                skill_id = skill_rel.get('skill_id')
                
                if skill_id:
                    ctx = get_handler_context(request, params)
                    if ctx:
                        ec_db_mgr = ctx.get_ec_db_mgr()
                        if ec_db_mgr:
                            skill_service = ec_db_mgr.get_skill_service()
                            if skill_service:
                                skill_result = skill_service.get_skill_by_id(skill_id)
                                if skill_result.get('success') and skill_result.get('data'):
                                    skill_data = skill_result['data']
                                    return {
                                        'id': skill_data.get('id'),
                                        'name': skill_data.get('name')
                                    }
        
        return None
        
    except Exception as e:
        logger.error(f"[task_handler] Failed to get task skill info: {e}")
        return None


def _resolve_compiled_skill_from_db(
    skill_id: str,
    request: Optional[Dict] = None,
    params: Optional[Dict] = None,
):
    """Resolve and compile a skill object from DB by skill_id.

    This is used by runtime task-skill sync when the selected skill is not in the
    current compiled pool (e.g., cloud-subscribed skill not yet compiled in memory).
    """
    try:
        if not skill_id:
            return None

        ctx = get_handler_context(request, params)
        if not ctx:
            return None

        ec_db_mgr = ctx.get_ec_db_mgr()
        if not ec_db_mgr:
            return None

        skill_service = ec_db_mgr.get_skill_service() if hasattr(ec_db_mgr, 'get_skill_service') else getattr(ec_db_mgr, 'skill_service', None)
        if not skill_service:
            return None

        skill_result = skill_service.get_skill_by_id(skill_id)
        if not skill_result.get('success') or not skill_result.get('data'):
            return None

        from agent.ec_skills.build_agent_skills import _convert_db_skill_to_object

        compiled_skill = _convert_db_skill_to_object(skill_result.get('data'))
        if compiled_skill:
            logger.info(
                f"[task_handler] ✅ Compiled runtime skill from DB: skill_id={skill_id}, "
                f"skill_name={getattr(compiled_skill, 'name', '')}"
            )
        else:
            logger.warning(
                f"[task_handler] ⚠️ Failed to compile skill from DB (file missing?): skill_id={skill_id}"
            )
        return compiled_skill
    except Exception as e:
        logger.warning(f"[task_handler] Failed to compile skill from DB for runtime sync: skill_id={skill_id}, error={e}")
        return None


def _update_agent_task_in_memory(agent_task_id: str, agent_task_data: Dict[str, Any]) -> bool:
    """Update or add agent task in mainwin.agent_tasks memory

    Args:
        agent_task_id: Agent task ID
        agent_task_data: Agent task data dictionary

    Returns:
        bool: True if successful, False otherwise
    """
    try:
        from gui.ipc.context_bridge import get_handler_context
        ctx = get_handler_context()
        if not ctx:
            logger.warning("[task_handler] Context not available")
            return False
        
        # Get agent_tasks from context
        agent_tasks = ctx.get_agent_tasks()
        if agent_tasks is None:
            logger.warning("[task_handler] agent_tasks not available")
            return False

        from agent.ec_tasks import ManagedTask
        from a2a.types import TaskStatus, TaskState

        # Check if agent task already exists in memory
        existing_index = None
        agent_tasks_list = agent_tasks  # Use the list from get_agent_tasks()
        for i, agent_task in enumerate(agent_tasks_list):
            if hasattr(agent_task, 'id') and agent_task.id == agent_task_id:
                existing_index = i
                break

        # Create agent task object with all required fields
        # ManagedTask requires: id, name, status (with state), skill, state
        # Valid TaskState values: submitted, working, input-required, completed, canceled, failed, unknown
        task_status = agent_task_data.get('status', 'submitted')
        # Map common status values to valid TaskState
        status_mapping = {
            'pending': 'submitted',
            'ready': 'submitted',
            'running': 'working',
            'paused': 'input-required',
            'done': 'completed',
            'error': 'failed'
        }
        task_status = status_mapping.get(task_status, task_status)
        
        # Get metadata from 'settings' (DB field name) or 'metadata' (API field name)
        metadata = agent_task_data.get('settings', agent_task_data.get('metadata', {}))
        if not isinstance(metadata, dict):
            metadata = {}
        
        # Get skill from task-skill relationship table
        skill_info = _get_task_skill_info(agent_task_id, request=None, params=None)
        skill_name = skill_info['name'] if skill_info else ''
        
        agent_task_obj = ManagedTask(
            id=agent_task_id,
            context_id=agent_task_data.get('context_id', agent_task_id),
            name=agent_task_data['name'],
            description=agent_task_data.get('description', ''),
            owner=agent_task_data['owner'],
            task_type=agent_task_data.get('task_type', 'local'),
            status=TaskStatus(
                state=TaskState(task_status)
            ),
            skill=skill_name,
            state={},
            metadata=metadata
        )

        if existing_index is not None:
            # Update existing agent task
            agent_tasks[existing_index] = agent_task_obj
            logger.info(f"[task_handler] Updated agent task in memory: {agent_task_data['name']}, total tasks: {len(agent_tasks)}")
        else:
            # Add new agent task - append directly to the list (which is a reference to mw.agent_tasks)
            agent_tasks.append(agent_task_obj)
            logger.info(f"[task_handler] Added new agent task to memory: {agent_task_data['name']}, total tasks: {len(agent_tasks)}")

        return True

    except Exception as e:
        logger.warning(f"[task_handler] Failed to update mainwin.agent_tasks: {e}")
        return False


def _sync_runtime_task_skill(
    task_id: str,
    request: Optional[Dict] = None,
    params: Optional[Dict] = None,
    preferred_skill_ids: Optional[list] = None,
) -> bool:
    """Sync task skill into runtime agent task objects used by routing.

    Chat routing uses ``agent.tasks`` in runner, not only ``mainwin.agent_tasks``.
    After task-skill relationship changes, update runtime task objects so the
    next message uses the latest skill binding without requiring app restart.
    """
    try:
        from gui.ipc.context_bridge import get_handler_context

        ctx = get_handler_context(request, params)
        if not ctx:
            logger.warning("[task_handler] Context not available for runtime skill sync")
            return False

        # Resolve target skill id (prefer explicit ids from save payload)
        skill_id = None
        if preferred_skill_ids:
            for sid in preferred_skill_ids:
                if sid:
                    skill_id = str(sid)
                    break

        skill_name = None
        if not skill_id:
            skill_info = _get_task_skill_info(task_id, request=request, params=params)
            if skill_info:
                skill_id = skill_info.get('id')
                skill_name = skill_info.get('name')

        if not skill_id and not skill_name:
            logger.warning(f"[task_handler] No skill relationship found for runtime sync, task_id={task_id}")
            return False

        # Resolve compiled skill object from current runtime skill pool
        compiled_skill = None
        agent_skills = ctx.get_agent_skills() if ctx else []

        # Compile fresh skill object from DB when skill_id is available.
        # This ensures dynamic skill switch / provider edits take effect without restart.
        if skill_id:
            compiled_skill = _resolve_compiled_skill_from_db(skill_id, request=request, params=params)
            if compiled_skill and isinstance(agent_skills, list):
                # Update agent_skills pool with fresh compiled skill
                replaced = False
                for idx, sk in enumerate(agent_skills):
                    if str(getattr(sk, 'id', '')) == str(skill_id):
                        agent_skills[idx] = compiled_skill
                        replaced = True
                        break
                if not replaced:
                    agent_skills.append(compiled_skill)
        
        # If DB compilation failed and we have skill_name, try to find by name in memory
        # (This is only for the case where skill_id is not available)
        if not compiled_skill and skill_name:
            compiled_skill = next((sk for sk in agent_skills if str(getattr(sk, 'name', '')) == str(skill_name)), None)

        if not compiled_skill:
            logger.warning(
                f"[task_handler] Target skill not found in compiled pool for runtime sync: "
                f"task_id={task_id}, skill_id={skill_id}, skill_name={skill_name}"
            )
            return False

        updated = 0
        agents = ctx.get_agents() if ctx else []
        for agent in agents or []:
            agent_tasks = getattr(agent, 'tasks', None) or []
            for t in agent_tasks:
                if getattr(t, 'id', None) == task_id:
                    t.skill = compiled_skill
                    current_metadata = getattr(t, 'metadata', {}) or {}
                    if isinstance(current_metadata, dict):
                        t.metadata = _clear_skill_runtime_markers(current_metadata)
                    current_state = getattr(t, 'state', None)
                    if isinstance(current_state, dict):
                        t.state = _clear_skill_runtime_markers({'state': current_state}).get('state', {})
                    updated += 1

            # Runner may hold task refs in a dict as well
            runner = getattr(agent, 'runner', None)
            runner_tasks = getattr(runner, 'tasks', None) if runner else None
            if isinstance(runner_tasks, dict):
                rt = runner_tasks.get(task_id)
                if rt is not None:
                    rt.skill = compiled_skill
                    current_metadata = getattr(rt, 'metadata', {}) or {}
                    if isinstance(current_metadata, dict):
                        rt.metadata = _clear_skill_runtime_markers(current_metadata)
                    current_state = getattr(rt, 'state', None)
                    if isinstance(current_state, dict):
                        rt.state = _clear_skill_runtime_markers({'state': current_state}).get('state', {})

        if updated > 0:
            logger.info(
                f"[task_handler] ✅ Runtime task skill synced: task_id={task_id}, "
                f"skill={getattr(compiled_skill, 'name', '')}, updated_tasks={updated}"
            )
            return True

        logger.warning(f"[task_handler] Runtime task not found for skill sync: task_id={task_id}")
        return False
    except Exception as e:
        logger.warning(f"[task_handler] Failed to sync runtime task skill: {e}")
        return False


def _create_clean_agent_task_response(agent_task_id: str, agent_task_data: Dict[str, Any]) -> Dict[str, Any]:
    """Create clean agent task data for response (avoid circular references)

    Args:
        agent_task_id: Agent task ID
        agent_task_data: Agent task data dictionary

    Returns:
        Dict containing clean agent task data
    """
    # Get metadata from 'settings' (DB field name) or 'metadata' (API field name)
    metadata = agent_task_data.get('settings', agent_task_data.get('metadata', {}))
    if not isinstance(metadata, dict):
        metadata = {}
    
    # Get skill info from task-skill relationship table
    skill_info = _get_task_skill_info(agent_task_id, request=None, params=None)
    skill_name = skill_info['name'] if skill_info else ''
    
    return {
        'id': agent_task_id,
        'name': agent_task_data['name'],
        'owner': agent_task_data['owner'],
        'description': agent_task_data['description'],
        'priority': agent_task_data.get('priority', 'medium'),
        'status': agent_task_data.get('status', 'pending'),
        'task_type': agent_task_data.get('task_type', ''),
        'progress': agent_task_data.get('progress', 0.0),
        'schedule': agent_task_data.get('schedule', {}),
        'trigger': agent_task_data.get('trigger', 'manual'),
        'skill': skill_name,  # Get skill from relationship table
        'metadata': metadata
    }


@IPCHandlerRegistry.handler('refresh_agent_task_status')
def handle_refresh_agent_task_status(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Refresh a single task status from database and return latest data."""
    try:
        logger.debug(f"Refresh task status handler called with request: {request}")

        username = resolve_username(request, params)
        if not username:
            logger.warning("Invalid parameters for refresh task status: Missing username")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: username (or owner/userId)')

        if not params or not params.get('task_id'):
            logger.warning("Invalid parameters for refresh task status: Missing task_id")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: task_id')

        task_id = str(params.get('task_id'))

        agent_task_service = _get_agent_task_service(request, params)
        if not agent_task_service:
            return create_error_response(request, 'SERVICE_ERROR', 'Database service not available')

        result = agent_task_service.query_tasks(id=task_id)
        if not result.get('success') or not result.get('data'):
            return create_error_response(request, 'TASK_NOT_FOUND', f'Agent task not found: {task_id}')

        task_data = result.get('data', [])[0]
        _update_agent_task_in_memory(task_id, task_data)
        clean_task = _create_clean_agent_task_response(task_id, task_data)

        return create_success_response(request, {
            'message': 'Refresh agent task status successful',
            'task': clean_task
        })

    except Exception as e:
        logger.error(f"Error in refresh task status handler: {e} {traceback.format_exc()}")
        return create_error_response(
            request,
            'REFRESH_TASK_STATUS_ERROR',
            f"Error during refresh task status: {str(e)}"
        )


@IPCHandlerRegistry.handler('run_agent_task')
def handle_run_agent_task(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Run an agent task locally or in cloud depending on cloud_based flag."""
    try:
        logger.debug(f"Run agent task handler called with request: {request}")

        username = resolve_username(request, params)
        if not username:
            logger.warning("Invalid parameters for run agent task: Missing username")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: username (or owner/userId)')

        if not params or not params.get('task_id'):
            logger.warning("Invalid parameters for run agent task: Missing task_id")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: task_id')

        task_id = str(params.get('task_id'))
        cloud_based = bool(params.get('cloud_based', False))
        skill_id = params.get('skill_id')
        skill_name = params.get('skill')

        from gui.ipc.context_bridge import get_handler_context
        ctx = get_handler_context(request, params)
        agents = ctx.get_agents() if ctx else []
        agent_tasks = ctx.get_agent_tasks() if ctx else []

        task_obj = next((t for t in agent_tasks if getattr(t, 'id', None) == task_id), None)

        if task_obj is None:
            from agent.ec_agents.create_agent_tasks import _convert_db_agent_task_to_object
            task_service = _get_agent_task_service(request, params)
            db_result = task_service.query_tasks(id=task_id) if task_service else {}
            if db_result.get('success') and db_result.get('data'):
                task_obj = _convert_db_agent_task_to_object(db_result.get('data')[0])
                if task_obj and agents:
                    agents[0].tasks.append(task_obj)

        if task_obj is None:
            return create_error_response(request, 'TASK_NOT_FOUND', f'Agent task not found: {task_id}')

        # Resolve agent
        agent_id = getattr(task_obj, 'agent_id', None) or params.get('agent_id')
        agent = next((ag for ag in agents if getattr(getattr(ag, 'card', None), 'id', None) == agent_id), None) if agents else None
        agent = agent or (agents[0] if agents else None)

        if not agent:
            return create_error_response(request, 'AGENT_NOT_FOUND', 'No agent available to run the task')

        # Resolve skill
        skill_obj = None
        agent_skills = ctx.get_agent_skills() if ctx else []
        if skill_id:
            skill_obj = next((sk for sk in agent_skills if getattr(sk, 'id', None) == skill_id), None)
        if not skill_obj and skill_name:
            skill_obj = next((sk for sk in agent_skills if getattr(sk, 'name', None) == skill_name), None)

        if skill_obj:
            task_obj.skill = skill_obj

        if cloud_based:
            if not skill_obj:
                return create_error_response(request, 'SKILL_NOT_FOUND', 'Skill not found for cloud run')

            from agent.cloud_api.cloud_api import run_skill_in_cloud, get_appsync_endpoint
            login = AppContext.get_login()
            tokens = login.auth_manager.get_tokens()
            token = tokens.get('access_token')
            if not token:
                return create_error_response(request, 'TOKEN_REQUIRED', 'No access token available')

            skill_dict = skill_obj.to_dict() if hasattr(skill_obj, 'to_dict') else skill_obj
            skill_json = json.dumps(skill_dict)
            metadata = {
                "run_id": task_id,
                "dev_mode": False,
                "local_machine": socket.gethostname()
            }

            session = requests.Session()
            endpoint = get_appsync_endpoint()
            result = run_skill_in_cloud(session, access_token, skill_json, username, metadata, endpoint)

            if not result.get('success'):
                return create_error_response(request, 'RUN_TASK_ERROR', str(result.get('error') or result.get('errors') or 'Cloud run failed'))

            return create_success_response(request, {
                'message': 'Run agent task in cloud successful',
                'run_status': result.get('data')
            })

        # Local execution
        runner = getattr(agent, 'runner', None)
        if not runner:
            return create_error_response(request, 'RUN_TASK_ERROR', 'Agent runner not available')

        thread_pool = getattr(agent, 'thread_pool_executor', None) or getattr(ctx.main_window, 'threadPoolExecutor', None)
        if not thread_pool:
            return create_error_response(request, 'RUN_TASK_ERROR', 'Thread pool executor not available')

        future = thread_pool.submit(runner.launch_unified_run, task_obj, task_obj.trigger or ['message'])
        if hasattr(agent, 'active_tasks') and hasattr(agent, 'task_lock') and getattr(task_obj, 'run_id', None):
            with agent.task_lock:
                agent.active_tasks[task_obj.run_id] = future

        return create_success_response(request, {
            'message': 'Run agent task successful',
            'task_id': task_id
        })

    except Exception as e:
        logger.error(f"Error in run agent task handler: {e} {traceback.format_exc()}")
        return create_error_response(
            request,
            'RUN_TASK_ERROR',
            f"Error during run agent task: {str(e)}"
        )

@IPCHandlerRegistry.handler('get_agent_tasks')
def handle_get_agent_tasks(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Get agent tasks list from database

    Reads agent tasks from database to ensure all fields (including 'source') are available.
    Falls back to memory if database is not available.

    Args:
        request: IPC request object
        params: Request parameters, can contain 'username', 'owner', or 'userId' field

    Returns:
        JSON formatted response message
    """
    try:
        logger.debug(f"Get agent tasks handler called with request: {request}")

        # Resolve username from params (supports username, owner, userId) or MainWindow context
        username = resolve_username(request, params)
        if not username:
            logger.warning(f"Invalid parameters for get agent tasks: Missing username")
            return create_error_response(
                request,
                'INVALID_PARAMS',
                'Missing required parameter: username (or owner/userId)'
            )

        logger.info(f"Getting agent tasks for user: {username}")

        # Get tasks from BOTH sources and merge them:
        # 1. Code-generated tasks from memory (source='code')
        # 2. UI-created tasks from SQLite database (source='ui')
        try:
            from gui.ipc.context_bridge import get_handler_context
            ctx = get_handler_context(request, params)
            memory_agent_tasks = ctx.get_agent_tasks() if ctx else []
            logger.info(f"Found {len(memory_agent_tasks)} agent tasks in memory (code-generated)")
            
            # Also load tasks from database (UI-created tasks)
            db_tasks = []
            agent_task_service = _get_agent_task_service(request, params)
            if agent_task_service:
                db_result = agent_task_service.query_tasks()
                if db_result.get('success') and db_result.get('data'):
                    db_tasks = db_result['data']
                    logger.info(f"[get_agent_tasks] Loaded {len(db_tasks)} tasks from database (UI-created)")
                else:
                    logger.warning(f"[get_agent_tasks] Failed to load from database: {db_result.get('error')}")
            else:
                logger.warning("[get_agent_tasks] Task service not available")
            
            # Build a set of IDs from database tasks to avoid duplicates
            db_task_ids = {t.get('id') for t in db_tasks if t.get('id')}

            # Convert tasks to dictionary format
            agent_tasks_dicts = []
            for i, agent_task in enumerate(memory_agent_tasks):
                try:
                    # Use Pydantic's model_dump() for proper serialization
                    if hasattr(agent_task, 'model_dump'):
                        # Pydantic v2: model_dump() with exclude for non-serializable fields
                        agent_task_dict = agent_task.model_dump(
                            exclude=TASK_SERIALIZATION_EXCLUDE,
                            mode='json',
                            exclude_none=True
                        )
                    elif hasattr(agent_task, 'dict'):
                        # Pydantic v1: dict() method
                        agent_task_dict = agent_task.dict(
                            exclude=TASK_SERIALIZATION_EXCLUDE,
                            exclude_none=True
                        )
                    else:
                        # ❌ Error: agent_task should be a Pydantic model
                        logger.error(f"Agent task {i} is not a Pydantic model! Type: {type(agent_task)}, Name: {getattr(agent_task, 'name', 'UNKNOWN')}")
                        logger.error(f"This indicates a serious data structure issue. Skipping this task.")
                        continue
                    
                    # Manually extract skill name (handle both string and object)
                    skill_value = getattr(agent_task, 'skill', None)
                    
                    if isinstance(skill_value, str):
                        agent_task_dict['skill'] = skill_value
                    elif skill_value and hasattr(skill_value, 'name'):
                        agent_task_dict['skill'] = skill_value.name
                    else:
                        agent_task_dict['skill'] = ''
                    
                    # Ensure owner field is set
                    agent_task_dict['owner'] = username
                    if 'id' not in agent_task_dict:
                        agent_task_dict['id'] = f"agent_task_{i}"
                    
                    # Serialize status properly
                    if 'status' in agent_task_dict:
                        agent_task_dict['status'] = _serialize_task_status(agent_task_dict['status'])
                    
                    agent_tasks_dicts.append(agent_task_dict)
                    logger.debug(f"Converted agent task: {agent_task_dict.get('name', 'NO NAME')}, source: {agent_task_dict.get('source', 'N/A')}, metadata: {agent_task_dict.get('metadata', 'N/A')}")
                except Exception as e:
                    logger.error(f"Failed to convert agent task {i}: {e}")
                    import traceback
                    logger.error(f"Traceback: {traceback.format_exc()}")
                    # Skip this task instead of crashing the entire request
                    continue

            # Attach skill_ids to memory tasks (association is purely ID-based)
            for mem_task in agent_tasks_dicts:
                mem_task_id = mem_task.get('id')
                if mem_task_id and not mem_task.get('skill_ids'):
                    try:
                        skill_rels = agent_task_service.get_task_skills(mem_task_id, role='primary') if agent_task_service else {}
                        if skill_rels.get('success') and skill_rels.get('data'):
                            skill_ids = [rel.get('skill_id') for rel in skill_rels['data'] if rel.get('skill_id')]
                            if skill_ids:
                                mem_task['skill_ids'] = skill_ids
                                logger.debug(f"[get_agent_tasks] Attached skill_ids={skill_ids} to memory task {mem_task_id}")
                    except Exception as e:
                        logger.warning(f"[get_agent_tasks] Failed to attach skills to memory task {mem_task_id}: {e}")

            # Attach skill_ids to DB tasks (association is purely ID-based)
            for db_task in db_tasks:
                db_task_id = db_task.get('id')
                if db_task_id and not db_task.get('skill_ids'):
                    try:
                        skill_rels = agent_task_service.get_task_skills(db_task_id, role='primary') if agent_task_service else {}
                        if skill_rels.get('success') and skill_rels.get('data'):
                            # Skill association is ID-based; name resolution is done by frontend
                            skill_ids = [rel.get('skill_id') for rel in skill_rels['data'] if rel.get('skill_id')]
                            if skill_ids:
                                db_task['skill_ids'] = skill_ids
                                logger.debug(f"[get_agent_tasks] Attached skill_ids={skill_ids} to DB task {db_task_id}")
                    except Exception as e:
                        logger.warning(f"[get_agent_tasks] Failed to attach skills to task {db_task_id}: {e}")

            # Merge: prefer DB task payload for duplicate IDs.
            # Rationale: runtime memory task objects may carry stale skill_ids; DB relation is source-of-truth.
            merged_by_id: Dict[str, Dict[str, Any]] = {}
            ordered_ids = []

            for mem_task in agent_tasks_dicts:
                tid = mem_task.get('id')
                if not tid:
                    continue
                merged_by_id[tid] = mem_task
                ordered_ids.append(tid)

            replaced_from_db = 0
            added_from_db = 0
            for db_task in db_tasks:
                db_task_id = db_task.get('id')
                if not db_task_id:
                    continue
                if db_task_id in merged_by_id:
                    replaced_from_db += 1
                else:
                    ordered_ids.append(db_task_id)
                    added_from_db += 1
                merged_by_id[db_task_id] = db_task

            # Keep deterministic order while applying DB overrides
            agent_tasks_dicts = [merged_by_id[tid] for tid in ordered_ids if tid in merged_by_id]
            logger.info(
                f"[get_agent_tasks] Merge result: replaced_from_db={replaced_from_db}, "
                f"added_from_db={added_from_db}, total={len(agent_tasks_dicts)}"
            )
            
            logger.info(f"Returning {len(agent_tasks_dicts)} agent tasks to frontend (memory: {len(memory_agent_tasks)}, db: {len(db_tasks)})")

            resultJS = {
                'tasks': agent_tasks_dicts,
                'message': 'Get agent tasks successful',
            }
            return create_success_response(request, resultJS)

        except Exception as e:
            import traceback as tb
            logger.error(f"Failed to get agent tasks from memory: {e}")
            logger.error(f"Traceback: {tb.format_exc()}")
            # Return empty list as fallback
            return create_success_response(request, {
                'tasks': [],
                'message': 'No agent tasks available',
            })

    except Exception as e:
        import traceback as tb
        logger.error(f"Error in get agent tasks handler: {e} {tb.format_exc()}")
        return create_error_response(
            request,
            'GET_TASKS_ERROR',
            f"Error during get agent tasks: {str(e)}"
        )
    
@IPCHandlerRegistry.handler('save_agent_task')
def handle_save_agent_task(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Handle saving agent task to local database

    Args:
        request: IPC request object
        params: Request parameters, must contain 'username' and 'task_info' fields

    Returns:
        JSON formatted response message
    """
    try:
        logger.debug(f"Save task handler called with request: {request}")

        # Resolve username from params (supports username, owner, userId)
        username = resolve_username(request, params)
        if not username:
            logger.warning(f"Invalid parameters for save task: Missing username")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: username (or owner/userId)')

        # Validate task_info parameter (also accept 'input' from GraphQL mutations)
        agent_task_info = None
        if params:
            agent_task_info = params.get('task_info') or params.get('input')
        # GraphQL mutations send input as an array — unwrap single-element lists
        if isinstance(agent_task_info, list):
            if len(agent_task_info) == 1:
                agent_task_info = agent_task_info[0]
            elif len(agent_task_info) == 0:
                agent_task_info = None
        if not agent_task_info:
            logger.warning(f"Invalid parameters for save task: Missing task_info")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: task_info')

        agent_task_id = agent_task_info.get('id') if isinstance(agent_task_info, dict) else None
        

        if not agent_task_id:
            return create_error_response(request, 'INVALID_PARAMS', 'Agent task ID is required for save operation')

        # ⚠️ Prevent saving code-generated tasks to database
        task_source = agent_task_info.get('source', 'ui')
        if task_source == 'code':
            logger.warning(f"Blocked attempt to save code-generated task '{agent_task_info.get('name')}' to database")
            return create_error_response(
                request, 
                'INVALID_OPERATION', 
                'Cannot save code-generated tasks to database. Code-generated tasks are read-only.'
            )

        logger.info(f"Saving agent task for user: {username}, agent_task_id: {agent_task_id}")

        # Get database service
        agent_task_service = _get_agent_task_service(request, params)
        if not agent_task_service:
            return create_error_response(request, 'SERVICE_ERROR', 'Database service not available')

        skill_ids = agent_task_info.get('skill_ids', []) if isinstance(agent_task_info, dict) else []
        if not skill_ids:
            single_id = agent_task_info.get('skill_id') if isinstance(agent_task_info, dict) else None
            skill_ids = [single_id] if single_id else []

        skill_binding_changed = _skill_binding_changed(agent_task_id, skill_ids, request=request, params=params) if agent_task_id else False

        # Prepare agent task data
        agent_task_data = _prepare_agent_task_data(agent_task_info, username, agent_task_id)
        if skill_binding_changed:
            agent_task_data['settings'] = _clear_skill_runtime_markers(agent_task_data.get('settings', {}))
            logger.info(f"[task_handler] Reset runtime state due to skill change: task_id={agent_task_id}, skill_ids={skill_ids}")

        # Check if agent task exists
        existing_agent_task = agent_task_service.query_tasks(id=agent_task_id)

        if existing_agent_task.get('success') and existing_agent_task.get('data'):
            # Update existing agent task
            existing_data = existing_agent_task.get('data', [{}])[0] if existing_agent_task.get('data') else {}
            logger.info(f"[task_handler] Existing task metadata before update: {existing_data.get('metadata', existing_data.get('settings', {}))}")
            logger.info(f"Updating existing agent task: {agent_task_id}")
            result = agent_task_service.update_task(agent_task_id, agent_task_data)
            logger.info(f"[task_handler] Update result: {result}")
        else:
            # Create new agent task
            logger.info(f"Creating new agent task: {agent_task_id}")
            result = agent_task_service.add_task(agent_task_data)

        if result.get('success'):
            # Get the actual agent_task_id from database response (in case it was generated)
            actual_agent_task_id = result.get('id', agent_task_id)
            logger.info(f"Agent task saved successfully: {agent_task_data['name']} (ID: {actual_agent_task_id})")

            # Step 1.5: Manage task-skill relationships (supports multiple skills)
            # Batch process: clear existing and add all new ones
            logger.debug(f"[task_handler] Managing skill relationships: task_id={actual_agent_task_id}, skill_ids={skill_ids}")
            _manage_task_skill_relationships(actual_agent_task_id, skill_ids, request=request, params=params)

            # Step 2: Update memory after database update succeeds
            _update_agent_task_in_memory(actual_agent_task_id, agent_task_data)
            _sync_runtime_task_skill(actual_agent_task_id, request=request, params=params, preferred_skill_ids=skill_ids)

            # Step 3: Clean up offline sync queue for this task (remove pending add/update operations)
            try:
                from agent.cloud_api.offline_sync_queue import get_offline_sync_queue
                sync_queue = get_offline_sync_queue()
                # Remove any pending add operations (they're now redundant since we're updating)
                removed_add = sync_queue.remove_tasks_by_resource('task', actual_agent_task_id, operation='add')
                # Remove any pending update operations (they're now redundant since we have a new update)
                removed_update = sync_queue.remove_tasks_by_resource('task', actual_agent_task_id, operation='update')
                if removed_add + removed_update > 0:
                    logger.info(f"[task_handler] Removed {removed_add + removed_update} pending sync tasks for task: {actual_agent_task_id}")
            except Exception as e:
                logger.warning(f"[task_handler] Failed to clean offline sync queue: {e}")

            # Step 4: Sync to cloud after memory update succeeds (async, fire and forget)
            task_data_with_id = agent_task_data.copy()
            task_data_with_id['id'] = actual_agent_task_id
            
            # Sync Task entity
            _trigger_cloud_sync(task_data_with_id, Operation.UPDATE)
            
            # Sync Task-Skill relationships (use skill_ids extracted earlier from agent_task_info).
            # Always use ADD — cloud resolver handles upsert. UPDATE requires the cloud-side
            # auto-generated relation row 'id' which the local client doesn't have.
            if skill_ids:
                _sync_task_skill_relations(actual_agent_task_id, skill_ids, Operation.ADD)

            # Create clean response
            clean_agent_task_data = _create_clean_agent_task_response(actual_agent_task_id, agent_task_data)

            return create_success_response(request, {
                'message': 'Save agent task successful',
                'task_id': actual_agent_task_id,
                'data': clean_agent_task_data
            })
        else:
            logger.error(f"Failed to save agent task: {result.get('error')}")
            return create_error_response(
                request,
                'SAVE_TASK_ERROR',
                f"Failed to save agent task: {result.get('error')}"
            )

    except Exception as e:
        logger.error(f"Error in save task handler: {e} {traceback.format_exc()}")
        return create_error_response(
            request,
            'SAVE_TASK_ERROR',
            f"Error during save task: {str(e)}"
        )


@IPCHandlerRegistry.handler('new_agent_task')
def handle_new_agent_task(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Handle creating new agent task and saving to local database

    Args:
        request: IPC request object
        params: Request parameters, must contain 'username' and 'task_info' fields

    Returns:
        JSON formatted response message
    """
    try:
        logger.debug(f"Create new task handler called with request: {request}")

        # Resolve username from params (supports username, owner, userId)
        username = resolve_username(request, params)
        if not username:
            logger.warning(f"Invalid parameters for create task: Missing username")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: username (or owner/userId)')

        # Validate task_info parameter (also accept 'input' from GraphQL mutations)
        agent_task_info = None
        if params:
            agent_task_info = params.get('task_info') or params.get('input')
        # GraphQL mutations send input as an array — unwrap single-element lists
        if isinstance(agent_task_info, list):
            if len(agent_task_info) == 1:
                agent_task_info = agent_task_info[0]
            elif len(agent_task_info) == 0:
                agent_task_info = None
        if not agent_task_info:
            logger.warning(f"Invalid parameters for create task: Missing task_info")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: task_info')

        logger.info(f"Creating new agent task for user: {username}")

        # Get database service
        agent_task_service = _get_agent_task_service(request, params)
        if not agent_task_service:
            return create_error_response(request, 'SERVICE_ERROR', 'Database service not available')

        # Prepare agent task data (without ID - let database generate it)
        agent_task_data = _prepare_agent_task_data(agent_task_info, username, agent_task_id=None)

        # Create new agent task in database
        logger.info(f"Creating new agent task: {agent_task_data['name']}")
        result = agent_task_service.add_task(agent_task_data)

        if result.get('success'):
            # Get the database-generated agent task ID
            agent_task_id = result.get('id')
            if not agent_task_id:
                logger.error("Database did not return agent task ID after creation")
                return create_error_response(
                    request,
                    'CREATE_TASK_ERROR',
                    'Database did not return agent task ID'
                )

            logger.info(f"Agent task created successfully: {agent_task_data['name']} (ID: {agent_task_id})")

            # Step 1.5: Manage task-skill relationships (supports multiple skills)
            skill_ids = agent_task_info.get('skill_ids', [])
            if not skill_ids:
                single_id = agent_task_info.get('skill_id')
                skill_ids = [single_id] if single_id else []
            # Batch process: clear existing and add all new ones
            _manage_task_skill_relationships(agent_task_id, skill_ids, request=request, params=params)

            # Step 2: Update memory after database creation succeeds
            _update_agent_task_in_memory(agent_task_id, agent_task_data)
            _sync_runtime_task_skill(agent_task_id, request=request, params=params, preferred_skill_ids=skill_ids)

            # Step 3: Sync to cloud after memory update succeeds (async, fire and forget)
            task_data_with_id = agent_task_data.copy()
            task_data_with_id['id'] = agent_task_id
            
            # Sync Task entity
            _trigger_cloud_sync(task_data_with_id, Operation.ADD)
            
            # Sync Task-Skill relationships
            if skill_ids:
                _sync_task_skill_relations(agent_task_id, skill_ids, Operation.ADD)

            # Create clean response
            clean_agent_task_data = _create_clean_agent_task_response(agent_task_id, agent_task_data)

            return create_success_response(request, {
                'message': 'Create agent task successful',
                'task_id': agent_task_id,
                'data': clean_agent_task_data
            })
        else:
            logger.error(f"Failed to create agent task: {result.get('error')}")
            return create_error_response(
                request,
                'CREATE_TASK_ERROR',
                f"Failed to create agent task: {result.get('error')}"
            )

    except Exception as e:
        logger.error(f"Error in create task handler: {e} {traceback.format_exc()}")
        return create_error_response(
            request,
            'CREATE_TASK_ERROR',
            f"Error during create task: {str(e)}"
        )


@IPCHandlerRegistry.handler('delete_agent_task')
def handle_delete_agent_task(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Handle deleting agent task from database and memory

    Args:
        request: IPC request object
        params: Request parameters, must contain 'username' and 'task_id' fields

    Returns:
        JSON formatted response message
    """
    try:
        logger.debug(f"Delete task handler called with request: {request}")

        # Resolve username from params (supports username, owner, userId)
        username = resolve_username(request, params)
        if not username:
            logger.warning(f"Invalid parameters for delete task: Missing username")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: username (or owner/userId)')

        # Validate task_id parameter (also accept 'input' from GraphQL mutations)
        agent_task_id = None
        if params:
            agent_task_id = params.get('task_id')
            if not agent_task_id:
                # GraphQL mutations send input as an array of IDs
                input_val = params.get('input')
                if isinstance(input_val, list) and len(input_val) == 1:
                    agent_task_id = input_val[0]
                elif isinstance(input_val, str):
                    agent_task_id = input_val
        if not agent_task_id:
            logger.warning(f"Invalid parameters for delete task: Missing task_id")
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: task_id')

        # ⚠️ Prevent deleting code-generated tasks from database
        # First check if this is a code-generated task by checking memory
        from gui.ipc.context_bridge import get_handler_context
        ctx = get_handler_context(request, params)
        if ctx:
            agent_tasks_list = ctx.get_agent_tasks() or []
            existing_task = next((t for t in agent_tasks_list if getattr(t, 'id', None) == agent_task_id), None)
            if existing_task and getattr(existing_task, 'source', 'ui') == 'code':
                logger.warning(f"Blocked attempt to delete code-generated task '{getattr(existing_task, 'name', 'Unknown')}' from database")
                return create_error_response(
                    request,
                    'INVALID_OPERATION',
                    'Cannot delete code-generated tasks. Code-generated tasks are read-only.'
                )

        logger.info(f"Deleting agent task for user: {username}, agent_task_id: {agent_task_id}")

        # Get database service
        agent_task_service = _get_agent_task_service(request, params)
        if not agent_task_service:
            return create_error_response(request, 'SERVICE_ERROR', 'Database service not available')

        # Step 1: Delete from database first
        result = agent_task_service.delete_task(agent_task_id)

        if result.get('success'):
            logger.info(f"Agent task deleted successfully from database: {agent_task_id}")

            # Step 2: Remove from memory after database deletion succeeds
            try:
                if ctx:
                    agent_tasks_list = ctx.get_agent_tasks()
                    if agent_tasks_list is not None:
                        original_count = len(agent_tasks_list)
                        # Filter out the deleted task - modify in place
                        agent_tasks_list[:] = [
                            agent_task for agent_task in agent_tasks_list
                            if not (hasattr(agent_task, 'id') and agent_task.id == agent_task_id)
                        ]
                        new_count = len(agent_tasks_list)
                        logger.info(f"[task_handler] Removed agent task from memory: {agent_task_id} (count: {original_count} → {new_count})")
            except Exception as e:
                logger.warning(f"[task_handler] Failed to remove agent task from memory: {e}")

            # Step 3: Clean up offline sync queue for this task
            try:
                from agent.cloud_api.offline_sync_queue import get_offline_sync_queue
                sync_queue = get_offline_sync_queue()
                removed_count = sync_queue.remove_tasks_by_resource('task', agent_task_id)
                if removed_count > 0:
                    logger.info(f"[task_handler] Removed {removed_count} pending sync tasks for task: {agent_task_id}")
            except Exception as e:
                logger.warning(f"[task_handler] Failed to clean offline sync queue: {e}")

            # Step 4: Sync deletion to cloud after memory update (async, fire and forget)
            delete_task_data = {
                'id': agent_task_id,
                'owner': username,
                'name': f"Task_{agent_task_id}"  # Placeholder name for deletion
            }
            _trigger_cloud_sync(delete_task_data, Operation.DELETE)

            return create_success_response(request, {
                'message': 'Delete agent task successful',
                'task_id': agent_task_id
            })
        else:
            logger.error(f"Failed to delete agent task: {result.get('error')}")
            return create_error_response(
                request,
                'DELETE_TASK_ERROR',
                f"Failed to delete agent task: {result.get('error')}"
            )

    except Exception as e:
        logger.error(f"Error in delete task handler: {e} {traceback.format_exc()}")
        return create_error_response(
            request,
            'DELETE_TASK_ERROR',
            f"Error during delete task: {str(e)}"
        )


# ============================================================================
# Cloud Task Run ID Query
# ============================================================================


@IPCHandlerRegistry.handler('query_cloud_task_run_id')
def handle_query_cloud_task_run_id(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Query the cloud task's runID for hybrid cloud execution.

    The runID is needed so the local helper task can subscribe to
    onPassiveCommand with matching clientID + runID.

    Args:
        request: IPC request object
        params: Must contain 'task_id' and optionally 'meta_data'

    Returns:
        JSON response with {id, runID, runner, status, success, error, timestamp}
    """
    try:
        task_id = (params or {}).get('task_id')
        meta_data = (params or {}).get('meta_data', {})

        if not task_id:
            return create_error_response(request, 'INVALID_PARAMS', 'Missing required parameter: task_id')

        logger.info(f"[task_handler] query_cloud_task_run_id: task_id={task_id}")

        # Try to find the runID from the in-memory task first
        from gui.ipc.context_bridge import get_handler_context
        ctx = get_handler_context(request, params)
        if ctx:
            agent_tasks = ctx.get_agent_tasks() or []
            for t in agent_tasks:
                if getattr(t, 'id', None) == task_id:
                    run_id = getattr(t, 'run_id', None)
                    if run_id:
                        logger.info(f"[task_handler] Found runID from memory: {run_id}")
                        return create_success_response(request, {
                            'id': task_id,
                            'runID': run_id,
                            'runner': getattr(t, 'owner', ''),
                            'status': json.dumps({'state': _serialize_task_status(getattr(t, 'status', 'pending'))}),
                            'success': True,
                            'error': None,
                        })

        # Fallback: check local DB task metadata/config for run_id
        task_service = _get_agent_task_service(request, params)
        if task_service:
            result = task_service.query_tasks(id=task_id)
            if result.get('success') and result.get('data'):
                task_data = result['data'][0] if result['data'] else {}
                settings = task_data.get('settings', task_data.get('metadata', {}))
                if isinstance(settings, str):
                    try:
                        settings = json.loads(settings)
                    except Exception:
                        settings = {}
                run_id = (settings or {}).get('run_id') or (settings or {}).get('runID')
                if run_id:
                    logger.info(f"[task_handler] Found runID from DB: {run_id}")
                    return create_success_response(request, {
                        'id': task_id,
                        'runID': run_id,
                        'runner': task_data.get('owner', ''),
                        'status': json.dumps({'state': task_data.get('status', 'pending')}),
                        'success': True,
                        'error': None,
                    })

        logger.warning(f"[task_handler] No runID found for task: {task_id}")
        return create_success_response(request, {
            'id': task_id,
            'runID': None,
            'runner': None,
            'status': json.dumps({'state': 'not_found'}),
            'success': False,
            'error': 'Task runID not found',
        })

    except Exception as e:
        logger.error(f"[task_handler] query_cloud_task_run_id error: {e} {traceback.format_exc()}")
        return create_error_response(request, 'QUERY_RUN_ID_ERROR', str(e))


# ============================================================================
# Hybrid Cloud Task Helper
# ============================================================================


@IPCHandlerRegistry.handler('setup_local_helper_task')
def handle_setup_local_helper_task(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Set up a local helper task for hybrid cloud execution: create a local
    helper task in SQLite with the same task ID as the cloud task, and start
    the onPassiveCommand WebSocket subscription with matching clientID + runID.
    
    NOTE: In normal operation, the agent scheduler in runner.py handles this
    automatically. This IPC handler is for manual/diagnostic triggering.

    Args:
        request: IPC request object
        params: Must contain:
            - cloud_task_id: The cloud task ID (local helper uses same ID)
            - skill_id: The local helper skill ID
            - run_id: The cloud task's runID (from queryCloudTaskRunId)
            - username: Owner

    Returns:
        JSON response with helper task info
    """
    try:
        if not params:
            return create_error_response(request, 'INVALID_PARAMS', 'Missing parameters')

        cloud_task_id = params.get('cloud_task_id')
        skill_id = params.get('skill_id')
        run_id = params.get('run_id')
        username = resolve_username(request, params)

        if not cloud_task_id:
            return create_error_response(request, 'INVALID_PARAMS', 'Missing cloud_task_id')
        if not skill_id:
            return create_error_response(request, 'INVALID_PARAMS', 'Missing skill_id (local helper skill)')
        if not run_id:
            return create_error_response(request, 'INVALID_PARAMS', 'Missing run_id')
        if not username:
            return create_error_response(request, 'INVALID_PARAMS', 'Missing username')

        logger.info(f"[HybridTask] Setting up hybrid cloud task: cloud_task_id={cloud_task_id}, "
                     f"skill_id={skill_id}, run_id={run_id}, user={username}")

        # Step 1: Create or update local helper task in SQLite with same ID as cloud task
        task_service = _get_agent_task_service(request, params)
        if not task_service:
            return create_error_response(request, 'SERVICE_ERROR', 'Database service not available')

        helper_task_data = {
            'id': cloud_task_id,  # Same ID as cloud task
            'name': f"hybrid_helper_{cloud_task_id[:8]}",
            'owner': username,
            'description': f"Local helper task for hybrid cloud execution (skill: {skill_id})",
            'source': 'hybrid_cloud',
            'status': 'pending',
            'task_type': 'hybrid_helper',
            'trigger': 'hybrid_cloud',
            'settings': {
                'run_id': run_id,
                'cloud_task_id': cloud_task_id,
                'local_helper_skill_id': skill_id,
                'is_helper_task': True,
            },
        }

        # Check if task already exists
        existing = task_service.query_tasks(id=cloud_task_id)
        if existing.get('success') and existing.get('data'):
            logger.info(f"[HybridTask] Updating existing local helper task: {cloud_task_id}")
            task_service.update_task(cloud_task_id, helper_task_data)
        else:
            logger.info(f"[HybridTask] Creating new local helper task: {cloud_task_id}")
            task_service.add_task(helper_task_data)

        # Step 2: Get client_id (acctSiteID) for the subscription
        from gui.ipc.context_bridge import get_handler_context
        ctx = get_handler_context(request, params)
        client_id = None
        if ctx and ctx.main_window:
            client_id = getattr(ctx.main_window, 'getAcctSiteID', lambda: None)()
        if not client_id:
            client_id = f"client-{cloud_task_id[:10]}"

        logger.info(f"[HybridTask] client_id={client_id}, run_id={run_id}")

        # Step 3: Start the local helper skill as a ManagedTask and subscribe to onPassiveCommand
        helper_result = _start_hybrid_helper_task(ctx, cloud_task_id, skill_id, run_id, client_id)

        if not helper_result.get('success'):
            logger.error(f"[HybridTask] Failed to start helper: {helper_result.get('error')}")
            return create_error_response(request, 'HYBRID_TASK_ERROR', helper_result.get('error', 'Unknown error'))

        # Step 4: Subscribe to onPassiveCommand for this run
        _start_passive_command_subscription(ctx, client_id, run_id)

        return create_success_response(request, {
            'message': 'Hybrid cloud task set up successfully',
            'cloud_task_id': cloud_task_id,
            'run_id': run_id,
            'client_id': client_id,
            'helper_skill_id': skill_id,
            'helper_task_started': helper_result.get('success', False),
        })

    except Exception as e:
        logger.error(f"[HybridTask] Error: {e} {traceback.format_exc()}")
        return create_error_response(request, 'HYBRID_TASK_ERROR', str(e))


def _start_hybrid_helper_task(ctx, task_id: str, skill_id: str, run_id: str, client_id: str) -> Dict[str, Any]:
    """Start a local helper skill as a ManagedTask for hybrid cloud execution.

    Args:
        ctx: Handler context
        task_id: Task ID (same as cloud task)
        skill_id: Local helper skill ID
        run_id: Cloud task's runID
        client_id: Client ID for passive command subscription

    Returns:
        dict with success, error
    """
    import uuid

    try:
        if not ctx or not ctx.main_window:
            return {"success": False, "error": "No main window available"}

        main_window = ctx.main_window
        agents = getattr(main_window, 'agents', [])
        if not agents:
            return {"success": False, "error": "No agents available"}

        agent = agents[0]

        # Find the skill
        skills = getattr(agent, 'skills', []) or getattr(main_window, 'agent_skills', []) or []
        target_skill = None
        for skill in skills:
            if getattr(skill, 'id', '') == skill_id or getattr(skill, 'name', '') == skill_id:
                target_skill = skill
                break

        if not target_skill:
            available = [f"{getattr(s, 'id', '?')}:{getattr(s, 'name', '?')}" for s in skills[:10]]
            return {"success": False, "error": f"Skill '{skill_id}' not found. Available: {available}"}

        skill_name = getattr(target_skill, 'name', skill_id)

        # Create ManagedTask
        from agent.ec_tasks import ManagedTask

        task_state = {
            "is_helper_skill": True,
            "parent_cloud_task_id": task_id,
            "client_id": client_id,
            "run_id": run_id,
        }
        new_task = ManagedTask(
            id=task_id,
            context_id=task_id,
            run_id=run_id,
            name=f"{skill_name}_helper_{task_id[:8]}",
            description=f"Hybrid cloud helper for task {task_id}",
            skill=target_skill,
            trigger="hybrid_cloud",
            cloud_based=True,
            metadata={"state": task_state},
            state=task_state,
            sessionId="",
        )

        # Add to agent tasks
        if not hasattr(agent, 'tasks') or agent.tasks is None:
            agent.tasks = []
        agent.tasks.append(new_task)

        # Start via runner
        runner = getattr(agent, 'runner', None)
        if runner:
            from concurrent.futures import ThreadPoolExecutor
            thread_pool = getattr(agent, 'thread_pool_executor', None)
            if not thread_pool:
                thread_pool = ThreadPoolExecutor(max_workers=4)
                agent.thread_pool_executor = thread_pool

            future = thread_pool.submit(runner.launch_unified_run, new_task, "hybrid_cloud")

            if hasattr(agent, 'active_tasks') and hasattr(agent, 'task_lock'):
                with agent.task_lock:
                    agent.active_tasks[run_id] = future

            logger.info(f"[HybridTask] Helper task submitted: id={task_id}, run_id={run_id}, skill={skill_name}")
        else:
            logger.warning(f"[HybridTask] No runner, task created but not started")

        return {"success": True}

    except Exception as e:
        logger.error(f"[HybridTask] _start_hybrid_helper_task error: {e} {traceback.format_exc()}")
        return {"success": False, "error": str(e)}


def _start_passive_command_subscription(ctx, client_id: str, run_id: str) -> None:
    """Start onPassiveCommand WebSocket subscription for hybrid cloud execution.

    Args:
        ctx: Handler context with main_window
        client_id: Client ID for the subscription
        run_id: Run ID for the subscription
    """
    try:
        if not ctx or not ctx.main_window:
            logger.warning("[HybridTask] No main_window, cannot start passive subscription")
            return

        main_window = ctx.main_window
        token = main_window.get_auth_token()
        if not token:
            logger.warning("[HybridTask] No auth token, skipping passive subscription")
            return

        from agent.ec_skills.browser_use_extension.passive_command_service import PassiveCommandService
        from agent.ec_skills.browser_use_extension.appsync_passive_client import (
            AppSyncPassiveClientConfig,
            _derive_realtime_endpoint,
            _derive_api_host,
        )

        http_endpoint = main_window.getWanApiEndpoint()
        ws_endpoint = main_window.getWSApiEndpoint() or _derive_realtime_endpoint(http_endpoint)
        api_host = main_window.getWSApiHost() or _derive_api_host(http_endpoint, ws_endpoint)

        config = AppSyncPassiveClientConfig(
            http_endpoint=http_endpoint,
            ws_endpoint=ws_endpoint,
            api_host=api_host,
            auth_token=token,
            run_id=run_id,
            client_id=client_id,
        )

        service = PassiveCommandService(
            config=config,
            route_command=main_window._route_passive_command_to_task,
        )

        import asyncio

        async def _start():
            await service.start()

        # Run in the main_window's event loop if available, else create one
        loop = getattr(main_window, '_async_loop', None)
        if loop and loop.is_running():
            asyncio.run_coroutine_threadsafe(_start(), loop)
        else:
            import threading
            def _run():
                asyncio.run(_start())
            t = threading.Thread(target=_run, daemon=True)
            t.start()

        logger.info(f"[HybridTask] Passive command subscription started: client_id={client_id}, run_id={run_id}")

    except Exception as e:
        logger.error(f"[HybridTask] Failed to start passive subscription: {e} {traceback.format_exc()}")


# ============================================================================
# Cloud Synchronization Functions
# ============================================================================


def _trigger_cloud_sync(task_data: Dict[str, Any], operation: 'Operation') -> None:
    """Trigger cloud synchronization (async, non-blocking)
    
    Async background execution, doesn't block UI operations, ensures eventual consistency.
    
    Args:
        task_data: Task data to sync
        operation: Operation type (Operation enum)
    """
    from agent.cloud_api.offline_sync_manager import get_sync_manager
    from agent.cloud_api.constants import DataType
    
    def _log_result(result: Dict[str, Any]):
        """Log sync result"""
        error_msg = result.get('error')
        if not error_msg:
            errors = result.get('errors')
            if isinstance(errors, list) and errors:
                error_msg = '; '.join([str(e) for e in errors if e])
        if result.get('synced'):
            logger.info(f"[task_handler] ✅ Task synced to cloud: {operation} - {task_data.get('name')}")
        elif result.get('cached'):
            logger.info(f"[task_handler] 💾 Task cached for later sync: {operation} - {task_data.get('name')}")
        else:
            logger.error(f"[task_handler] ❌ Failed to sync task: {error_msg or result}")
    
    # Use SyncManager's thread pool for async execution
    # Note: Use TASK for Task entity data (name, description, etc.)
    #       Use AGENT_TASK for Agent-Task relationship data (agid, task_id, owner)
    manager = get_sync_manager()
    manager.sync_to_cloud_async(DataType.TASK, task_data, operation, callback=_log_result)


def _sync_task_skill_relations(task_id: str, skill_ids: list, operation: 'Operation') -> None:
    """Sync Task-Skill relationships to cloud (async, non-blocking)
    
    Args:
        task_id: Task ID
        skill_ids: List of skill IDs
        operation: Operation type (ADD/UPDATE/DELETE)
    """
    if not skill_ids:
        return
    
    from agent.cloud_api.offline_sync_manager import get_sync_manager
    from agent.cloud_api.constants import DataType
    from gui.ipc.context_bridge import get_handler_context
    
    manager = get_sync_manager()
    ctx = get_handler_context()
    owner = ctx.get_username() if ctx else 'unknown'
    
    logger.info(f"[task_handler] Syncing {len(skill_ids)} skill relationships for task: {task_id}")
    
    for skill_id in skill_ids:
        relation_data = {
            'task_id': task_id,
            'skill_id': skill_id
        }
        
        def _log_result(result: Dict[str, Any]):
            error_msg = result.get('error')
            if not error_msg:
                errors = result.get('errors')
                if isinstance(errors, list) and errors:
                    error_msg = '; '.join([str(e) for e in errors if e])
            if result.get('synced'):
                logger.info(f"[task_handler] ✅ Skill relation synced: {skill_id}")
            elif result.get('cached'):
                logger.info(f"[task_handler] 💾 Skill relation cached: {skill_id}")
            else:
                logger.error(f"[task_handler] ❌ Failed to sync skill relation: {error_msg or result}")
        
        manager.sync_to_cloud_async(DataType.TASK_SKILL, relation_data, operation, callback=_log_result)


@IPCHandlerRegistry.handler('query_agent_task_skill_rels')
def handle_query_agent_task_skill_rels(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Query agent task-skill relationships.

    Queries local DB first (authoritative source for desktop mode).  Cloud API
    is queried as a supplement when an auth token is available.

    Args:
        request: IPC request object
        params: Request parameters.  Supported filter keys inside 'input':
                  task_id  – return relations for a specific task
                  limit    – max rows (default 500)
                  offset   – pagination offset (default 0)

    Returns:
        List of relation dicts, each containing at minimum task_id and skill_id.
    """
    try:
        logger.debug(f"Query agent task-skill relationships handler called")

        q_settings = params.get('input', {}) if params else {}
        if isinstance(q_settings, str):
            try:
                q_settings = json.loads(q_settings)
            except Exception:
                q_settings = {}

        task_id_filter = str(q_settings.get('task_id', '')).strip() if q_settings else ''
        limit = int(q_settings.get('limit', 500)) if q_settings else 500

        # ── Local DB (authoritative) ──────────────────────────────────────────
        task_service = _get_agent_task_service(request, params)
        local_rels = []
        if task_service:
            try:
                if task_id_filter:
                    result = task_service.get_task_skills(task_id_filter, role=None)
                    rows = result.get('data', []) if result.get('success') else []
                    for row in (rows or []):
                        local_rels.append({
                            'task_id': task_id_filter,
                            'skill_id': str(row.get('skill_id', '')),
                            'role': row.get('role', 'primary'),
                        })
                else:
                    # No specific task_id — fetch all via DB tasks list then their skills
                    all_tasks_result = task_service.query_tasks()
                    if all_tasks_result.get('success') and all_tasks_result.get('data'):
                        for t in (all_tasks_result['data'] or [])[:limit]:
                            tid = str(t.get('id', '')).strip()
                            if not tid:
                                continue
                            skill_result = task_service.get_task_skills(tid, role=None)
                            for row in (skill_result.get('data') or []):
                                local_rels.append({
                                    'task_id': tid,
                                    'skill_id': str(row.get('skill_id', '')),
                                    'role': row.get('role', 'primary'),
                                })
            except Exception as db_err:
                logger.warning(f"[query_agent_task_skill_rels] Local DB query failed: {db_err}")

        logger.info(f"[query_agent_task_skill_rels] Found {len(local_rels)} local relationships"
                    + (f" for task_id={task_id_filter}" if task_id_filter else ""))

        if local_rels:
            return create_success_response(request, local_rels)

        # ── Cloud fallback (only when no local results and token available) ───
        ctx = get_handler_context(request, params)
        token = ctx.get_auth_token() if ctx else None
        if not token:
            return create_success_response(request, [])

        try:
            from agent.cloud_api.cloud_api import (
                send_query_task_skill_relations_to_cloud,
                get_appsync_endpoint,
            )
            endpoint = get_appsync_endpoint()
            session = requests.Session()
            if not q_settings:
                username = resolve_username(request, params)
                q_settings = {'byowneruser': True}

            result = send_query_task_skill_relations_to_cloud(session, token, q_settings, endpoint)
            if isinstance(result, list):
                relationships = result
            elif isinstance(result, dict):
                if 'errorType' in result:
                    logger.warning(f"[query_agent_task_skill_rels] Cloud API error: {result.get('message')}")
                    return create_success_response(request, [])
                relationships = result.get('items', result.get('relationships', []))
            else:
                relationships = []
            logger.info(f"[query_agent_task_skill_rels] Cloud fallback: {len(relationships)} relationships")
            return create_success_response(request, relationships)
        except Exception as cloud_err:
            logger.warning(f"[query_agent_task_skill_rels] Cloud query failed: {cloud_err}")
            return create_success_response(request, [])

    except Exception as e:
        logger.error(f"Error in query agent task-skill relationships handler: {e}")
        import traceback
        logger.error(f"Traceback: {traceback.format_exc()}")
        return create_error_response(
            request,
            'QUERY_TASK_SKILL_RELS_ERROR',
            f"Error querying task-skill relationships: {str(e)}"
        )


@IPCHandlerRegistry.handler('add_agent_task_skill_rels')
def handle_add_agent_task_skill_rels(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Add task-skill relationships.

    Supports desktop/local mode via DB service and forwards to cloud as best effort
    when auth token is available.
    """
    try:
        logger.debug(f"Add agent task-skill relationships handler called with request: {request}")

        raw_input = params.get('input', []) if params else []
        if isinstance(raw_input, str):
            try:
                raw_input = json.loads(raw_input)
            except Exception:
                raw_input = []

        relations = raw_input if isinstance(raw_input, list) else []
        if not relations:
            return create_success_response(request, [])

        task_service = _get_agent_task_service(request, params)
        if not task_service:
            return create_error_response(request, 'SERVICE_ERROR', 'Database service not available')

        local_results = []
        for rel in relations:
            task_id = str((rel or {}).get('task_id', '')).strip()
            skill_id = str((rel or {}).get('skill_id', '')).strip()
            if not task_id or not skill_id:
                local_results.append({'success': False, 'error': 'Missing task_id or skill_id', 'data': rel})
                continue
            local_results.append(task_service.add_skill_to_task(
                task_id=task_id,
                skill_id=skill_id,
                role='primary',
                is_required=True,
            ))

        # Best-effort cloud forwarding (do not fail local success)
        cloud_result = None
        try:
            ctx = get_handler_context(request, params)
            token = ctx.get_auth_token() if ctx else None
            if token:
                from agent.cloud_api.cloud_api import send_add_task_skill_relations_to_cloud, get_appsync_endpoint
                endpoint = get_appsync_endpoint()
                session = requests.Session()
                cloud_result = send_add_task_skill_relations_to_cloud(session, relations, token, endpoint)
        except Exception as ce:
            logger.warning(f"[add_agent_task_skill_rels] Cloud forwarding failed: {ce}")

        return create_success_response(request, {
            'local': local_results,
            'cloud': cloud_result,
        })

    except Exception as e:
        logger.error(f"Error in add agent task-skill relationships handler: {e}")
        import traceback
        logger.error(f"Traceback: {traceback.format_exc()}")
        return create_error_response(
            request,
            'ADD_TASK_SKILL_RELS_ERROR',
            f"Error adding task-skill relationships: {str(e)}"
        )


@IPCHandlerRegistry.handler('remove_agent_task_skill_rels')
def handle_remove_agent_task_skill_rels(request: IPCRequest, params: Optional[Dict[str, Any]]) -> IPCResponse:
    """Remove task-skill relationships.

    Accepts either relation id objects ({id}) and/or explicit keys ({task_id, skill_id}).
    Local DB removal requires task_id + skill_id; id-only removals are cloud-only.
    """
    try:
        logger.debug(f"Remove agent task-skill relationships handler called with request: {request}")

        raw_input = params.get('input', []) if params else []
        if isinstance(raw_input, str):
            try:
                raw_input = json.loads(raw_input)
            except Exception:
                raw_input = []

        removes = raw_input if isinstance(raw_input, list) else []
        if not removes:
            return create_success_response(request, [])

        task_service = _get_agent_task_service(request, params)
        local_results = []
        if task_service:
            for item in removes:
                task_id = str((item or {}).get('task_id', '')).strip()
                skill_id = str((item or {}).get('skill_id', '')).strip()
                if task_id and skill_id:
                    local_results.append(task_service.remove_skill_from_task(task_id=task_id, skill_id=skill_id))
                else:
                    # id-only record is expected from cloud relation query; skip local deletion
                    local_results.append({'success': True, 'skipped_local': True, 'data': item})
        else:
            local_results = [{'success': False, 'error': 'Database service not available'}]

        # Best-effort cloud forwarding
        cloud_result = None
        try:
            ctx = get_handler_context(request, params)
            token = ctx.get_auth_token() if ctx else None
            if token:
                from agent.cloud_api.cloud_api import send_remove_task_skill_relations_to_cloud, get_appsync_endpoint
                endpoint = get_appsync_endpoint()
                session = requests.Session()
                cloud_result = send_remove_task_skill_relations_to_cloud(session, removes, token, endpoint)
        except Exception as ce:
            logger.warning(f"[remove_agent_task_skill_rels] Cloud forwarding failed: {ce}")

        return create_success_response(request, {
            'local': local_results,
            'cloud': cloud_result,
        })

    except Exception as e:
        logger.error(f"Error in remove agent task-skill relationships handler: {e}")
        import traceback
        logger.error(f"Traceback: {traceback.format_exc()}")
        return create_error_response(
            request,
            'REMOVE_TASK_SKILL_RELS_ERROR',
            f"Error removing task-skill relationships: {str(e)}"
        )
