name: 'Setup Node.js Environment'
description: 'Setup Node.js environment and install frontend dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  frontend-dir:
    description: 'Frontend directory path'
    required: false
    default: 'gui_v2'
  install-command:
    description: 'Install command to use'
    required: false
    default: 'npm install --legacy-peer-deps'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install frontend dependencies
      working-directory: ${{ inputs.frontend-dir }}
      shell: bash
      run: |
        echo "=== Installing Frontend Dependencies ==="
        
        # Check if we need to clean install (fix for rollup optional dependencies issue)
        NEEDS_CLEAN_INSTALL=false
        
        # Always clean install if node_modules doesn't exist
        if [ ! -d "node_modules" ] || [ -z "$(ls -A node_modules)" ]; then
          echo "node_modules not found, performing clean install..."
          NEEDS_CLEAN_INSTALL=true
        else
          # Check if critical rollup native binaries are missing
          ROLLUP_NATIVE="node_modules/rollup/dist/native.js"
          if [ -f "$ROLLUP_NATIVE" ]; then
            # Try to verify rollup can load its native module
            if ! node -e "require('rollup')" 2>/dev/null; then
              echo "Rollup native module check failed, performing clean install..."
              NEEDS_CLEAN_INSTALL=true
            else
              echo "node_modules exists and rollup check passed, skipping install."
            fi
          else
            echo "Rollup native module not found, performing clean install..."
            NEEDS_CLEAN_INSTALL=true
          fi
        fi
        
        # Perform clean install if needed (preserve package-lock.json so cache key remains stable)
        if [ "$NEEDS_CLEAN_INSTALL" = true ]; then
          echo "Cleaning node_modules (preserving package-lock.json)..."
          rm -rf node_modules
          echo "Installing dependencies with optional dependencies support..."
          ${{ inputs.install-command }}
          
          # Verify rollup installation
          echo "=== Verifying Rollup Installation ==="
          if node -e "require('rollup')" 2>/dev/null; then
            echo "✅ Rollup verification passed"
          else
            echo "⚠️  Rollup verification failed, attempting reinstall..."
            npm install rollup --force --legacy-peer-deps
          fi
        fi
