/**
 * A2UIFormCard - A2UI-based replacement for ClarificationCard
 * 
 * This component renders clarification questions using the A2UI protocol,
 * providing a richer, more dynamic form experience generated by the LLM.
 */

import React, { useCallback, useMemo } from 'react';
import styled from 'styled-components';
import { A2UISurface } from './A2UISurface';
import { clarificationToA2UI, extractAnswersFromA2UIAction } from './converter';
import type { ClarificationQuestion } from '../../../types/skill-editor-chat.types';
import type { A2UIServerMessage } from './types';

interface A2UIFormCardProps {
  /** 
   * Clarification questions to render
   * Will be converted to A2UI format if a2uiMessages is not provided 
   */
  questions?: ClarificationQuestion[];
  /**
   * Pre-generated A2UI messages from the LLM
   * If provided, these will be used directly instead of converting questions
   */
  a2uiMessages?: A2UIServerMessage[];
  /** Surface ID (required if a2uiMessages is provided) */
  surfaceId?: string;
  /** Callback when user submits answers */
  onSubmit?: (answers: Record<string, string[]>) => void;
  /** Callback when user cancels */
  onCancel?: () => void;
  /** Whether form is being submitted */
  isSubmitting?: boolean;
  /** Read-only mode - shows submitted answers */
  submittedAnswers?: Record<string, string[]>;
}

const CardContainer = styled.div<{ $readOnly?: boolean }>`
  background: rgba(30, 41, 59, 0.9);
  border: 1px solid ${props => props.$readOnly ? 'rgba(34, 197, 94, 0.3)' : 'rgba(59, 130, 246, 0.3)'};
  border-radius: 12px;
  padding: 16px;
  margin: 8px 0;
  overflow: hidden;
  
  /* Loading overlay */
  &.loading::after {
    content: '';
    position: absolute;
    inset: 0;
    background: rgba(15, 23, 42, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
  }
`;

const ReadOnlyHeader = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
  padding-bottom: 8px;
  border-bottom: 1px solid rgba(148, 163, 184, 0.2);
  
  span.icon {
    font-size: 16px;
  }
  
  span.title {
    font-size: 14px;
    font-weight: 600;
    color: #e2e8f0;
  }
`;

const ReadOnlyAnswer = styled.div`
  margin-bottom: 12px;
  
  .question {
    font-size: 13px;
    font-weight: 500;
    color: #e2e8f0;
    margin-bottom: 4px;
  }
  
  .answer {
    font-size: 12px;
    color: rgba(148, 163, 184, 0.9);
    padding-left: 12px;
    border-left: 2px solid rgba(34, 197, 94, 0.4);
  }
`;

/**
 * A2UIFormCard component
 * 
 * Renders clarification questions using A2UI protocol.
 * Can use either pre-generated A2UI messages or convert ClarificationQuestion array.
 */
export const A2UIFormCard: React.FC<A2UIFormCardProps> = ({
  questions,
  a2uiMessages,
  surfaceId: providedSurfaceId,
  onSubmit,
  onCancel,
  isSubmitting = false,
  submittedAnswers,
}) => {
  // Convert questions to A2UI if needed
  const { messages, surfaceId } = useMemo(() => {
    // If A2UI messages are provided, use them directly
    if (a2uiMessages && providedSurfaceId) {
      return { messages: a2uiMessages, surfaceId: providedSurfaceId };
    }
    
    // Convert questions to A2UI format
    if (questions && questions.length > 0) {
      const result = clarificationToA2UI(questions, providedSurfaceId);
      return { messages: result.messages, surfaceId: result.surfaceId };
    }
    
    return { messages: [], surfaceId: '' };
  }, [questions, a2uiMessages, providedSurfaceId]);

  // Handle A2UI actions
  const handleAction = useCallback((actionName: string, context: Record<string, unknown>) => {
    console.log('[A2UIFormCard] Action:', actionName, context);
    
    if (actionName === 'submit_clarification') {
      if (onSubmit) {
        const answers = extractAnswersFromA2UIAction(context);
        onSubmit(answers);
      }
    } else if (actionName === 'cancel_clarification') {
      if (onCancel) {
        onCancel();
      }
    }
  }, [onSubmit, onCancel]);

  // Read-only mode - show submitted answers
  if (submittedAnswers && questions) {
    return (
      <CardContainer $readOnly>
        <ReadOnlyHeader>
          <span className="icon">✅</span>
          <span className="title">Your answers to clarification questions:</span>
        </ReadOnlyHeader>
        {questions.map((q, index) => {
          const selectedIds = submittedAnswers[q.id] || [];
          const selectedLabels = q.choices
            .filter(c => selectedIds.includes(c.id))
            .map(c => c.label);
          
          return (
            <ReadOnlyAnswer key={q.id}>
              <div className="question">{index + 1}. {q.question}</div>
              <div className="answer">{selectedLabels.join(', ') || 'No answer'}</div>
            </ReadOnlyAnswer>
          );
        })}
      </CardContainer>
    );
  }

  // No content to render
  if (messages.length === 0) {
    console.warn('[A2UIFormCard] No messages to render');
    return null;
  }

  return (
    <CardContainer className={isSubmitting ? 'loading' : ''}>
      <A2UISurface
        messages={messages}
        surfaceId={surfaceId}
        onAction={handleAction}
        theme={{ primaryColor: '#3b82f6' }}
      />
    </CardContainer>
  );
};

export default A2UIFormCard;
