#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Minibuild core: a simplified, maintainable build pipeline for PyInstaller.

Design goals:
- Single spec generator with minimal dynamic-import detection
- Minimal config surface (reuse build_system/build_config.json where possible)
- Default to onedir; onefile optional per mode
- Works on Windows and macOS; supports macOS .app (BUNDLE) and PKG via existing InstallerBuilder
- Very small hook surface (reuse existing build_system/pyinstaller_hooks)
"""
from __future__ import annotations

import ast
import json
import sys
import subprocess
import os
from pathlib import Path
from typing import Dict, List, Set, Any, Optional
import shutil


class MiniSpecBuilder:
    def __init__(self, project_root: Optional[Path] = None, config_path: str = "build_system/build_config.json"):
        self.project_root = project_root or Path.cwd()
        self.config_path = self.project_root / config_path
        with open(self.config_path, "r", encoding="utf-8") as f:
            self.cfg: Dict[str, Any] = json.load(f)
        # Generated hooks directory (for pre_safe_import_module)
        self.gen_hooks_dir = self.project_root / "build" / "pyinstaller_hooks_gen"
        self.pre_safe_dir = self.gen_hooks_dir / "pre_safe_import_module"

    # ---- Public API ----
    def build(self, mode: str = "fast") -> bool:
        # Generate essential pre-safe hooks for known problematic modules
        self._ensure_pre_safe_hooks()
        self._ensure_global_sitecustomize()

        # Write spec file
        self._last_spec_path = self._write_spec(mode)
        
        # Run PyInstaller
        # Use virtual environment Python if available, fallback to sys.executable
        python_executable = self._get_python_executable()
        cmd = [python_executable, "-m", "PyInstaller", str(self._last_spec_path), "--noconfirm", "--clean"]
        print(f"[MINIBUILD] Running: {' '.join(cmd)}")
        env = os.environ.copy()
        py_path = str(self.gen_hooks_dir)
        env["PYTHONPATH"] = (py_path + (os.pathsep + env.get("PYTHONPATH", "") if env.get("PYTHONPATH") else ""))
        env["PYTHONUTF8"] = "1"
        
        result = subprocess.run(cmd, cwd=str(self.project_root), env=env)
        if result.returncode != 0:
            print(f"[MINIBUILD] Build failed with code {result.returncode}")
            return False
        print("[MINIBUILD] Build succeeded")
        return True

    def _ensure_pre_safe_hooks(self) -> None:
        """Generate essential pre-safe hooks for known problematic modules"""
        try:
            # Only generate hooks for modules that are actually used
            used_modules = self._get_used_modules()
            if not used_modules:
                return
                
            self.pre_safe_dir.mkdir(parents=True, exist_ok=True)
            tmpl = (
                "# Auto-generated by minibuild_core: pre-safe import hook for {mod}\n"
                "def pre_safe_import_module(api):\n"
                "    import sys, argparse\n"
                "    try:\n"
                "        # Patch argparse to avoid argv side-effects during PyInstaller analysis\n"
                "        _orig_parse_args = argparse.ArgumentParser.parse_args\n"
                "        _orig_parse_known_args = argparse.ArgumentParser.parse_known_args\n"
                "        def _safe_parse_args(self, args=None, namespace=None):\n"
                "            return _orig_parse_args(self, args=[], namespace=namespace)\n"
                "        def _safe_parse_known_args(self, args=None, namespace=None):\n"
                "            return _orig_parse_known_args(self, args=[], namespace=namespace)\n"
                "        argparse.ArgumentParser.parse_args = _safe_parse_args\n"
                "        argparse.ArgumentParser.parse_known_args = _safe_parse_known_args\n"
                "    except Exception:\n"
                "        pass\n"
            )
            
            # Generate hooks only for modules that need them
            essential_modules = {"lightrag", "lightrag.api", "jaraco.text", "jaraco.functools"}
            for mod in essential_modules:
                if mod in used_modules:
                    (self.pre_safe_dir / f"hook-{mod}.py").write_text(tmpl.format(mod=mod), encoding="utf-8")
                    
        except Exception as e:
            print(f"[MINIBUILD] Warning: Failed to generate pre-safe hooks: {e}")

    def _ensure_global_sitecustomize(self) -> None:
        """Ensure a sitecustomize.py that patches argparse globally for isolated child processes."""
        try:
            self.gen_hooks_dir.mkdir(parents=True, exist_ok=True)
            sc = self.gen_hooks_dir / "sitecustomize.py"
            content = (
                "# Auto-generated by minibuild_core: global sitecustomize for PyInstaller isolated child\n"
                "import sys, os, argparse\n"
                "try:\n"
                "    # Only patch when running PyInstaller's isolated child (_child.py)\n"
                "    if hasattr(sys, 'argv') and len(sys.argv) > 0:\n"
                "        prog = os.path.basename(sys.argv[0]).lower()\n"
                "        if prog.endswith('_child.py'):\n"
                "            _orig_parse_args = argparse.ArgumentParser.parse_args\n"
                "            _orig_parse_known_args = argparse.ArgumentParser.parse_known_args\n"
                "            def _safe_parse_args(self, args=None, namespace=None):\n"
                "                return _orig_parse_args(self, args=[], namespace=namespace)\n"
                "            def _safe_parse_known_args(self, args=None, namespace=None):\n"
                "                return _orig_parse_known_args(self, args=[], namespace=namespace)\n"
                "            argparse.ArgumentParser.parse_args = _safe_parse_args\n"
                "            argparse.ArgumentParser.parse_known_args = _safe_parse_known_args\n"
                "except Exception:\n"
                "    pass\n"
            )
            sc.write_text(content, encoding="utf-8")
        except Exception as e:
            print(f"[MINIBUILD] Warning: Failed to generate sitecustomize: {e}")

    def _get_used_modules(self) -> Set[str]:
        """Get modules that are actually used in the project"""
        modules = set()
        
        # Add modules from config
        pyinstaller_cfg = self.cfg.get("pyinstaller", {})
        modules.update(pyinstaller_cfg.get("collect_all", []))
        modules.update(pyinstaller_cfg.get("collect_data_only", []))
        modules.update(pyinstaller_cfg.get("force_includes", []))
        modules.update(pyinstaller_cfg.get("force_hiddenimports", []))
        
        return modules

    def _get_python_executable(self) -> str:
        """Get the appropriate Python executable for PyInstaller"""
        # Check if we're in a virtual environment
        if hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix):
            # We're in a virtual environment, use the venv Python
            venv_python = self.project_root / "venv" / "bin" / "python3"
            if sys.platform.startswith("win"):
                venv_python = self.project_root / "venv" / "Scripts" / "python.exe"
            
            if venv_python.exists():
                return str(venv_python)
        
        # Fallback to current executable
        return sys.executable

    # ---- Spec generation ----
    def _write_spec(self, mode: str) -> Path:
        app = self.cfg.get("app_info", {})
        app_name = app.get("name", "app")
        main_script = app.get("main_script", "main.py")
        icon_win = app.get("icon_windows", "eCan.ico")
        icon_mac = app.get("icon_macos", "eCan.icns")

        bmodes = self.cfg.get("build_modes", {})
        mode_cfg = bmodes.get(mode, {})
        onefile = bool(mode_cfg.get("onefile", False))
        console = bool(mode_cfg.get("console", app.get("console", False)))
        debug = bool(mode_cfg.get("debug", app.get("debug", False)))

        datas_lines = self._datas_from_config()
        hiddenimports = self._hiddenimports_from_config()

        spec_lines: List[str] = []
        spec_lines.append("# -*- mode: python ; coding: utf-8 -*-")
        spec_lines.append("import sys")
        spec_lines.append("from pathlib import Path")
        spec_lines.append("project_root = Path(r'" + str(self.project_root) + "')")
        spec_lines.append("")
        spec_lines.append("import os as _os, sys as _sys")
        spec_lines.append("")
        spec_lines.append("data_files = []")
        spec_lines.append("binaries = []")
        spec_lines.append("hiddenimports = " + repr(hiddenimports))
        spec_lines.extend(datas_lines)
        spec_lines.append("")

        # Collect all resources/hiddenimports/binaries for configured packages
        collect_pkgs = self.cfg.get("pyinstaller", {}).get("collect_all", []) or []
        if collect_pkgs:
            spec_lines.append("from PyInstaller.utils.hooks import collect_all")
            spec_lines.append("hooked_bins = []")
            spec_lines.append("hooked_hidden = []")
            spec_lines.append("for _pkg in " + repr(collect_pkgs) + ":")
            spec_lines.append("    _d, _b, _h = collect_all(_pkg)")
            spec_lines.append("    data_files += _d")
            spec_lines.append("    binaries += _b")
            spec_lines.append("    hiddenimports += _h")
            spec_lines.append("")

        # Collect data-only for packages that cannot be imported in isolated child
        collect_data_only = self.cfg.get("pyinstaller", {}).get("collect_data_only", []) or []
        if collect_data_only:
            spec_lines.append("from PyInstaller.utils.hooks import collect_data_files")
            spec_lines.append("for _pkg in " + repr(collect_data_only) + ":")
            spec_lines.append("    data_files += collect_data_files(_pkg)")
            spec_lines.append("")

        # Analysis section
        spec_lines.append("a = Analysis([")
        spec_lines.append(f"    r'{main_script}',")
        spec_lines.append("],")
        spec_lines.append("    pathex=[str(project_root)],")
        spec_lines.append("    binaries=binaries,")
        spec_lines.append("    datas=data_files,")
        spec_lines.append("    hiddenimports=hiddenimports,")
        spec_lines.append("    hookspath=[],  # Use PyInstaller's default hooks for PySide6/QtWebEngine")
        spec_lines.append("    hooksconfig={},")

        # Handle codesign exclusions for macOS
        excludes = self.cfg.get("pyinstaller", {}).get("excludes", [])
        if sys.platform == 'darwin':
            codesign_excludes = self.cfg.get("pyinstaller", {}).get("codesign_exclude", [])
            if codesign_excludes:
                # Add ms-playwright to excludes to prevent it from being collected
                excludes.append('ms-playwright')
                spec_lines.append("    # macOS codesign exclusions added to excludes")
                spec_lines.append("    # ms-playwright will be excluded from Analysis")
                for exclude in codesign_excludes:
                    spec_lines.append(f"    # codesign_exclude: {exclude}")
                spec_lines.append("")
        
        spec_lines.append("    excludes=" + repr(excludes) + ",")
        spec_lines.append("    runtime_hooks=[],")
        spec_lines.append("    win_no_prefer_redirects=False,")
        spec_lines.append("    win_private_assemblies=False,")
        
        # Get optimization settings
        opt_cfg = self.cfg.get("pyinstaller", {}).get("optimization", {})
        copy_metadata = opt_cfg.get("copy_metadata", True)
        
        spec_lines.append("    cipher=None,")
        spec_lines.append("    noarchive=False,")
        spec_lines.append(f"    copy_metadata={copy_metadata},")
        spec_lines.append(")")
        spec_lines.append("")

        # Basic cleanup: remove duplicate entries
        spec_lines.append("# Basic cleanup: remove duplicate entries")
        spec_lines.append("seen_datas = set()")
        spec_lines.append("unique_datas = []")
        spec_lines.append("for data in a.datas:")
        spec_lines.append("    data_key = (data[0], data[1])")
        spec_lines.append("    if data_key not in seen_datas:")
        spec_lines.append("        seen_datas.add(data_key)")
        spec_lines.append("        unique_datas.append(data)")
        spec_lines.append("a.datas = unique_datas")
        spec_lines.append("")
        spec_lines.append("seen_bins = set()")
        spec_lines.append("unique_bins = []")
        spec_lines.append("for b in a.binaries:")
        spec_lines.append("    key = (b[0], b[1])")
        spec_lines.append("    if key not in seen_bins:")
        spec_lines.append("        seen_bins.add(key)")
        spec_lines.append("        unique_bins.append(b)")
        spec_lines.append("a.binaries = unique_bins")
        spec_lines.append("print(f'[SPEC] Cleaned up: {len(unique_datas)} datas, {len(unique_bins)} binaries')")
        spec_lines.append("")
        
        # Post-analysis cleanup for macOS: remove Playwright binaries that cause codesign issues
        spec_lines.append("if _sys.platform == 'darwin':")
        spec_lines.append("    # Remove Playwright binaries that cause codesign failures")
        spec_lines.append("    playwright_binaries = []")
        spec_lines.append("    for binary in a.binaries[:]:")
        spec_lines.append("        dest_name = str(binary[0])")
        spec_lines.append("        # Remove any Playwright-related binaries that might have been collected")
        spec_lines.append("        if any(pattern in dest_name for pattern in ['ms-playwright', 'chromium', 'chrome-mac', 'chrome-mac-arm64']):")
        spec_lines.append("            playwright_binaries.append(binary)")
        spec_lines.append("            a.binaries.remove(binary)")
        spec_lines.append("    print(f'[SPEC] Removed {len(playwright_binaries)} Playwright binaries to avoid codesign issues')")
        spec_lines.append("")
        spec_lines.append("    # Basic framework symlink cleanup to prevent conflicts")
        spec_lines.append("    # Remove duplicate framework content that should be symlinks")
        spec_lines.append("    framework_duplicates = []")
        spec_lines.append("    for binary in a.binaries[:]:")
        spec_lines.append("        dest_name = str(binary[0])")
        spec_lines.append("        # If we have both Versions/Current/Helpers/foo and Helpers/foo, keep only Versions/Current/Helpers/foo")
        spec_lines.append("        if '.framework/Helpers/' in dest_name and '.framework/Versions/' not in dest_name:")
        spec_lines.append("            # Check if we also have the Versions/Current version")
        spec_lines.append("            versions_path = dest_name.replace('.framework/Helpers/', '.framework/Versions/Current/Helpers/')")
        spec_lines.append("            if any(str(b[0]) == versions_path for b in a.binaries):")
        spec_lines.append("                framework_duplicates.append(binary)")
        spec_lines.append("                a.binaries.remove(binary)")
        spec_lines.append("    print(f'[SPEC] Removed {len(framework_duplicates)} framework symlink duplicates')")
        spec_lines.append("")
        
        spec_lines.append("pyz = PYZ(a.pure, a.zipped_data, cipher=None)")
        spec_lines.append("")

        if onefile:
            # onefile EXE
            spec_lines.append("exe = EXE(")
            spec_lines.append("    pyz,")
            spec_lines.append("    a.scripts,")
            spec_lines.append("    a.binaries,")
            spec_lines.append("    a.zipfiles,")
            spec_lines.append("    a.datas,")
            spec_lines.append(f"    name='{app_name}',")
            spec_lines.append(f"    debug={repr(debug)},")
            spec_lines.append("    bootloader_ignore_signals=False,")
            spec_lines.append(f"    strip={'False' if sys.platform.startswith('win') else 'True'},")
            spec_lines.append("    upx=False,")
            spec_lines.append("    upx_exclude=[],")
            spec_lines.append("    runtime_tmpdir=None,")
            spec_lines.append(f"    console={repr(console)},")
            spec_lines.append("    icon=(r'" + (icon_mac if sys.platform == 'darwin' else icon_win) + "'),")
            spec_lines.append(")")
        else:
            # onedir EXE + COLLECT
            spec_lines.append("exe = EXE(")
            spec_lines.append("    pyz,")
            spec_lines.append("    a.scripts,")
            spec_lines.append("    [],")
            spec_lines.append("    exclude_binaries=True,")
            spec_lines.append(f"    name='{app_name}',")
            spec_lines.append(f"    debug={repr(debug)},")
            spec_lines.append("    bootloader_ignore_signals=False,")
            spec_lines.append(f"    strip={'False' if sys.platform.startswith('win') else 'True'},")
            spec_lines.append("    upx=False,")
            spec_lines.append("    upx_exclude=[],")
            spec_lines.append("    runtime_tmpdir=None,")
            spec_lines.append(f"    console={repr(console)},")
            spec_lines.append("    icon=(r'" + (icon_mac if sys.platform == 'darwin' else icon_win) + "'),")
            spec_lines.append(")")
            spec_lines.append("")
            spec_lines.append("coll = COLLECT(")
            spec_lines.append("    exe,")
            spec_lines.append("    a.binaries,")
            spec_lines.append("    a.zipfiles,")
            spec_lines.append("    a.datas,")
            spec_lines.append(f"    strip={'False' if sys.platform.startswith('win') else 'True'},")
            spec_lines.append("    upx=False,")
            spec_lines.append("    upx_exclude=[],")
            spec_lines.append("    exclude_binaries=False,")
            spec_lines.append("    name='{app_name}'".format(app_name=app_name))
            spec_lines.append(")")
            spec_lines.append("")
            
            # macOS app bundle wrapper
            spec_lines.append("if _sys.platform == 'darwin':")
            spec_lines.append("    app = BUNDLE(")
            spec_lines.append("        coll,")
            spec_lines.append(f"        name='{app_name}.app',")
            spec_lines.append("        icon=(r'" + icon_mac + "'),")
            spec_lines.append("    )")

        spec_path = self.project_root / f"{app_name}_{mode}.spec"
        spec_path.write_text("\n".join(spec_lines), encoding="utf-8")
        print(f"[MINIBUILD] Wrote spec: {spec_path}")
        return spec_path

    # ---- Helpers ----
    def _datas_from_config(self) -> List[str]:
        """Generate spec lines for data files/dirs, skipping entries that don't exist."""
        lines: List[str] = []
        data_cfg = self.cfg.get("data_files", {})
        
        # Directories
        for d in data_cfg.get("directories", []) or []:
            d_path = (self.project_root / d)
            if d_path.exists():
                lines.append(f"data_files.append((r'{d}', r'{d}'))")
            else:
                print(f"[MINIBUILD] Warning: data directory not found, skipping: {d_path}")
        
        # Files
        for f in data_cfg.get("files", []) or []:
            f_path = (self.project_root / f)
            if f_path.exists():
                lines.append(f"data_files.append((r'{f}', r'.'))")
            else:
                print(f"[MINIBUILD] Warning: data file not found, skipping: {f_path}")
        
        return lines

    def _hiddenimports_from_config(self) -> List[str]:
        """Get hiddenimports from config, with minimal essential additions"""
        base: Set[str] = {
            # Qt WebEngine pieces (let PyInstaller's own hooks pick the rest)
            "PySide6.QtWebEngineCore",
            "PySide6.QtWebEngineWidgets",
        }
        
        # Merge with config
        pyinstaller_cfg = self.cfg.get("pyinstaller", {})
        for m in pyinstaller_cfg.get("force_includes", []) or []:
            if isinstance(m, str) and m:
                base.add(m)
        
        for m in pyinstaller_cfg.get("force_hiddenimports", []) or []:
            if isinstance(m, str) and m:
                base.add(m)
        
        return sorted(base)


__all__ = ["MiniSpecBuilder"]

