"""
Unit tests for OTA path / permission / template safety.

These tests do NOT exercise Inno Setup, hdiutil, or real osascript
invocations — they verify the safety properties of the OTA pipeline:

  * ``ecan_ota_launcher_template.bat`` does not contain any batch
    positional-argument token (``%N%``) that Python's ``str.replace``
    would silently turn into a positional-arg reference at runtime.
  * The macOS PKG helper script generated by ``_install_pkg`` takes
    ``$1`` as the package path rather than embedding the path into
    the bash source — so paths with double-quote, dollar, backslash,
    spaces, backticks, or other shell-special characters round-trip
    cleanly.
  * The macOS DMG install path invokes ``osascript`` with
    ``administrator privileges`` (not just a plain ``do shell script``),
    so the user actually gets prompted for credentials when writing
    to ``/Applications``.
  * ``safe_makedirs`` raises ``RuntimeError`` with platform-specific
    remediation hints on ``PermissionError``.
  * ``is_writable_dir`` returns ``False`` for non-existent paths and
    ``True`` for paths the current process can write to.

All these tests run on any platform (they use ``tmp_path`` and never
touch real OTA directories).
"""

import os
import platform
import re
import sys
import stat
import textwrap
from pathlib import Path

import pytest


# Skip when PySide6 / full OTA stack is unavailable. We import lazily
# inside each test so the import error here is test-environment-specific
# rather than a code regression.
def _import_installer():
    """Import ``ota.core.installer`` after stubbing PySide6 if needed."""
    try:
        import ota.core.installer  # noqa: F401
        return __import__("ota.core.installer", fromlist=["*"])
    except ImportError:
        # Stub PySide6 just enough that ``ota.gui`` imports don't crash.
        import types

        pyside6 = types.ModuleType("PySide6")
        qtcore = types.ModuleType("PySide6.QtCore")
        qtgui = types.ModuleType("PySide6.QtGui")
        qtwidgets = types.ModuleType("PySide6.QtWidgets")

        class _Stub:
            def __init__(self, *a, **kw):
                pass

            def __getattr__(self, name):
                return _Stub()

            def __call__(self, *a, **kw):
                return _Stub()

        for mod, names in [
            (qtcore, ["QObject", "Signal", "Qt", "QThread", "QTimer"]),
            (qtgui, ["QFont", "QIcon", "QPixmap"]),
            (
                qtwidgets,
                [
                    "QDialog", "QMessageBox", "QProgressBar", "QCheckBox",
                    "QGridLayout", "QGroupBox", "QHBoxLayout", "QApplication",
                    "QPushButton", "QSpacerItem", "QSizePolicy", "QTextEdit",
                    "QVBoxLayout", "QLabel", "QFrame",
                ],
            ),
        ]:
            for n in names:
                setattr(mod, n, _Stub)

        pyside6.QtCore = qtcore
        pyside6.QtGui = qtgui
        pyside6.QtWidgets = qtwidgets
        sys.modules["PySide6"] = pyside6
        sys.modules["PySide6.QtCore"] = qtcore
        sys.modules["PySide6.QtGui"] = qtgui
        sys.modules["PySide6.QtWidgets"] = qtwidgets

        return __import__("ota.core.installer", fromlist=["*"])


@pytest.fixture(scope="module")
def installer_module():
    return _import_installer()


# ---------------------------------------------------------------------------
# BAT template regression: %__ARGS_COUNT__% was batch-positional-arg
# ---------------------------------------------------------------------------


class TestBatTemplate:
    """The Windows OTA launcher BAT must not interpret placeholders as positional args."""

    REPO_ROOT = Path(__file__).resolve().parents[2]
    BAT_TEMPLATE = REPO_ROOT / "ota" / "resources" / "ecan_ota_launcher_template.bat"

    def test_template_file_exists(self):
        """The launcher template must exist on disk."""
        assert self.BAT_TEMPLATE.exists(), f"BAT template missing: {self.BAT_TEMPLATE}"

    def test_template_has_no_positional_arg_placeholder(self):
        """``%N%`` style tokens must not appear in the template.

        Python's ``str.replace("__ARGS_COUNT__", "2")`` would turn the
        literal ``%__ARGS_COUNT__%`` in the source into ``%2%``, which
        batch parses as positional arg 2 + literal ``%``. We pin the
        template to NOT contain any ``%N%`` pattern so this regression
        cannot recur.
        """
        text = self.BAT_TEMPLATE.read_text(encoding="utf-8")
        # Reject any %N% where N is 0-9 (positional args). %% is fine —
        # it's the literal-% escape and won't fire replacement twice.
        offenders = re.findall(r"%[0-9]%", text)
        assert not offenders, (
            f"BAT template contains positional-arg tokens {offenders}; "
            f"these get rewritten by ``str.replace`` at runtime into "
            f"something other than the literal count. Remove the ``%`` "
            f"around placeholders."
        )

    def test_template_uses_disable_delayed_expansion(self):
        """``!`` in installer paths must not be re-interpreted."""
        text = self.BAT_TEMPLATE.read_text(encoding="utf-8")
        # Case-insensitive — batch is case-insensitive about keywords.
        assert re.search(r"setlocal\s+DisableDelayedExpansion", text, re.IGNORECASE), (
            "BAT template must use ``setlocal DisableDelayedExpansion`` "
            "to defeat delayed-expansion re-interpretation of ``!`` in "
            "installer paths."
        )

    def test_template_uses_argv_passthrough(self):
        """``start "" %*`` must forward all installer args verbatim."""
        text = self.BAT_TEMPLATE.read_text(encoding="utf-8")
        assert "start \"\" %*" in text, (
            "BAT template must forward args via ``start \"\" %*`` so "
            "paths with spaces / quotes / ampersands round-trip cleanly."
        )

    def test_template_placeholder_will_render_as_literal_int(self):
        """After str.replace the count line is human-readable."""
        text = self.BAT_TEMPLATE.read_text(encoding="utf-8")
        # Substitute the placeholders ourselves and verify the result
        # is human-readable. This catches future regressions where
        # someone re-introduces ``%`` around ``__ARGS_COUNT__``.
        rendered = text.replace("__DELAY_SECONDS__", "3").replace("__ARGS_COUNT__", "2")
        echo_line = next(
            (line for line in rendered.splitlines() if "Launching installer" in line),
            None,
        )
        assert echo_line is not None, "Template missing the 'Launching installer' echo line"
        # The rendered line must contain the literal ``2 argument(s)``
        # text — no batch metacharacters. This proves the template
        # doesn't depend on positional-arg expansion for the count.
        assert "2 argument(s)" in echo_line, (
            f"Rendered echo line missing '2 argument(s)': {echo_line!r}"
        )
        # And it must NOT contain %2% — that would mean positional
        # expansion was reintroduced.
        assert "%2%" not in echo_line, (
            f"Rendered echo line still has %2% positional-arg token: {echo_line!r}"
        )


# ---------------------------------------------------------------------------
# PKG helper script safety: $1 instead of embedded package_path
# ---------------------------------------------------------------------------


class TestPkgHelperScriptSafety:
    """The macOS PKG helper script must not embed ``package_path`` into bash."""

    def test_helper_script_uses_positional_arg(self, tmp_path, monkeypatch):
        """Re-rendering the PKG helper with a path that has ``"`` and ``$`` survives."""
        # Stub the appdata path so the installer writes under tmp_path.
        from config.app_info import app_info  # type: ignore

        monkeypatch.setattr(app_info, "appdata_path", str(tmp_path))

        installer = _import_installer()
        # Construct an instance with a controlled package_path. The
        # package_path doesn't need to actually exist — we just want to
        # read what ``_install_pkg`` WOULD have written to disk.
        mgr = installer.InstallationManager()

        # The helper script content lives in a separate method in our
        # implementation; rather than mocking the whole AppleScript
        # path, we replicate the script-rendering snippet here so we
        # can assert against it independently of the platform check.
        # If you change ``_install_pkg``, keep this test in sync.
        package_path_str = '/tmp/has space and "$ and backtick ` and \\.pkg'
        script_content = textwrap.dedent(
            """
            #!/bin/bash
            # $1 = absolute path to .pkg. Quote once to defeat shell word-splitting.
            installer -pkg "$1" -target / -verboseR 2>&1
            """
        )

        # Render the script.
        rendered_path = tmp_path / "sample_pkg_helper.sh"
        rendered_path.write_text(script_content, encoding="utf-8")
        os.chmod(rendered_path, 0o755)

        # Bash must accept the rendered script as parseable.
        import subprocess

        result = subprocess.run(
            ["bash", "-n", str(rendered_path)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, (
            f"Rendered bash script failed ``bash -n`` syntax check: "
            f"stderr={result.stderr!r}"
        )

        # Sanity: the script source must NOT contain the package path
        # literal. If we embedded it via f-string the special chars
        # above would have broken bash parsing — exactly the regression
        # we want to prevent.
        text = rendered_path.read_text(encoding="utf-8")
        assert "$1" in text, "Helper script must use $1 to receive package path"
        assert package_path_str not in text, (
            "Helper script embedded the package path literally — "
            "shell-special chars in the path will break the script."
        )

    def test_pkg_argv_passes_pkg_path_safely(self, tmp_path, monkeypatch):
        """AppleScript invocation should pass pkg_path via argv, not via f-string."""
        # This is a structural test: we grep the installer source to
        # make sure ``_install_pkg`` does NOT have any leftover
        # ``f'installer -pkg "{package_path}"`` interpolation. If a
        # future refactor reintroduces that pattern, this test fires.
        installer_path = (
            Path(__file__).resolve().parents[2] / "ota" / "core" / "installer.py"
        )
        text = installer_path.read_text(encoding="utf-8")
        # Reject the exact broken pattern from the old code.
        bad_pattern = re.compile(
            r'installer\s+-pkg\s+"\{package_path\}"', re.MULTILINE
        )
        matches = bad_pattern.findall(text)
        assert not matches, (
            "installer.py still has ``installer -pkg \"{package_path}\"`` "
            "f-string interpolation; replace with ``$1`` and pass pkg "
            "path via argv."
        )

        # And require that the helper-script literal in installer.py
        # uses ``$1`` so positional-arg passing is preserved.
        assert 'installer -pkg "$1"' in text, (
            "installer.py PKG helper script must use ``installer -pkg \"$1\"`` "
            "so shell-special chars in the package path survive."
        )


# ---------------------------------------------------------------------------
# macOS DMG install: must request admin privileges for /Applications
# ---------------------------------------------------------------------------


class TestDmgInstallElevation:
    """DMG install to /Applications must NOT use plain shutil.copytree."""

    def test_dmg_install_uses_osascript_with_admin(self):
        """``_install_dmg`` must wrap the copy in ``osascript … with administrator privileges``.

        We grep the source rather than executing it because
        ``_install_dmg`` requires admin / hdiutil which we can't
        safely exercise from CI. The structural test is enough to
        catch a regression where someone reverts to the unguarded
        ``shutil.copytree`` path.
        """
        installer_path = (
            Path(__file__).resolve().parents[2] / "ota" / "core" / "installer.py"
        )
        text = installer_path.read_text(encoding="utf-8")
        # Locate the body of ``_install_dmg`` and assert within it.
        m = re.search(r"def _install_dmg\(.*?\n(?=    def |\Z)", text, re.DOTALL)
        assert m, "Could not locate ``_install_dmg`` in installer.py"
        body = m.group(0)
        assert "administrator privileges" in body, (
            "``_install_dmg`` must call ``osascript … with administrator "
            "privileges`` so /Applications writes can succeed."
        )
        assert "/usr/bin/osascript" in body, (
            "``_install_dmg`` must use the absolute path ``/usr/bin/osascript`` "
            "to avoid PATH manipulation by the privileged shell."
        )
        # The old broken pattern ``shutil.copytree(app_file, target_path)``
        # is what allowed unprivileged writes to ``/Applications`` to fail
        # silently. Reject any direct copytree in the DMG body.
        assert "shutil.copytree(app_file, target_path)" not in body, (
            "``_install_dmg`` still has the unguarded ``shutil.copytree(app_file, target_path)`` "
            "that writes to /Applications without admin elevation."
        )

    def test_dmg_helper_script_uses_argv(self):
        """DMG helper script must take source/dest via positional args."""
        installer_path = (
            Path(__file__).resolve().parents[2] / "ota" / "core" / "installer.py"
        )
        text = installer_path.read_text(encoding="utf-8")
        assert 'rm -rf "$2" 2>/dev/null' in text, (
            "DMG helper must use ``rm -rf \"$2\"`` so the destination "
            "path round-trips through bash positional args safely."
        )
        assert 'cp -R "$1" "$2"' in text, (
            "DMG helper must use ``cp -R \"$1\" \"$2\"`` so the source "
            "and destination paths round-trip safely."
        )


# ---------------------------------------------------------------------------
# safe_makedirs + is_writable_dir helpers
# ---------------------------------------------------------------------------


class TestSafeMakedirs:
    """``safe_makedirs`` must convert PermissionError into a clear RuntimeError."""

    def test_creates_missing_directory(self, installer_module, tmp_path):
        target = tmp_path / "new_subdir" / "ota"
        result = installer_module.safe_makedirs(target, purpose="OTA test")
        assert result == target
        assert target.is_dir()

    def test_idempotent_when_directory_exists(self, installer_module, tmp_path):
        target = tmp_path / "already_here"
        target.mkdir()
        # Should not raise even though the dir exists.
        result = installer_module.safe_makedirs(target, purpose="OTA test")
        assert result == target

    def test_permission_error_reraises_as_runtime_error(self, installer_module, tmp_path):
        """When the parent directory is read-only, we get RuntimeError with hint."""
        if platform.system() == "Windows":
            pytest.skip("POSIX-only permission semantics; chmod doesn't map to Windows ACLs")

        parent = tmp_path / "ro_parent"
        parent.mkdir()
        # Make parent read-only by removing write permission for owner.
        # This affects ``mkdir`` because POSIX ``mkdir`` requires write
        # on the parent directory. (Creating a subdir inside a read-only
        # parent fails with EACCES.)
        os.chmod(parent, stat.S_IRUSR | stat.S_IXUSR)

        target = parent / "ota_scripts"
        try:
            with pytest.raises(RuntimeError) as excinfo:
                installer_module.safe_makedirs(target, purpose="OTA scripts")
            msg = str(excinfo.value)
            assert "OTA scripts" in msg, (
                f"RuntimeError message must include the purpose label, got: {msg!r}"
            )
            assert "permission denied" in msg.lower(), (
                f"RuntimeError message must mention permission denied, got: {msg!r}"
            )
        finally:
            # Restore write so pytest can clean up tmp_path.
            os.chmod(parent, stat.S_IRWXU)

    def test_existing_file_raises_runtime_error(self, installer_module, tmp_path):
        """If a regular file occupies the target path, RuntimeError (not silent success)."""
        blocker = tmp_path / "not_a_directory"
        blocker.write_text("I am a regular file, not a dir")
        with pytest.raises(RuntimeError) as excinfo:
            installer_module.safe_makedirs(blocker, purpose="OTA test")
        assert "regular file" in str(excinfo.value)


class TestIsWritableDir:
    """``is_writable_dir`` must be a strict probe."""

    def test_existing_writable_dir_is_true(self, installer_module, tmp_path):
        assert installer_module.is_writable_dir(tmp_path) is True

    def test_nonexistent_path_is_false(self, installer_module, tmp_path):
        ghost = tmp_path / "does_not_exist"
        assert installer_module.is_writable_dir(ghost) is False

    def test_read_only_parent_is_false(self, installer_module, tmp_path):
        if platform.system() == "Windows":
            pytest.skip("POSIX-only; chmod doesn't model Windows ACLs")
        ro = tmp_path / "ro"
        ro.mkdir()
        os.chmod(ro, stat.S_IRUSR | stat.S_IXUSR)
        try:
            assert installer_module.is_writable_dir(ro) is False
        finally:
            os.chmod(ro, stat.S_IRWXU)


# ---------------------------------------------------------------------------
# Install-dir writability check before launching installer (Windows EXE)
# ---------------------------------------------------------------------------


class TestInstallDirWritabilityCheck:
    """``_install_exe`` must short-circuit if install_dir is not writable."""

    def test_install_exe_logs_warning_when_install_dir_unwritable(
        self, installer_module, monkeypatch, tmp_path
    ):
        """When install_dir is unwritable, we log a clear warning instead of silently launching."""
        if platform.system() == "Windows":
            pytest.skip("POSIX-only test (chmod) — Windows test belongs in the BAT branch.")

        mgr = installer_module.InstallationManager()

        # Force the install-dir resolver to return our read-only dir.
        ro_dir = tmp_path / "ro_install"
        ro_dir.mkdir()
        os.chmod(ro_dir, stat.S_IRUSR | stat.S_IXUSR)

        # The OTA installer logs through ``utils.logger_helper``, which
        # sets ``propagate=False`` on its named logger ("eCan"). pytest's
        # ``caplog`` hooks the root logger, so it doesn't see those
        # records. We attach a temporary handler to the actual logger to
        # capture the records instead.
        captured = []
        import logging

        otta_logger = logging.getLogger("eCan")
        handler = logging.Handler()
        handler.emit = lambda record: captured.append(record)
        otta_logger.addHandler(handler)
        try:
            monkeypatch.setattr(
                mgr, "_get_current_windows_install_dir", lambda: ro_dir
            )

            fake_pkg = tmp_path / "fake.exe"
            fake_pkg.write_bytes(b"fake")

            # Pretend we're frozen so the install path doesn't dev-fallback.
            monkeypatch.setattr(sys, "frozen", True, raising=False)
            # Pretend we're on Windows so we hit the Inno Setup branch.
            monkeypatch.setattr(sys, "platform", "win32")

            mgr._install_exe(fake_pkg, install_options={"silent": True})
        finally:
            otta_logger.removeHandler(handler)
            os.chmod(ro_dir, stat.S_IRWXU)

        # The writability check MUST have logged an error.
        assert any(
            "Target install directory is NOT writable" in record.getMessage()
            for record in captured
        ), (
            "Expected ``Target install directory is NOT writable`` "
            "log line when install_dir is read-only; the check "
            "either didn't fire or the message was downgraded."
        )

    def test_install_exe_returns_false_when_both_dirs_unwritable(
        self, installer_module, monkeypatch, tmp_path
    ):
        """When even the sys.executable fallback is unwritable, _install_exe returns False."""
        if platform.system() == "Windows":
            pytest.skip("POSIX-only test (chmod).")

        mgr = installer_module.InstallationManager()

        # Both target install dir and the sys.executable parent must be
        # read-only so the fallback path ALSO fails. To create a file
        # inside a directory we're about to chmod, we:
        #   1. mkdir the fallback dir
        #   2. create the file while the dir is still writable
        #   3. THEN chmod to read-only
        ro_dir = tmp_path / "ro_install"
        ro_dir.mkdir()
        os.chmod(ro_dir, stat.S_IRUSR | stat.S_IXUSR)

        fallback_dir = tmp_path / "ro_fallback"
        fallback_dir.mkdir()
        fake_exe = fallback_dir / "fake_exe"
        fake_exe.write_bytes(b"")
        os.chmod(fallback_dir, stat.S_IRUSR | stat.S_IXUSR)

        try:
            monkeypatch.setattr(
                mgr, "_get_current_windows_install_dir", lambda: ro_dir
            )
            monkeypatch.setattr(sys, "frozen", True, raising=False)
            monkeypatch.setattr(sys, "platform", "win32")
            original_executable = sys.executable
            monkeypatch.setattr(sys, "executable", str(fake_exe))

            fake_pkg = tmp_path / "fake.exe"
            fake_pkg.write_bytes(b"fake")

            result = mgr._install_exe(fake_pkg, install_options={"silent": True})
            assert result is False, (
                "_install_exe should return False (NOT launch the "
                "installer) when both the resolved install_dir and "
                "the sys.executable fallback are unwritable."
            )
        finally:
            monkeypatch.setattr(sys, "executable", original_executable)
            os.chmod(ro_dir, stat.S_IRWXU)
            os.chmod(fallback_dir, stat.S_IRWXU)


# ---------------------------------------------------------------------------
# Regression: Inno Setup command MUST pin the install directory via /DIR=
# ---------------------------------------------------------------------------


class TestInstallExeDirParameter:
    """Bug 2026-09-16 (continued): ``_install_exe`` previously built an
    Inno Setup command WITHOUT ``/DIR=<dir>`` — it relied entirely on
    ``UsePreviousAppDir=yes`` to recover the previous install dir from
    the registry. That was a leftover "Diagnostic mode B" experiment to
    A/B test an unrelated installer-flash-and-exit theory, but the
    side-effect is real:

      * If the registry key is missing / corrupted / out of date, Inno
        Setup falls back to ``DefaultDirName={autopf}\\eCan.cn`` (or
        ``{localappdata}\\eCan``) — a directory the OTA flow never
        validated for writability.
      * The user then sees Inno Setup install into ``C:\\Program Files``
        (or ``%LOCALAPPDATA%``) even though we validated a custom path
        like ``D:\\MyApps\\eCan`` is writable.

    Pin the fix: ``/DIR="<resolved install_dir>"`` MUST appear in the
    Inno Setup command in both the frozen and dev code paths."""

    def test_install_exe_includes_dir_parameter_in_cmd(
        self, installer_module, monkeypatch, tmp_path
    ):
        """The resolved install_dir must be passed to Inno Setup via /DIR=."""
        monkeypatch.setattr(sys, "platform", "win32")
        monkeypatch.setattr(sys, "frozen", True, raising=False)

        mgr = installer_module.InstallationManager()

        target_dir = tmp_path / "MyApps" / "eCan"
        target_dir.mkdir(parents=True)

        monkeypatch.setattr(
            mgr, "_get_current_windows_install_dir", lambda: target_dir
        )
        monkeypatch.setattr(
            mgr, "_terminate_processes_in_dir", lambda *a, **kw: None
        )
        monkeypatch.setattr(
            installer_module, "is_writable_dir", lambda p: True
        )

        # Capture the BAT launcher argv via a stub. We don't want to
        # actually spawn a subprocess or write a .bat file in this test
        # (DETACHED_PROCESS is Windows-only and would crash on macOS).
        #
        # NOTE: monkeypatch.setattr on the CLASS replaces the method
        # descriptor with a plain function, so when Python invokes
        # ``self._launch_windows_installer_delayed(...)`` the ``self``
        # instance is passed as the first positional argument. The
        # fake must therefore accept ``self`` explicitly.
        captured_cmd = {}

        def fake_launch(self, cmd, delay_seconds=3):
            captured_cmd["cmd"] = list(cmd)
            captured_cmd["delay"] = delay_seconds
            return 99999

        monkeypatch.setattr(
            installer_module.InstallationManager,
            "_launch_windows_installer_delayed",
            fake_launch,
        )
        # Stub download_manager.set_installing so we don't need the GUI.
        from ota.core import download_manager as _dm
        monkeypatch.setattr(
            _dm.download_manager, "set_installing", lambda *a, **kw: None
        )

        fake_pkg = tmp_path / "fake.exe"
        fake_pkg.write_bytes(b"fake")
        result = mgr._install_exe(fake_pkg, install_options={"silent": True})

        assert result is True, (
            f"_install_exe returned False (not the expected True); "
            f"captured_cmd={captured_cmd!r}"
        )
        assert "cmd" in captured_cmd, (
            f"_launch_windows_installer_delayed was not called; "
            f"captured_cmd={captured_cmd!r}"
        )
        cmd = captured_cmd["cmd"]
        # Look for a /DIR="<our resolved dir>" token in the cmd.
        expected = f'/DIR="{target_dir}"'
        assert any(
            expected == arg or arg.startswith(f'/DIR="{target_dir}')
            for arg in cmd
        ), (
            f"Inno Setup command MUST include ``/DIR=\"{target_dir}\"`` so "
            f"the installer writes to the directory we validated as "
            f"writable. Without it Inno Setup falls back to "
            f"``DefaultDirName`` and silently installs to "
            f"``C:\\Program Files\\eCan.cn`` (or "
            f"``%LOCALAPPDATA%\\eCan``). Got cmd: {cmd!r}"
        )

    def test_install_exe_includes_dir_in_dev_mode_cmd(
        self, installer_module, monkeypatch, tmp_path
    ):
        """The dev mode path must also include ``/DIR=`` — same belt-and-suspenders
        reasoning as the frozen path."""
        monkeypatch.setattr(sys, "platform", "win32")
        monkeypatch.setattr(sys, "frozen", False, raising=False)

        mgr = installer_module.InstallationManager()

        target_dir = tmp_path / "DevInstall" / "eCan"
        target_dir.mkdir(parents=True)

        monkeypatch.setattr(
            mgr, "_get_current_windows_install_dir", lambda: target_dir
        )

        # NOTE: monkeypatch.setattr on the CLASS replaces the method
        # descriptor with a plain function, so ``self`` is passed as
        # the first positional argument when Python invokes the
        # method. See the matching note in
        # ``test_install_exe_includes_dir_parameter_in_cmd``.
        captured_cmd = {}

        def fake_launch(self, cmd, delay_seconds=3):
            captured_cmd["cmd"] = list(cmd)
            return 99999

        monkeypatch.setattr(
            installer_module.InstallationManager,
            "_launch_windows_installer_delayed",
            fake_launch,
        )
        from ota.core import download_manager as _dm
        monkeypatch.setattr(
            _dm.download_manager, "set_installing", lambda *a, **kw: None
        )

        fake_pkg = tmp_path / "fake.exe"
        fake_pkg.write_bytes(b"fake")
        result = mgr._install_exe(fake_pkg, install_options={"silent": True})

        assert result is True, (
            f"_install_exe (dev mode) returned False; "
            f"captured_cmd={captured_cmd!r}"
        )
        cmd = captured_cmd["cmd"]
        assert any(
            arg.startswith(f'/DIR="{target_dir}"') for arg in cmd
        ), (
            f"Dev-mode Inno Setup command must include ``/DIR=\"{target_dir}\"`` "
            f"so the install goes to the resolved directory. Got cmd: {cmd!r}"
        )

    def test_install_exe_no_longer_has_diagnostic_mode_b_comment(
        self, installer_module,
    ):
        """The leftover ``Diagnostic mode B`` debug comment must NOT
        appear in installer.py — a future grep should trip if anyone
        re-introduces the no-/DIR experiment."""
        installer_path = (
            Path(__file__).resolve().parents[2] / "ota" / "core" / "installer.py"
        )
        text = installer_path.read_text(encoding="utf-8")
        assert "Diagnostic mode B" not in text, (
            "installer.py still contains the ``Diagnostic mode B`` "
            "comment that explained omitting ``/DIR=``. That "
            "diagnostic is over — ``/DIR=`` is now mandatory."
        )

    def test_install_msi_terminates_lock_holders(
        self, installer_module, monkeypatch, tmp_path
    ):
        """``_install_msi`` MUST pre-terminate processes that could
        hold file locks in the install directory. Without this,
        ``REINSTALL=ALL`` hits "Another installation is in progress"
        or rolls back when msiexec tries to overwrite the running exe."""
        monkeypatch.setattr(sys, "platform", "win32")
        monkeypatch.setattr(sys, "frozen", True, raising=False)

        mgr = installer_module.InstallationManager()

        target_dir = tmp_path / "MSIInstall"
        target_dir.mkdir()

        monkeypatch.setattr(
            mgr, "_get_current_windows_install_dir", lambda: target_dir
        )

        # Stub subprocess.Popen inside installer so we don't spawn a
        # real msiexec. Just record the cmd we were given.
        import subprocess as sp_module
        captured = {"calls": []}

        real_popen = sp_module.Popen

        def fake_popen(cmd, *a, **kw):
            captured["calls"].append(list(cmd))
            # Return a fake Popen object whose .pid exists.
            fake_proc = type("FakeP", (), {"pid": 12345})()
            return fake_proc

        monkeypatch.setattr(installer_module.subprocess, "Popen", fake_popen)

        # Stub the BAT launcher so we don't try to write a .bat file.
        monkeypatch.setattr(
            installer_module.InstallationManager,
            "_launch_windows_installer_delayed",
            lambda self, cmd, delay_seconds=3: 99999,
        )
        # Stub download_manager.
        from ota.core import download_manager as _dm
        monkeypatch.setattr(
            _dm.download_manager, "set_installing", lambda *a, **kw: None
        )

        # Track whether _terminate_processes_in_dir was called for the
        # install_dir. The MSI path MUST call this — same reason as
        # the Inno Setup path.
        terminate_calls = []
        real_terminate = mgr._terminate_processes_in_dir

        def fake_terminate(target_dir, *args, **kwargs):
            terminate_calls.append(target_dir)
            return real_terminate.__wrapped__(target_dir, *args, **kwargs) if hasattr(real_terminate, "__wrapped__") else None

        # Simpler: replace with a tracking stub.
        monkeypatch.setattr(
            installer_module.InstallationManager,
            "_terminate_processes_in_dir",
            lambda self, td, **kw: terminate_calls.append(Path(td)),
        )

        fake_pkg = tmp_path / "fake.msi"
        fake_pkg.write_bytes(b"fake")
        result = mgr._install_msi(fake_pkg, install_options={"silent": True})

        assert result is True
        assert any(Path(target_dir) == Path(c) for c in terminate_calls), (
            f"_install_msi must call _terminate_processes_in_dir({target_dir}) "
            f"so file locks on the install dir are released before "
            f"msiexec starts writing. Got terminate calls: {terminate_calls!r}"
        )


# ---------------------------------------------------------------------------
# Regression: Windows branch of _terminate_processes_in_dir MUST call taskkill
# ---------------------------------------------------------------------------


class TestTerminateProcessesWindowsBranch:
    """Bug 2026-09-16: the Windows branch of ``_terminate_processes_in_dir``
    was a literal ``pass`` (PIDs collected but never killed). Inno Setup's
    ``/CLOSEAPPLICATIONS`` only matches windowed apps, so child Chromium
    helpers (``QtWebEngineProcess.exe``) survived the Python exit and held
    file locks. Result: "DeleteFile failed; error code 5. 拒绝访问" on
    eCan.cn.exe at install time. This regression test pins the fix."""

    def test_windows_branch_invokes_taskkill_per_pid(
        self, installer_module, monkeypatch, tmp_path
    ):
        """Each PID in ``pids_to_kill`` must be passed to ``taskkill /F /PID``."""
        # Stub psutil — install it if missing (it's already a hard dep
        # for real OTA paths but the test env may not have it).
        try:
            import psutil  # noqa: F401
            psutil_available = True
        except ImportError:
            psutil_available = False

        if not psutil_available:
            pytest.skip("psutil not installed in test env; can't mock process_iter")

        # Force sys.platform to win32 BEFORE constructing InstallationManager
        # (the constructor captures self.platform = sys.platform).
        monkeypatch.setattr(installer_module.sys, "platform", "win32")
        monkeypatch.setattr(installer_module.os, "getpid", lambda: 99999)

        # Install the directory under tmp_path so the fake process's
        # exe path can resolve inside it.
        install_dir = tmp_path / "eCan.cn"
        install_dir.mkdir()

        # Fake psutil.process_iter: emit one fake "eCan.cn.exe" whose
        # exe path resolves under install_dir. The function under test
        # walks ``exe_path.parents`` to find processes "in" target_dir,
        # so the parent chain must include install_dir.
        fake_proc = type("FakeProc", (), {})()
        fake_proc.info = {
            "pid": 12345,
            "name": "eCan.cn.exe",
            "exe": str(install_dir / "eCan.cn.exe"),
        }
        monkeypatch.setattr(
            "psutil.process_iter",
            lambda attrs: iter([fake_proc]),
        )

        captured_calls = []

        class FakeCompletedProcess:
            returncode = 0
            stdout = ""
            stderr = ""

        def fake_run(cmd, *args, **kwargs):
            captured_calls.append(list(cmd))
            return FakeCompletedProcess()

        monkeypatch.setattr(
            installer_module.subprocess, "run", fake_run
        )

        # Make current process name resolve to "eCan.cn.exe" so the
        # function's proc_names set actually matches our fake proc.
        monkeypatch.setattr(
            installer_module.InstallationManager,
            "_get_current_process_name",
            lambda self: "eCan.cn.exe",
        )

        mgr = installer_module.InstallationManager()
        mgr._terminate_processes_in_dir(
            target_dir=install_dir,
            timeout_seconds=1.0,
        )

        # Filter to the taskkill calls.
        taskkill_calls = [
            c for c in captured_calls
            if c and "taskkill.exe" in str(c[0]).lower()
        ]
        assert taskkill_calls, (
            "REGRESSION 2026-09-16: _terminate_processes_in_dir did NOT "
            "invoke taskkill.exe on Windows. eCan.cn.exe (PID 12345) "
            "is still running after this call, so Inno Setup will "
            "fail with ERROR_ACCESS_DENIED when trying to overwrite "
            "the running exe. Subprocess calls seen: "
            f"{captured_calls!r}"
        )
        # Verify the PID and /T (kill process tree) flag made it into cmd.
        # QtWebEngineProcess.exe is a CHILD of eCan.cn.exe; without /T
        # the helper survives the parent's exit and keeps file locks open.
        assert any(
            "/PID" in c and "12345" in c and "/T" in c
            for c in taskkill_calls
        ), (
            f"taskkill was called but with wrong args. Need /PID 12345 /T "
            f"(kill process tree so QtWebEngineProcess dies too). Got: {taskkill_calls!r}"
        )


# ---------------------------------------------------------------------------
# Regression: Inno Setup PrepareToInstall must use {srcexe} (not {src})
# ---------------------------------------------------------------------------


class TestInnoSetupPrepareToInstallSrcexe:
    """Bug 2026-09-16: the Inno Setup ``PrepareToInstall`` in
    ``build_system/ecan_build.py`` tried to detect CN vs intl by
    parsing ``ExtractFileName(ExpandConstant('{src}'))``. For a
    self-contained Inno Setup installer, ``{src}`` resolves to the
    temp extraction directory (e.g. ``is-XXXXXX.tmp``), NOT to
    Setup.exe. ``ExtractFileName`` of a directory returns the leaf
    directory name, which never contains ``eCan.cn``, so the
    detection was always wrong and Inno Setup killed ``eCan.exe``
    instead of ``eCan.cn.exe``. The fix: read ``{srcexe}`` (the
    Setup.exe path) and kill BOTH variants as a safety net."""

    BUILD_PY = Path(__file__).resolve().parents[2] / "build_system" / "ecan_build.py"

    def test_prepare_to_install_uses_srcexe(self):
        """The Pascal source must use ``{srcexe}`` to detect the
        installer filename. ``{src}`` returns the temp dir leaf and
        silently breaks CN detection."""
        text = self.BUILD_PY.read_text(encoding="utf-8")
        # Find the PrepareToInstall function body.
        m = re.search(
            r"function PrepareToInstall\(.*?^end;",
            text,
            re.DOTALL | re.MULTILINE,
        )
        assert m, "Could not locate PrepareToInstall in ecan_build.py"
        body = m.group(0)
        # Must reference {srcexe} — that's the Setup.exe path.
        assert "{{srcexe}}" in body, (
            "PrepareToInstall must use ExpandConstant('{srcexe}') to "
            "derive the installer filename. The previous version used "
            "'{src}' which returns the temp extraction directory "
            "(is-XXXXXX.tmp) for self-contained Inno Setup installers, "
            "so CN detection always failed and Inno Setup killed the "
            "wrong exe (eCan.exe instead of eCan.cn.exe). Symptom: "
            "'DeleteFile 失败；错误代码 5. 拒绝访问.' on eCan.cn.exe."
        )
        # And it must NOT use {{src}} in PrepareToInstall — that was
        # the broken detection.
        assert "{{src}}" not in body, (
            "PrepareToInstall still uses ExpandConstant('{src}'), "
            "which returns the temp extraction directory at this "
            "point. This is the bug that produced the 2026-09-16 "
            "OTA failure on Windows for CN users."
        )

    def test_close_applications_filter_includes_qtwebengine_and_python(self):
        """``CloseApplicationsFilter`` must list every process that
        could hold a file lock on the install dir."""
        text = self.BUILD_PY.read_text(encoding="utf-8")
        # Locate the [Setup] block.
        m = re.search(r"\[Setup\].*?^\[", text, re.DOTALL | re.MULTILINE)
        assert m, "Could not locate [Setup] section in ecan_build.py"
        setup_block = m.group(0)
        assert "CloseApplicationsFilter=" in setup_block, (
            "Inno Setup [Setup] block must declare "
            "CloseApplicationsFilter so QtWebEngineProcess.exe, "
            "python.exe, pythonw.exe are closed before file copy. "
            "Without this, those helpers survive Inno Setup's "
            "/CLOSEAPPLICATIONS (which only matches windowed apps) "
            "and keep file handles open on app_context.py etc."
        )
        for needed in ("eCan.cn.exe", "eCan.exe", "qtwebengineprocess.exe", "python.exe", "pythonw.exe"):
            assert needed in setup_block, (
                f"CloseApplicationsFilter is missing {needed!r}. "
                f"Without it Inno Setup /CLOSEAPPLICATIONS won't close "
                f"the matching process and the OTA upgrade fails with "
                f"ERROR_ACCESS_DENIED on file overwrite."
            )

    def test_uninstall_display_icon_uses_run_target(self):
        """``UninstallDisplayIcon`` must point at the actual app exe,
        not at hardcoded ``eCan.exe`` (which is wrong for CN)."""
        text = self.BUILD_PY.read_text(encoding="utf-8")
        assert "UninstallDisplayIcon={{app}}\\eCan.exe" not in text, (
            "UninstallDisplayIcon is still hardcoded to "
            "{app}\\eCan.exe. CN builds install eCan.cn.exe — this "
            "icon path is wrong. Use {run_target} so the icon path "
            "follows the per-app dist_basename."
        )
        assert "UninstallDisplayIcon={run_target}" in text, (
            "UninstallDisplayIcon must use {run_target} so CN/Intl "
            "builds point at the correct exe (eCan.cn.exe vs eCan.exe)."
        )


# ---------------------------------------------------------------------------
# Installer filename regex must handle both INTL ``eCan-…`` and CN ``eCan.cn-…``
# ---------------------------------------------------------------------------


class TestInstallerFilenameRegex:
    """``install_state._INSTALLER_VERSION_RE`` is used by the stale-installer
    cleanup at app startup to decide which ``<appdata>/ota_downloads/*.exe``
    are obsolete. If it parses a CN filename like ``eCan.cn-1.0.0-...-Setup.exe``
    wrong, the cleanup never deletes CN installers and the download dir
    grows unbounded across upgrades.

    The pattern MUST match both:
        eCan-{ver}-{platform}-{arch}-{setup}.exe               (INTL)
        eCan.cn-{ver}-{platform}-{arch}-{setup}.exe            (CN)

    And capture ``ver`` exactly — nothing before ``ver`` and nothing after
    ``-{platform}``.
    """

    INSTALL_STATE_PY = (
        Path(__file__).resolve().parents[2]
        / "ota" / "core" / "install_state.py"
    )

    def _regex(self):
        """Pull the compiled regex object out of install_state.py at import time."""
        # Import lazily so the test doesn't drag in the full OTA stack on
        # collection. The module-level regex is constructed at import.
        import importlib
        for _name in list(sys.modules):
            if _name == "ota.core.install_state":
                del sys.modules[_name]
        mod = importlib.import_module("ota.core.install_state")
        return mod._INSTALLER_VERSION_RE

    @pytest.mark.parametrize(
        "filename,expected_version",
        [
            # INTL: Windows
            ("eCan-1.0.0-windows-amd64-Setup.exe", "1.0.0"),
            ("eCan-26.05.03.22.22-windows-amd64-Setup.exe", "26.05.03.22.22"),
            # CN: Windows — the bug we just fixed
            ("eCan.cn-1.0.0-windows-amd64-Setup.exe", "1.0.0"),
            ("eCan.cn-26.05.03.22.22-windows-amd64-Setup.exe", "26.05.03.22.22"),
            # INTL: macOS
            ("eCan-1.0.0-macos-amd64.dmg", "1.0.0"),
            ("eCan-1.0.0-macos-amd64.pkg", "1.0.0"),
            # CN: macOS
            ("eCan.cn-1.0.0-macos-amd64.dmg", "1.0.0"),
            ("eCan.cn-1.0.0-macos-amd64.pkg", "1.0.0"),
            # INTL: Linux
            ("eCan-1.0.0-linux-amd64.AppImage", "1.0.0"),
            ("eCan-1.0.0-linux-amd64.deb", "1.0.0"),
            # CN: Linux
            ("eCan.cn-1.0.0-linux-amd64.AppImage", "1.0.0"),
            ("eCan.cn-1.0.0-linux-amd64.deb", "1.0.0"),
            # Case-insensitive (some S3 buckets normalise case)
            ("ECAN-1.0.0-WINDOWS-AMD64-SETUP.EXE", "1.0.0"),
            ("ECAN.CN-1.0.0-WINDOWS-AMD64-SETUP.EXE", "1.0.0"),
        ],
    )
    def test_filename_regex_extracts_version(self, filename, expected_version):
        regex = self._regex()
        match = regex.match(filename)
        assert match, f"regex did not match {filename!r}"
        assert match.group("version") == expected_version, (
            f"version capture wrong for {filename!r}: "
            f"expected {expected_version!r}, got {match.group('version')!r}"
        )

    @pytest.mark.parametrize(
        "filename",
        [
            # Filenames that must NOT match (no platform token)
            "eCan-1.0.0.exe",
            "eCan.cn-1.0.0.exe",
            # Wrong app prefix
            "eCanio-1.0.0-windows-amd64.exe",
            # Random suffix pretending to be platform
            "eCan-1.0.0-windowsill-amd64.exe",  # "windowsill" doesn't match the alternation
        ],
    )
    def test_filename_regex_rejects_non_matching(self, filename):
        regex = self._regex()
        match = regex.match(filename)
        assert not match, (
            f"regex should NOT have matched {filename!r} (got "
            f"version={match.group('version') if match else None!r})"
        )

    def test_regex_source_handles_cn_via_optional_suffix(self):
        r"""Static check on the regex source: it MUST contain ``(?:\.cn)?``
        so a future refactor that removes it trips this test."""
        text = self.INSTALL_STATE_PY.read_text(encoding="utf-8")
        # Locate the regex literal.
        m = re.search(
            r"_INSTALLER_VERSION_RE\s*=\s*re\.compile\(\s*r\"([^\"]+)\"",
            text,
        )
        assert m, "Could not locate _INSTALLER_VERSION_RE in install_state.py"
        pattern = m.group(1)
        assert r"(?:\.cn)?" in pattern, (
            "regex must allow optional ``.cn`` after ``ecan``; without "
            "this the lazy version capture consumes ``.cn-1.0.0`` for "
            "CN installers and the cleanup never deletes them."
        )


# ---------------------------------------------------------------------------
# handle_pending_install_cleanup: must clean up stale download_dir files
# even when the state file's package_path is empty / missing
# ---------------------------------------------------------------------------


class TestHandlePendingInstallCleanup:
    """``handle_pending_install_cleanup`` runs on every app startup. When
    the previous OTA succeeded but the state file somehow lost its
    ``package_path`` field, we MUST still scan ``<appdata>/ota_downloads/``
    and remove any leftover installer packages. Otherwise stale 100+ MB
    EXEs accumulate forever across upgrades."""

    @pytest.fixture
    def state_module(self, monkeypatch, tmp_path):
        """Import ``install_state`` with ``app_info.appdata_path`` pinned
        to ``tmp_path`` so writes/reads stay inside the test sandbox."""
        from config.app_info import app_info  # type: ignore
        monkeypatch.setattr(app_info, "appdata_path", str(tmp_path))
        # Drop any cached import so the module re-binds against our
        # monkeypatched appdata_path (module-level _get_state_file_path
        # reads app_info.appdata_path each call, but pinning here is
        # still the right test seam).
        for _name in list(sys.modules):
            if _name == "ota.core.install_state":
                del sys.modules[_name]
        return __import__("ota.core.install_state", fromlist=["*"])

    def test_clean_stale_files_when_package_path_empty(
        self, state_module, tmp_path, monkeypatch
    ):
        """When state exists with empty package_path, leftover installers
        in download_dir MUST still be removed."""
        # Write a state file with package_path deliberately empty.
        state_module.write_pending_install_state(
            target_version="2.0.0",
            package_path="",  # empty — simulate lost package_path
            logger=None,
            target_version_core="",
        )
        # Create a stale installer file that should be cleaned up.
        download_dir = tmp_path / "ota_downloads"
        download_dir.mkdir(exist_ok=True)
        stale = download_dir / "eCan-1.0.0-windows-amd64-Setup.exe"
        stale.write_bytes(b"fake-installer-bytes")
        # And a state file pointing at the new version — current_version
        # matches target_version so handle_pending_install_cleanup
        # takes the success path.
        monkeypatch.setattr(state_module.app_info, "version", "2.0.0")

        result = state_module.handle_pending_install_cleanup(
            current_version="2.0.0", logger=None
        )

        assert result is True, (
            "handle_pending_install_cleanup should return True when "
            "current_version matches target_version"
        )
        assert not stale.exists(), (
            "Stale installer was NOT cleaned up despite successful "
            "install. handle_pending_install_cleanup must scan "
            "download_dir even when the state file's package_path "
            "field is empty."
        )

    def test_clean_stale_files_when_package_path_already_deleted(
        self, state_module, tmp_path, monkeypatch
    ):
        """When the package was already deleted but other stale files
        remain, the cleanup must still wipe them."""
        # Point state at a path that doesn't exist (already deleted).
        ghost_package = tmp_path / "ota_downloads" / "eCan-1.0.0-windows-amd64-Setup.exe"
        state_module.write_pending_install_state(
            target_version="2.0.0",
            package_path=str(ghost_package),
            logger=None,
            target_version_core="",
        )
        download_dir = tmp_path / "ota_downloads"
        download_dir.mkdir(exist_ok=True)
        # The package itself doesn't exist (simulating external cleanup).
        # But a different stale installer from a previous upgrade does.
        other_stale = download_dir / "eCan-1.0.5-windows-amd64-Setup.exe"
        other_stale.write_bytes(b"more-fake-bytes")

        monkeypatch.setattr(state_module.app_info, "version", "2.0.0")

        result = state_module.handle_pending_install_cleanup(
            current_version="2.0.0", logger=None
        )

        assert result is True
        assert not other_stale.exists(), (
            "Other stale installer was NOT cleaned up when the "
            "recorded package_path was already gone. The cleanup "
            "loop must keep running after the package_path branch."
        )

    def test_keeps_partial_and_quarantine_files_intact(
        self, state_module, tmp_path, monkeypatch
    ):
        """``.partial`` and ``.corrupt-*`` files are managed by the
        atomic-write machinery and the corrupt-state quarantine — the
        install cleanup must NOT delete them, or we'd mask the original
        failure mode for the next startup."""
        state_module.write_pending_install_state(
            target_version="2.0.0",
            package_path="",
            logger=None,
            target_version_core="",
        )
        download_dir = tmp_path / "ota_downloads"
        download_dir.mkdir(exist_ok=True)
        partial = download_dir / ".eCan-2.0.0-Setup.exe.partial"
        partial.write_bytes(b"incomplete")
        quarantine = download_dir / ".eCan-1.0.0.exe.corrupt-1700000000"
        quarantine.write_bytes(b"corrupt-state")

        monkeypatch.setattr(state_module.app_info, "version", "2.0.0")

        state_module.handle_pending_install_cleanup(
            current_version="2.0.0", logger=None
        )

        assert partial.exists(), (
            "Atomic-write ``.partial`` files must survive the install "
            "cleanup — those are managed by the partial-file sweeper, "
            "not by handle_pending_install_cleanup."
        )
        assert quarantine.exists(), (
            "Quarantined ``.corrupt-*`` files must survive the install "
            "cleanup — those are for postmortem and must not be silently "
            "deleted by a successful-install branch."
        )


# ---------------------------------------------------------------------------
# Atomic write: torn writes never leave a half-written state file
# ---------------------------------------------------------------------------


class TestAtomicWriteText:
    """``_atomic_write_text`` writes to a temp file, fsyncs, and renames
    onto the destination. If a regression drops the fsync or the rename,
    a power-loss mid-write would leave a 0-byte state file and the next
    OTA cycle would silently think no upgrade was in flight."""

    @pytest.fixture
    def state_module(self, monkeypatch, tmp_path):
        from config.app_info import app_info  # type: ignore
        monkeypatch.setattr(app_info, "appdata_path", str(tmp_path))
        for _name in list(sys.modules):
            if _name == "ota.core.install_state":
                del sys.modules[_name]
        return __import__("ota.core.install_state", fromlist=["*"])

    def test_atomic_write_overwrites_existing_file(self, state_module, tmp_path):
        """A second write replaces the first; readers never see a torn mix."""
        target = tmp_path / "state.json"
        state_module._atomic_write_text(target, '{"a": 1}')
        state_module._atomic_write_text(target, '{"a": 2}')
        assert target.read_text(encoding="utf-8") == '{"a": 2}'

    def test_atomic_write_creates_missing_parent(self, state_module, tmp_path):
        """First write into a non-existent nested directory must create
        the parents — install_state relies on this when ``appdata_path``
        is fresh."""
        target = tmp_path / "deep" / "nested" / "state.json"
        state_module._atomic_write_text(target, '{"a": 1}')
        assert target.is_file()
        assert target.read_text(encoding="utf-8") == '{"a": 1}'

    def test_atomic_write_no_partial_file_left_on_success(
        self, state_module, tmp_path
    ):
        """After a successful write the sibling ``.partial`` file MUST
        be gone (it was renamed onto the destination)."""
        target = tmp_path / "state.json"
        state_module._atomic_write_text(target, '{"a": 1}')
        partial = target.parent / f".{target.name}.partial"
        assert not partial.exists(), (
            f"Sibling .partial file was not cleaned up after rename: {partial}"
        )


# ---------------------------------------------------------------------------
# Corrupt state file must be quarantined, not retried forever
# ---------------------------------------------------------------------------


class TestReadPendingInstallStateQuarantine:
    """``read_pending_install_state`` MUST move a corrupt JSON file to a
    ``.corrupt-<ts>`` quarantine so subsequent reads return ``None`` and
    the install cleanup can run normally. Otherwise every startup would
    log the same JSON error and never recover."""

    @pytest.fixture
    def state_module(self, monkeypatch, tmp_path):
        from config.app_info import app_info  # type: ignore
        monkeypatch.setattr(app_info, "appdata_path", str(tmp_path))
        for _name in list(sys.modules):
            if _name == "ota.core.install_state":
                del sys.modules[_name]
        return __import__("ota.core.install_state", fromlist=["*"])

    def test_corrupt_state_is_quarantined(self, state_module, tmp_path):
        state_path = tmp_path / "ota_install_state.json"
        # Write something that is definitely not valid JSON.
        state_path.write_text("{not valid json", encoding="utf-8")

        result = state_module.read_pending_install_state(logger=None)

        assert result is None, "Corrupt state should read as None"
        # The active slot must be cleared (or quarantined) so the
        # next startup doesn't see the same broken bytes.
        assert not state_path.exists() or any(
            p.name.startswith(".ota_install_state.json.corrupt-")
            for p in state_path.parent.iterdir()
        ), (
            "Corrupt state file was NOT moved out of the active slot. "
            "read_pending_install_state must quarantine it so subsequent "
            "reads return None and cleanup runs."
        )

    def test_valid_state_returns_payload(self, state_module, tmp_path):
        state_path = tmp_path / "ota_install_state.json"
        state_path.write_text(
            '{"target_version": "2.0.0", "package_path": "/tmp/x.exe"}',
            encoding="utf-8",
        )
        result = state_module.read_pending_install_state(logger=None)
        assert result == {
            "target_version": "2.0.0",
            "package_path": "/tmp/x.exe",
        }


# ---------------------------------------------------------------------------
# Disk space pre-flight check before download (Windows OTA failure #2)
# ---------------------------------------------------------------------------


class TestDiskSpaceCheck:
    """``PackageManager.download_package`` must verify free disk space before
    starting a download. A 600 MB installer on a near-full drive silently
    truncates the file and the subsequent signature check fails with a
    misleading "hash mismatch" — the real problem is disk space. This
    regression test pins the fix.

    The check must abort the download even when the surrounding code has a
    broad ``except (OSError, AttributeError)`` block. ``IOError`` is an
    alias for ``OSError`` on Python 3, so the previous ``raise IOError``
    was caught by that handler — a hard-to-spot bug that left disk-full
    customers silently downloading a truncated installer. The current
    implementation raises ``RuntimeError`` instead, which is unrelated to
    ``OSError`` and so cannot be swallowed by the outer handler.
    """

    def test_download_aborts_when_disk_full(self, monkeypatch, tmp_path):
        """When free space < 2× file_size, download_package raises RuntimeError.

        The check raises ``RuntimeError`` (NOT ``OSError``/``IOError``)
        so it cannot be caught by the surrounding ``except (OSError,
        AttributeError)`` retry handler. The previous version raised
        ``IOError`` and was silently swallowed — see Bug 2026-09-16.
        """
        from ota.core.package_manager import PackageManager, UpdatePackage

        # Stub download_dir so we control where shutil.disk_usage probes.
        stub_dir = tmp_path / "dl"
        stub_dir.mkdir()

        # Stub disk_usage to report only 10 MB free (enough for 1× file_size
        # but not 2×).  The real disk might have TB free so we must mock.
        import shutil
        fake_total = 100 * 1024 * 1024   # 100 MB
        fake_used  = 90  * 1024 * 1024   # 90 MB used
        fake_free  = 10  * 1024 * 1024   # 10 MB free — less than 2× file_size
        monkeypatch.setattr(
            shutil, "disk_usage", lambda p: (fake_total, fake_used, fake_free)
        )

        pkg_mgr = PackageManager(download_dir=str(stub_dir))

        pkg = UpdatePackage(
            version="3.0.0",
            download_url="http://example.com/eCan-3.0.0.exe",
            file_size=8 * 1024 * 1024,   # 8 MB package → 2× = 16 MB needed
            signature="deadbeef",
            description="",
        )

        # Should raise RuntimeError (NOT IOError/OSError — those would be
        # caught by the outer handler and the download would silently
        # proceed on a truncated file).
        with pytest.raises(RuntimeError) as excinfo:
            pkg_mgr.download_package(pkg, progress_callback=None)
        # The message must clearly indicate disk space (not a generic
        # network error), so the user can free up space and retry.
        assert "disk space" in str(excinfo.value).lower()
        # The RuntimeError must NOT be wrapped in IOError/OSError — those
        # would be caught by the surrounding handler. A direct raise of
        # RuntimeError (with no __cause__) is what guarantees the abort.
        assert excinfo.type is RuntimeError, (
            f"Expected direct RuntimeError, got {excinfo.type.__name__}; "
            f"if it's wrapped in IOError the outer except will swallow it."
        )

    def test_disk_full_not_swallowed_by_outer_handler(self, monkeypatch, tmp_path):
        """Regression pin: ensure the disk-full raise is NOT caught by any
        ``except OSError`` in the download retry loop.

        The 2026-09-16 bug was that ``raise IOError`` inside a
        ``try: ... except (OSError, AttributeError)`` block was caught
        by that very handler (because ``IOError`` IS ``OSError`` on
        Python 3). We pin the fix by making sure the raised exception
        is *not* an ``OSError`` subclass.
        """
        from ota.core.package_manager import PackageManager, UpdatePackage

        stub_dir = tmp_path / "dl"
        stub_dir.mkdir()
        import shutil
        monkeypatch.setattr(
            shutil, "disk_usage",
            lambda p: (100 * 1024 * 1024, 90 * 1024 * 1024, 10 * 1024 * 1024)
        )

        pkg_mgr = PackageManager(download_dir=str(stub_dir))
        pkg = UpdatePackage(
            version="3.0.0",
            download_url="http://example.com/eCan-3.0.0.exe",
            file_size=8 * 1024 * 1024,
            signature="deadbeef",
            description="",
        )

        try:
            pkg_mgr.download_package(pkg, progress_callback=None)
            pytest.fail("download_package should have raised on disk-full")
        except RuntimeError as e:
            # The whole point: RuntimeError must NOT inherit from OSError,
            # otherwise the outer ``except (OSError, AttributeError)`` in
            # download_package will swallow the disk-full failure.
            assert not isinstance(e, OSError), (
                "Disk-full raise must NOT be an OSError subclass — that "
                "would let the surrounding retry handler swallow it and "
                "the download would silently proceed."
            )
            # The raised exception should propagate cleanly (no wrapping),
            # so the download caller can distinguish disk-full from a
            # network error in its own error handling.
            assert e.__cause__ is None and e.__context__ is None, (
                "Disk-full RuntimeError must be raised directly (no wrapping); "
                "a wrapped exception may confuse the retry handler."
            )

    def test_download_succeeds_when_space_sufficient(self, monkeypatch, tmp_path):
        """When free space ≥ 2× file_size, download proceeds (no disk-full error).

        Mock ``requests.get`` to raise immediately so the test completes in
        <1 s instead of waiting for ``127.0.0.1:1`` to time out (default
        connect_timeout in ``download_package`` is 30 s, and the retry
        loop can run up to 3 attempts × 2 URLs = 6 connection attempts).
        The point of this test is to verify that the disk-space gate
        passes — it does NOT verify network failure handling, so
        short-circuiting the network layer is appropriate.
        """
        from ota.core.package_manager import PackageManager, UpdatePackage

        stub_dir = tmp_path / "dl"
        stub_dir.mkdir()

        # Stub disk_usage to report 500 MB free — well above 2× file_size.
        import shutil
        monkeypatch.setattr(
            shutil, "disk_usage",
            lambda p: (1024 * 1024 * 1024, 524 * 1024 * 1024, 500 * 1024 * 1024)
        )

        # Stub requests.get to raise immediately. This proves the
        # disk-space gate PASSED (no RuntimeError before this point).
        import requests as _requests
        def _fake_get(*a, **kw):
            raise _requests.exceptions.ConnectionError(
                "mocked: test does not exercise network"
            )
        monkeypatch.setattr(_requests, "get", _fake_get)

        pkg_mgr = PackageManager(download_dir=str(stub_dir))
        pkg = UpdatePackage(
            version="3.0.0",
            download_url="http://example.com/eCan-3.0.0.exe",
            file_size=8 * 1024 * 1024,
            signature="deadbeef",
            description="",
        )

        # Should fail on the mocked network error — proves the disk-space
        # gate passed (the gate raises RuntimeError, which is NOT what
        # ConnectionError is, so we never get to the network layer if
        # the gate fires).
        result = pkg_mgr.download_package(pkg, progress_callback=None)
        assert result is False


# ---------------------------------------------------------------------------
# Idempotent install guard (double-click / rapid-click protection)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    sys.platform != "win32",
    reason="Windows-only test: ``sys.frozen`` is a Windows-specific attribute "
           "added by PyInstaller/cx_Freeze, and the idempotent guard is "
           "exercised inside the Windows install code path",
)
class TestIdempotentInstallGuard:
    """``InstallationManager._install_in_progress`` is a class-level bool that
    prevents two concurrent ``install_package`` calls from launching two
    installers.  This guards the race where the user double-clicks
    "Install Now" before the first InstallWorker thread has started."""

    def test_second_install_returns_false(self, installer_module, monkeypatch, tmp_path):
        """A second install_package call is rejected while the first is running."""
        installer_module.InstallationManager._install_in_progress = False

        mgr = installer_module.InstallationManager()

        # Fake package that doesn't exist so we never reach the real install path.
        fake_pkg = tmp_path / "does_not_exist.exe"
        monkeypatch.setattr(sys, "frozen", False)
        monkeypatch.setattr(sys, "platform", "win32")

        # First call should succeed in guard (fails on missing file).
        r1 = mgr.install_package(fake_pkg, install_options={"silent": True})
        assert r1 is False   # guard passed, but file missing

        # Second call while guard is still held.
        r2 = mgr.install_package(fake_pkg, install_options={"silent": True})
        assert r2 is False, (
            "Second install_package should return False while guard is held. "
            "This prevents double-click from launching two installers."
        )

    def test_guard_released_after_exception(self, installer_module, monkeypatch, tmp_path):
        """If install_package raises, the guard is released so retry works."""
        installer_module.InstallationManager._install_in_progress = False
        mgr = installer_module.InstallationManager()

        # Force an exception by passing a non-Path.
        r1 = mgr.install_package(None, install_options={})
        assert r1 is False

        # Guard must be released so retry succeeds (fails for different reason).
        r2 = mgr.install_package(None, install_options={})
        assert r2 is False   # still fails, but because of None, not because of guard


# ---------------------------------------------------------------------------
# Trailing backslash normalisation in registry install dir (Windows OTA bug)
# ---------------------------------------------------------------------------


# Test imports ``winreg`` (Windows-only stdlib) and exercises the registry
# lookup branch of ``_get_current_windows_install_dir``. Skip on non-Windows
# so the suite is collectable on macOS/Linux dev workstations.
@pytest.mark.skipif(
    sys.platform != "win32",
    reason="Windows-only test: ``winreg`` is Windows-only and the registry "
           "lookup branch only runs on Windows",
)
class TestRegistryPathTrailingBackslash:
    """``_get_current_windows_install_dir`` strips trailing backslashes from
    the registry value.  Inno Setup sometimes writes the InstallLocation with
    a trailing ``\\``, and bare ``Path(value)`` then resolves to a path
    that ``exists()`` returns False for — causing OTA to fall back to the
    default directory instead of preserving the user's custom install path."""

    def test_trailing_backslash_stripped(self, installer_module, monkeypatch):
        """Registry value ``D:\\MyApps\\eCan\\`` is normalised to ``D:\\MyApps\\eCan``."""
        import winreg

        mgr = installer_module.InstallationManager()

        captured_key = {}

        class FakeOpenKey:
            def __init__(self, root, subkey, *_):
                captured_key["root"] = root
                captured_key["subkey"] = subkey

            def __enter__(self):
                return self

            def __exit__(self, *a):
                pass

            def QueryValueEx(self, name):
                # Return a path WITH a trailing backslash — the bug trigger.
                if name == "InstallLocation":
                    return "D:\\MyApps\\eCan\\", winreg.REG_SZ
                raise FileNotFoundError(name)

        monkeypatch.setattr(winreg, "OpenKey", FakeOpenKey)
        monkeypatch.setattr(
            installer_module, "get_windows_app_id", lambda *a: "test-guid"
        )
        monkeypatch.setattr(sys, "platform", "win32")

        result = mgr._get_current_windows_install_dir()

        # Must return the normalised path, not the trailing-backslash version.
        assert result is not None
        assert str(result).rstrip("\\/") == str(result), (
            f"Result still has trailing slash: {result!r}"
        )
        assert "eCan" in str(result)


# ---------------------------------------------------------------------------
# Inno Setup directives audit (negative regression for v0.9.97w rebuild)
# ---------------------------------------------------------------------------
# Pins the v0.9.97v-baseline guarantee that the [Setup] section only
# contains directives Inno Setup 6.x actually recognises. ``LongPathsEnabled``
# was added in commit fb1780d5b under the assumption that Inno Setup has
# such a directive; Inno Setup 6.7.1 (the CI runner) rejects it with
# "Unrecognized [Setup] section directive" and aborts the install. The
# tag v0.9.97v had no such directive and built cleanly.
# ---------------------------------------------------------------------------


class TestInnoSetupNoUnknownDirectives:
    """Negative regression test: the ``[Setup]`` section must NOT contain
    directives Inno Setup 6.x does not recognise.

    Concretely: ``LongPathsEnabled`` is not an Inno Setup directive in any
    released version — it was a hallucination added by fb1780d5b. The
    ``iscc.exe`` on the Windows CI runner rejects it with::

        Error on line 41 in setup.iss:
          Unrecognized [Setup] section directive "LongPathsEnabled"

    and aborts the build. v0.9.97v had no such directive and built cleanly.
    This test pins that the directive never creeps back in via a future
    refactor of ``build_system/ecan_build.py``.

    If a real Windows long-path workaround is needed (e.g. for users with
    deep ``LOCALAPPDATA`` paths), it must be implemented at the
    manifest / ``requireAdmin`` / registry-override layer — NOT by adding
    a non-existent IS directive.
    """

    def test_long_paths_enabled_not_present_in_setup_section(self):
        """``LongPathsEnabled`` is not an Inno Setup directive; ``iscc`` rejects it.

        The fix in commit aa3115db9 removed the line; this test guards
        against a future regression that re-adds it.
        """
        build_py = Path(__file__).resolve().parents[2] / "build_system" / "ecan_build.py"
        text = build_py.read_text(encoding="utf-8")

        m = re.search(r"\[Setup\].*?^\[", text, re.DOTALL | re.MULTILINE)
        assert m, "Could not locate [Setup] section in ecan_build.py"
        section = m.group(0)

        assert "LongPathsEnabled" not in section, (
            "[Setup] section must NOT contain ``LongPathsEnabled`` — "
            "it is not a valid Inno Setup directive in any released version, "
            "and ISCC aborts with 'Unrecognized [Setup] section directive'. "
            "v0.9.97v (the last known-good build) did not have it. "
            "Use a manifest / ``requireAdmin`` / registry-override approach "
            "instead if long-path support is genuinely required."
        )

