#!/usr/bin/env python3
"""
Regression test for .gitignore coverage of sensitive local-only files.

Two artifacts MUST be ignored before any commit:

1. ``.wx_st_*`` — WeChat session token JWT file. Generated by
   ``auth/auth_manager.py:_save_wechat_session_token`` (constant
   ``_WECHAT_SESSION_TOKEN_FILE_PREFIX = ".wx_st"``). The base64 suffix
   encodes the username. Holds a long-lived session token: if committed,
   anyone with the file can authenticate as the user.

2. ``+86 *_local/`` — CloudBase phone-login per-user data directories.
   ``gui/MainGUI.py:1497-1505`` sets ``log_user = +86 <phone>_local`` for
   the phone-login flow (the whole ``+86 13880917374`` becomes the
   local_part because the string contains no '@'). The dir holds SQLite
   DBs (ecan_base.db, myecb.db), settings.json, lightrag caches, etc.

The existing rules catch the WeChat user-data dir pattern
(``wechat_**_local/``) and the ``+86 *_local/`` pattern is the matching
fix for the phone-login variant. Both files were reportable as
"untracked" until these patterns were added (regression target).

Run:
    python3 -m pytest tests/unit/test_gitignore_sensitive_files.py -v
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


_script_path = Path(__file__).resolve()
_project_root = _script_path
for _ in range(3):  # tests/unit/<file> -> repo root
    _project_root = _project_root.parent


def _git(args: list[str]) -> str:
    """Run git in the repo root and return stdout."""
    proc = subprocess.run(
        ["git", "-C", str(_project_root), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        # git check-ignore returns 1 for "no match" — that's not an error
        if proc.returncode == 1 and proc.stderr.strip() == "":
            return ""
        raise RuntimeError(f"git {args} failed: {proc.stderr}")
    return proc.stdout


def _is_ignored(path: str) -> bool:
    """True if ``git check-ignore`` reports the path is ignored."""
    out = _git(["check-ignore", "-v", path])
    return bool(out.strip())


class TestGitignoreSensitiveFilePatterns:
    """Defends against accidental commit of session tokens and per-user data."""

    # -- WeChat session token ------------------------------------------------

    def test_wx_st_file_is_ignored(self):
        """The ``.wx_st_<base64>`` JWT session token file MUST be ignored.

        Without this rule, the file would show up as untracked and could
        be accidentally ``git add``'d, leaking auth credentials.
        """
        # Use the exact file that exists in this workspace
        # (created by earlier login flow) — if it doesn't exist, the test
        # falls back to a synthetic path; either way the rule must apply.
        existing = list(_project_root.glob(".wx_st_*"))
        if existing:
            sample = existing[0].name
        else:
            sample = ".wx_st_d2VjaGF0XzZlNTdiYTI1MDlhMzlmMDZlZTdhYTQ2Nw=="

        assert _is_ignored(sample), (
            f"{sample} is not covered by .gitignore. "
            "Add the pattern ``.wx_st_*`` to keep WeChat session tokens "
            "out of version control."
        )

    def test_wx_st_pattern_does_not_match_source_files(self):
        """Defensive: the ``.wx_st_*`` pattern must not match files
        without the leading dot or without the underscore separator
        (no false positives on source code like ``wx_st_x``).
        """
        # These should NOT be ignored
        for path in [
            "wx_st_x",  # no leading dot
            "auth/auth_manager.py",  # unrelated source
            "agent/mcp/server/wechat/__init__.py",  # related but not pattern match
        ]:
            if not (_project_root / path).exists():
                continue
            assert not _is_ignored(path), (
                f"{path} was incorrectly ignored by .wx_st_* pattern. "
                "The pattern must only match dotfiles starting with .wx_st_."
            )

    # -- Phone-login local user data dir -------------------------------------

    def test_plus86_phone_local_dir_is_ignored(self):
        """The ``+86 13880917374_local/`` directory (CloudBase phone-login
        per-user data) MUST be ignored. Names are like ``+86 <phone>_local``,
        so the pattern is ``+86 *_local/``.
        """
        existing = list(_project_root.glob("+86*_local"))
        if existing:
            sample = f"{existing[0].name}/ecan_base.db"
        else:
            sample = "+86 13880917374_local/ecan_base.db"

        assert _is_ignored(sample), (
            f"{sample} is not covered by .gitignore. "
            "Add the pattern ``+86 *_local/`` to keep phone-login local "
            "data (SQLite DBs, settings, lightrag caches) out of git."
        )

    def test_plus86_dir_is_ignored_at_root(self):
        """The directory itself (not just contents) must be ignored."""
        # Check the bare directory path
        if (_project_root / "+86 13880917374_local").exists():
            sample = "+86 13880917374_local"
            assert _is_ignored(sample), (
                f"{sample}/ directory is not ignored. "
                "The ``+86 *_local/`` pattern must match the dir itself."
            )

    # -- WeChat-login local user data dir (existing rule) --------------------

    def test_wechat_openid_local_dir_is_ignored(self):
        """The ``wechat_<openid>_local/`` directory is already covered by
        ``wechat_**_local/``. This guards against future refactors that
        might rename the pattern.
        """
        existing = list(_project_root.glob("wechat_*_local"))
        if existing:
            sample = f"{existing[0].name}/ecan_base.db"
        else:
            sample = "wechat_6e57ba2509a39f06ee7aa467_local/ecan_base.db"

        assert _is_ignored(sample), (
            f"{sample} is not covered by .gitignore. The "
            "``wechat_**_local/`` rule must remain for WeChat-login dirs."
        )

    # -- End-to-end: no matching files are reported as untracked -------------

    def test_no_sensitive_files_appear_in_untracked(self):
        """Sanity check: ``git status --porcelain --untracked-files=all``
        must not contain any of the sensitive patterns. This is the
        user-facing smoke test (matches what the user reported).
        """
        out = _git([
            "status", "--porcelain", "--untracked-files=all", "--ignored=no"
        ])
        bad_lines = [
            line for line in out.splitlines()
            if any(
                pat in line
                for pat in (".wx_st_", "+86 ", "wechat_6e57ba2509a39f06ee7aa467")
            )
        ]
        assert not bad_lines, (
            "These sensitive local files are still reported as untracked "
            "(should be ignored by .gitignore):\n"
            + "\n".join(bad_lines)
        )


def main():
    """Allow running as a script (no pytest required)."""
    import pytest
    code = pytest.main([__file__, "-v"])
    sys.exit(code)


if __name__ == "__main__":
    main()
