name: 'Setup Playwright Browsers'
description: 'Install and cache Playwright browsers for browser automation'
inputs:
  platform:
    description: 'Platform (windows, macos, linux)'
    required: true
  arch:
    description: 'Architecture (amd64, aarch64) - for cache key'
    required: false
    default: 'amd64'
  browsers:
    description: 'Browsers to install (comma-separated: chromium,firefox,webkit)'
    required: false
    default: 'chromium'

runs:
  using: 'composite'
  steps:
    - name: Cache Playwright browsers (Windows)
      if: inputs.platform == 'windows'
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Local\ms-playwright
          third_party\ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('requirements-base.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Cache Playwright browsers (macOS)
      if: inputs.platform == 'macos'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/ms-playwright
          third_party/ms-playwright
        key: ${{ runner.os }}-${{ inputs.arch }}-playwright-${{ hashFiles('requirements-base.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.arch }}-playwright-

    - name: Cache Playwright browsers (Linux)
      if: inputs.platform == 'linux'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          third_party/ms-playwright
        key: ${{ runner.os }}-${{ inputs.arch }}-playwright-${{ hashFiles('requirements-base.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.arch }}-playwright-

    - name: Install Playwright browsers (Windows)
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        Write-Host "=== Installing Playwright browsers ===" -ForegroundColor Cyan
        
        # Resolve Python executable (prefer virtualenv if available)
        $PYTHON_EXE = "python"
        if ($env:VIRTUAL_ENV -and (Test-Path "$env:VIRTUAL_ENV\Scripts\python.exe")) {
          $PYTHON_EXE = "$env:VIRTUAL_ENV\Scripts\python.exe"
          Write-Host "Using venv Python: $PYTHON_EXE"
        } else {
          Write-Host "VIRTUAL_ENV not set or python.exe not found in venv; falling back to runner python"
        }
        
        # Check if already cached
        $playwrightCache = "$env:USERPROFILE\AppData\Local\ms-playwright"
        if (Test-Path $playwrightCache) {
          Write-Host "Found cached Playwright browsers at: $playwrightCache"
          $browserDirs = Get-ChildItem -Path $playwrightCache -Directory | Where-Object { 
            $_.Name -like "chromium-*" -or $_.Name -like "firefox-*" -or $_.Name -like "webkit-*" 
          }
          if ($browserDirs) {
            Write-Host "Cached browser versions:"
            $browserDirs | ForEach-Object { Write-Host "  - $($_.Name)" }
          }
        }
        
        # Parse browsers input
        $browsers = "${{ inputs.browsers }}" -split ','
        
        # Ensure playwright package is installed in the chosen interpreter
        try {
          & $PYTHON_EXE - <<'PY'
import importlib, sys
try:
    importlib.import_module('playwright')
    print('[OK] playwright already installed')
except ImportError:
    print('[INFO] Installing playwright into current environment...')
    import subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-U', 'playwright'])
PY
        } catch {
          Write-Host "Failed to verify/install playwright" -ForegroundColor Red
          throw
        }

        # Install each browser
        foreach ($browser in $browsers) {
          $browser = $browser.Trim()
          if ($browser) {
            Write-Host "Installing $browser browser..."
            & $PYTHON_EXE -m playwright install $browser --with-deps
          }
        }
        
        Write-Host "Playwright browsers installed successfully" -ForegroundColor Green

    - name: Install Playwright browsers (Unix)
      if: inputs.platform == 'macos' || inputs.platform == 'linux'
      shell: bash
      run: |
        echo "=== Installing Playwright browsers ==="
        
        # Resolve Python executable (prefer virtualenv if available)
        PYTHON_EXE="python"
        if [ -n "${VIRTUAL_ENV:-}" ] && [ -x "$VIRTUAL_ENV/bin/python" ]; then
          PYTHON_EXE="$VIRTUAL_ENV/bin/python"
          echo "Using venv Python: $PYTHON_EXE"
        else
          echo "VIRTUAL_ENV not set or python not found in venv; falling back to runner python"
        fi
        
        # Determine cache location
        if [ "${{ inputs.platform }}" = "macos" ]; then
          playwright_cache="$HOME/Library/Caches/ms-playwright"
        else
          playwright_cache="$HOME/.cache/ms-playwright"
        fi
        
        # Check if already cached
        if [ -d "$playwright_cache" ]; then
          echo "Found cached Playwright browsers at: $playwright_cache"
          browser_dirs=$(ls -d "$playwright_cache"/{chromium,firefox,webkit}-* 2>/dev/null || true)
          if [ -n "$browser_dirs" ]; then
            echo "Cached browser versions:"
            echo "$browser_dirs" | while read dir; do
              echo "  - $(basename "$dir")"
            done
          fi
        fi
        
        # Parse browsers input
        IFS=',' read -ra BROWSERS <<< "${{ inputs.browsers }}"
        
        # Ensure playwright package is installed in the chosen interpreter
        "$PYTHON_EXE" - <<'PY'
import importlib, sys, subprocess
try:
    importlib.import_module('playwright')
    print('[OK] playwright already installed')
except ImportError:
    print('[INFO] Installing playwright into current environment...')
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-U', 'playwright'])
PY

        # Install each browser
        for browser in "${BROWSERS[@]}"; do
          browser=$(echo "$browser" | xargs)  # Trim whitespace
          if [ -n "$browser" ]; then
            echo "Installing $browser browser..."
            "$PYTHON_EXE" -m playwright install "$browser" --with-deps
          fi
        done
        
        echo "Playwright browsers installed successfully"

