name: 'Setup OTA Dependencies'
description: 'Install and verify OTA update dependencies for Windows and macOS'
inputs:
  platform:
    description: 'Platform (windows, macos)'
    required: true
  verify-only:
    description: 'Only verify dependencies, skip installation'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install OTA dependencies
      if: ${{ inputs.verify_only != 'true' }}
      shell: bash
      run: |
        echo "=== Installing OTA Dependencies ==="
        # Map platform names: macos -> darwin
        if [ "${{ inputs.platform }}" = "macos" ]; then
          SCRIPT_PLATFORM="darwin"
        else
          SCRIPT_PLATFORM="${{ inputs.platform }}"
        fi
        python build_system/install_ota_dependencies.py install --platform $SCRIPT_PLATFORM

    - name: Verify OTA dependencies
      shell: bash
      run: |
        echo "=== Verifying OTA Dependencies ==="
        python build_system/install_ota_dependencies.py verify

    - name: Check OTA installation
      shell: bash
      run: |
        if [ "${{ inputs.platform }}" = "windows" ]; then
          echo "=== Checking winSparkle Installation ==="
          dll_paths=("third_party/winsparkle/winsparkle.dll")
          found=false
          for p in "${dll_paths[@]}"; do
            if [ -f "$p" ]; then
              echo "winSparkle DLL found at: $p"
              size=$(stat -f%z "$p" 2>/dev/null || stat -c%s "$p" 2>/dev/null || echo "unknown")
              echo "   Size: $size bytes"
              found=true
              break
            fi
          done
          if [ "$found" = false ]; then
            echo "[WARN] winSparkle DLL not found in expected locations"
            echo "Searching for winSparkle files..."
            find third_party -name "*sparkle*" -type f 2>/dev/null || echo "No Sparkle files found in third_party"
          fi
        elif [ "${{ inputs.platform }}" = "macos" ]; then
          echo "=== Checking Sparkle Framework Installation ==="
          if [ -d "third_party/sparkle/Sparkle.framework" ]; then
            echo "[OK] Sparkle.framework found"
            framework_size=$(du -sh third_party/sparkle/Sparkle.framework | cut -f1)
            echo "   Size: $framework_size"

            # Check framework structure
            if [ -f "third_party/sparkle/Sparkle.framework/Versions/Current/Sparkle" ]; then
              echo "[OK] Sparkle binary found in framework"
            else
              echo "[WARN] Sparkle binary not found in expected location"
            fi

            if [ -f "third_party/sparkle/sparkle-cli" ]; then
              echo "[OK] Sparkle CLI found"
            else
              echo "[WARN] Sparkle CLI not found"
            fi
          else
            echo "[ERROR] Sparkle.framework not found"
            echo "Searching for Sparkle files..."
            find third_party -name "*parkle*" -type f 2>/dev/null || echo "No Sparkle files found in third_party"
          fi
        fi
